/* Expansion patch maps — extra REAL strengths and REAL brand products for molecules
   defined in the other seed files. One key per salt — duplicate keys overwrite! */
module.exports = {
  "Paracetamol": {
    strengths: ["250 mg/5 ml Syrup", "100 mg/ml Drops"],
    brands: ["Calpol 650", "P-650", "Pacimol 500"],
  },
  "Ibuprofen": { strengths: ["600 mg Tablet"], brands: ["Brufen 600", "Brufen Syrup"] },
  "Diclofenac": { strengths: ["100 mg Suppository"], brands: ["Voveran Emulgel"] },
  "Naproxen": { brands: ["Naxdom 250"] },
  "Etoricoxib": { brands: ["Etoshine 120", "Nucoxia 120", "Etova 60", "Nucoxia 60"] },
  "Metformin": {
    strengths: ["500 mg SR Tablet", "750 mg SR Tablet"],
    brands: ["Glucophage 850", "Glucophage SR 500", "Glycomet 850", "Glycomet 1000"],
  },
  "Glimepiride": { brands: ["Glimy 1"] },
  "Sitagliptin": { brands: ["Istavel 50", "Istavel 25"] },
  "Dapagliflozin": { brands: ["Dapanorm 5"] },
  "Pantoprazole": { brands: ["Pantop 40", "Pantop 20", "Pantocid 20", "Pantop DSR"] },
  "Omeprazole": { brands: ["Ocid 10"] },
  "Esomeprazole": { brands: ["Esoz 20"] },
  "Ondansetron": {
    strengths: ["4 mg/2 ml Injection"],
    brands: ["Ondem 2 Syrup", "Vomikind MD 8", "Emeset Injection"],
  },
  "Domperidone": { brands: ["Domstal Baby Drops"] },
  "Amlodipine": { brands: ["Amlopres 10", "Amlokind 2.5", "Amlovas 5", "Amlovas 2.5"] },
  "Telmisartan": { brands: ["Telsartan 20", "Telmikind 40"] },
  "Losartan": { brands: ["Losar 100"] },
  "Ramipril": { brands: ["Cardace 10", "Ramistar 2.5"] },
  "Metoprolol": {
    strengths: ["100 mg XL Tablet"],
    brands: ["Metolar 100", "Betaloc 50", "Metolar XL 50"],
  },
  "Bisoprolol": { brands: ["Concor 10"] },
  "Atenolol": { brands: ["Tenormin 50"] },
  "Atorvastatin": { brands: ["Atorva 80", "Storvas 10", "Lipvas 10"] },
  "Rosuvastatin": { strengths: ["40 mg Tablet"], brands: ["Rosuvas 20", "Rozavel 20"] },
  "Fenofibrate": { brands: ["Lipicard 200"] },
  "Levothyroxine": { brands: ["Thyronorm 75", "Thyronorm 100", "Eltroxin 50", "Eltroxin 25"] },
  "Vitamin D3 (cholecalciferol)": { brands: ["Uprise D3 60K Capsule", "D-Rise 60K Capsule"] },
  "Vitamin E (tocopherol)": { brands: ["Evion 600"] },
  "Calcium carbonate + Vitamin D3": { brands: ["Shelcal HD"] },
  "Cetirizine": { brands: ["Cetzine Syrup", "Alerid Syrup"] },
  "Levocetirizine": { brands: ["Xyzal Syrup"] },
  "Fexofenadine": { brands: ["Histafree 120"] },
  "Montelukast": { brands: ["Montair 4 Kid", "Montek 5"] },
  "Montelukast + Levocetirizine": { brands: ["Montair LC Kid"] },
  "Fluticasone + Salmeterol": { brands: ["Seroflo 250 Rotacaps"] },
  "Doxofylline": { brands: ["Doxobid 400"] },
  "Azithromycin": {
    strengths: ["200 mg/5 ml Suspension"],
    brands: ["Azee 250", "Azithral 250"],
  },
  "Cefixime": { strengths: ["50 mg/5 ml Dry Syrup"], brands: ["Zifi 100 DT", "Cefolac 200"] },
  "Cefpodoxime": { brands: ["Cepodem 100 Dry Syrup", "Monocef-O 100 DT"] },
  "Ciprofloxacin": { brands: ["Cifran OD 1000"] },
  "Levofloxacin": { brands: ["Levotas 500"] },
  "Amoxicillin": { brands: ["Mox 125 DT"] },
  "Cephalexin": { strengths: ["125 mg/5 ml Syrup"] },
  "Amoxicillin + Clavulanic acid": {
    strengths: ["312 mg/5 ml Dry Syrup"],
    brands: ["Clavam 375", "Clavam 1g", "Clavam 625 Duo"],
  },
  "Cefuroxime + Clavulanic acid": { strengths: ["312.5 mg Tablet", "625 mg Tablet"] },
  "Calcitriol + Calcium + Zinc": { strengths: ["500 mg Softgel"] },
  "Metronidazole": { brands: ["Metrogyl 2% Gel"] },
  "Clindamycin": { brands: ["Clindac A Gel"] },
  "Doxycycline": { strengths: ["200 mg Capsule"] },
  "Tamsulosin": { brands: ["Urimax 0.2", "Veltam 0.4"] },
  "Sildenafil": { brands: ["Penegra 25", "Manforce 100", "Viagra 25 (global)"] },
  "Finasteride": { brands: ["Finpecia 1"] },
  "Sertraline": { brands: ["Serta 25", "Daxid 100", "Zosert 25"] },
  "Escitalopram": { brands: ["Nexito LS"] },
  "Fluoxetine": { brands: ["Prodep 10", "Fludac 10"] },
  "Duloxetine": { brands: ["Duzela 60", "Dulane 20"] },
  "Mirtazapine": { brands: ["Mirtaz 30", "Mirtazap 15"] },
  "Amitriptyline": { brands: ["Tryptomer 75"] },
  "Alprazolam": { brands: ["Restyl 0.25", "Restyl 0.5"] },
  "Clonazepam": { brands: ["Clonotril 0.25", "Clonotril 2", "Rivotril 2 (global)"] },
  "Etizolam": { brands: ["Etilaam 1", "Etizola 0.25"] },
  "Zolpidem": { brands: ["Nitrest 10"] },
  "Pregabalin": {
    strengths: ["300 mg Capsule"],
    brands: ["Pregeb 150", "Maxgalin 150", "Pregalin 150", "Pregabid 300"],
  },
  "Levetiracetam": { brands: ["Torleva 250"] },
  "Sodium valproate": { brands: ["Encorate 200"] },
  "Phenytoin": { strengths: ["100 mg Injection"] },
  "Risperidone": { brands: ["Risdone 1", "Risdone 4"] },
  "Olanzapine": { brands: ["Oleanz 15"] },
  "Quetiapine": { brands: ["Qutipin 100", "Qutipin SR 300"] },
  "Aripiprazole": { brands: ["Arip MT 15"] },
  "Sumatriptan": { brands: ["Suminat 100"] },
  "Isotretinoin": { brands: ["Isotroin 10"] },
  "Clotrimazole": { brands: ["Candid Powder"] },
  "Ketoconazole": { brands: ["KZ Lotion"] },
  "Fluconazole": { brands: ["Zocon 200"] },
  "Itraconazole": { brands: ["Itaspor 200"] },
  "Hydroxychloroquine": { brands: ["HCQS 300"] },
  "Acyclovir": { brands: ["Acivir Eye Ointment"] },
  "Loperamide": { strengths: ["2 mg Tablet"] },
  "Ceftriaxone": { strengths: ["250 mg Injection"] },
  "Insulin glargine": { brands: ["Lantus Vial", "Basalog Refill", "Glaritus Vial"] },
  "Insulin aspart": { brands: ["NovoRapid Vial", "Fiasp Penfill"] },
  "Human insulin 30/70 mix": { brands: ["Huminsulin 30/70 Cartridge"] },
  "Fentanyl": { brands: ["Duragesic Patch"] },
  "Enoxaparin": { brands: ["Clexane 60 Injection"] },
  "Oxytocin": { brands: ["Syntocinon Injection"] },
  "Prednisolone": { brands: ["Wysolone 20"] },
  "Oral rehydration salts (ORS)": { brands: ["Electral Sachet Mango"] },
  "Aspirin (low dose)": { brands: ["Ecosprin AV 75 Capsule", "Loprin DS 150"] },
  "Telmisartan + Amlodipine": { brands: ["Telsartan-AM 80"] },
  "Rosuvastatin + Ezetimibe": { brands: ["Rosuvastatin+Ezetimibe Tablet"] },
};
