/* Antibiotics — real molecules & Indian brands. */
module.exports = [
  {
    salt: "Amoxicillin", cat: "Antibiotics", kind: "Capsule · Syrup · Injection",
    strengths: ["250 mg Capsule", "500 mg Capsule", "125 mg/5 ml Syrup"],
    simple: "A penicillin-family antibiotic that punches holes in bacterial walls so germs burst. It is the workhorse for throat, ear, chest and dental infections.",
    uses: ["Throat infection", "Ear infection", "Chest infection", "Dental abscess", "Urinary infection"],
    how: "500 mg every 8 hours as prescribed — and always finish the full course even if you feel better in 2 days, or the infection returns stronger.",
    watch: ["Loose stools", "Skin rash", "Nausea"],
    alert: "Penicillin allergy is serious: any swelling of lips/face or difficulty breathing after a dose is an emergency. Rash with fever needs a doctor's review.",
    brands: ["Mox 250", "Mox 500", "Novamox 500"],
  },
  {
    salt: "Amoxicillin + Clavulanic acid", cat: "Antibiotics", kind: "Tablet · Dry Syrup",
    strengths: ["375 mg Tablet", "625 mg Tablet", "1 g Tablet"],
    simple: "Amoxicillin plus a shield-breaker (clavulanic acid) that disables the enzymes resistant bacteria use against it. Used when plain amoxicillin would fail.",
    uses: ["Resistant chest infection", "Sinusitis", "Urinary infection", "Skin infection", "Bite wounds"],
    how: "625 mg every 8 hours or 1 g every 12 hours, taken at the START of a meal to prevent stomach upset. Complete the full course.",
    watch: ["Loose stools (common)", "Nausea", "Thrush in the mouth with long courses"],
    alert: "Stop and report immediately if a deep rash, yellowing of eyes or severe watery diarrhoea appears.",
    brands: ["Augmentin 625 Duo", "Augmentin 1g Duo", "Clavam 625", "Mega CV 625"],
  },
  {
    salt: "Azithromycin", cat: "Antibiotics", kind: "Tablet · Suspension",
    strengths: ["500 mg Tablet", "250 mg Tablet", "200 mg/5 ml Suspension"],
    simple: "A 3-to-5-day antibiotic that lingers in tissues, so one dose a day is enough. It gathers inside cells where many common germs hide.",
    uses: ["Chest infection", "Sinus infection", "Typhoid", "Skin infection", "Certain stomach infections"],
    how: "500 mg once daily for 3–5 days, one hour before or two hours after food (antacids block its absorption).",
    watch: ["Stomach cramps", "Nausea", "Metallic taste"],
    alert: "Tell your doctor about any irregular heartbeat feeling — rare but reported. Overuse has made many germs resistant; never self-start it for viral fever.",
    brands: ["Azithral 500", "Azithral 200 Suspension", "Azee 500", "Azicip 500", "Zithrox 500"],
  },
  {
    salt: "Cefixime", cat: "Antibiotics", kind: "Tablet · Dry Syrup",
    strengths: ["200 mg Tablet", "100 mg/5 ml Dry Syrup"],
    simple: "A third-generation cephalosporin — a broad antibiotic often chosen for urinary infections, typhoid and stubborn throat infections.",
    uses: ["Urinary infection", "Typhoid fever", "Throat infection", "Ear infection"],
    how: "200 mg twice a day (or 400 mg once) as prescribed, with the course always completed.",
    watch: ["Loose stools", "Nausea", "Stomach pain"],
    alert: "Rash, fever with blistering, or blood in stool during the course needs immediate medical review.",
    brands: ["Taxim-O 200", "Zifi 200", "Zifi 100 Dry Syrup"],
  },
  {
    salt: "Cefuroxime", cat: "Antibiotics", kind: "Tablet · Suspension",
    strengths: ["250 mg Tablet", "500 mg Tablet"],
    simple: "A strong cephalosporin antibiotic good for respiratory infections, sinusitis and skin infections, taken twice daily.",
    uses: ["Chest infection", "Sinusitis", "Tonsillitis", "Skin infection", "Lyme disease"],
    how: "250–500 mg every 12 hours with food, for the full prescribed course (usually 5–10 days).",
    watch: ["Diarrhoea", "Nausea", "Headache"],
    alert: "Penicillin/cephalosporin allergy can cross-react — any facial swelling or wheeze is an emergency.",
    brands: ["Ceftum 250", "Ceftum 500"],
  },
  {
    salt: "Cefpodoxime", cat: "Antibiotics", kind: "Tablet · Dry Syrup",
    strengths: ["200 mg Tablet"],
    simple: "An oral cephalosporin for respiratory, urinary and skin infections — often picked when a twice-a-day broad antibiotic is needed.",
    uses: ["Pneumonia (mild)", "Bronchitis", "Urinary infection", "Skin infection"],
    how: "200 mg every 12 hours with food to boost absorption.",
    watch: ["Loose stools", "Stomach discomfort"],
    alert: "Severe diarrhoea during or after the course can signal C. difficile infection — see a doctor rather than self-treating.",
    brands: ["Cepodem 200", "Monocef-O 200"],
  },
  {
    salt: "Cephalexin", cat: "Antibiotics", kind: "Capsule · Syrup",
    strengths: ["250 mg Capsule", "500 mg Capsule"],
    simple: "A first-generation cephalosporin that is especially good against skin and soft-tissue germs like streptococcus and staphylococcus.",
    uses: ["Skin boils and cellulitis", "Throat infection", "Ear infection", "Bone infection (long course)"],
    how: "500 mg every 6–12 hours as prescribed; complete the whole course.",
    watch: ["Nausea", "Loose stools"],
    alert: "Allergic swelling or rash needs urgent care; tell your doctor of any penicillin allergy first.",
    brands: ["Sporidex 250", "Sporidex 500"],
  },
  {
    salt: "Ceftriaxone", cat: "Antibiotics", kind: "Injection",
    strengths: ["1 g Injection", "500 mg Injection"],
    simple: "A powerful injectable antibiotic given only in hospitals and clinics — the backbone of treatment for serious infections like pneumonia, typhoid and sepsis.",
    uses: ["Serious chest infection", "Typhoid", "Urinary sepsis", "Meningitis", "Surgical prophylaxis"],
    how: "Given into a vein or muscle by medical staff, once or twice daily. Courses run several days depending on the infection.",
    watch: ["Pain at injection site", "Rash", "Loose stools"],
    alert: "Tell staff about prior antibiotic allergies. Rash with breathlessness during the drip is an emergency.",
    brands: ["Monocef 1g Injection", "Monocef 500mg Injection"],
  },
  {
    salt: "Ciprofloxacin", cat: "Antibiotics", kind: "Tablet · Eye/Ear Drops",
    strengths: ["500 mg Tablet", "250 mg Tablet", "0.3% Eye/Ear Drops"],
    simple: "A fluoroquinolone antibiotic that interferes with bacterial DNA copying. Widely used for urinary and stomach infections; the drops treat eye and ear infections.",
    uses: ["Urinary infection", "Traveller's diarrhoea", "Eye/ear infection (drops)", "Bone infection"],
    how: "500 mg twice daily; doses are spaced from dairy, antacids and iron (they lock to it). Finish the full course.",
    watch: ["Nausea", "Headache", "Tendon aches (rare but important)"],
    alert: "Stop and call a doctor at once if a tendon (especially Achilles) starts aching or popping — fluoroquinolones can injure tendons. Not first-line in children.",
    brands: ["Cifran 500", "Cifran 250", "Ciplox Eye/Ear Drops"],
  },
  {
    salt: "Levofloxacin", cat: "Antibiotics", kind: "Tablet · Injection",
    strengths: ["250 mg Tablet", "500 mg Tablet"],
    simple: "A once-daily fluoroquinolone for chest, sinus and urinary infections — the left-handed mirror of ciprofloxacin with better lung coverage.",
    uses: ["Pneumonia", "Sinusitis", "Urinary infection", "Bronchitis"],
    how: "500 mg once daily, plenty of water, away from antacids and iron tablets by 2 hours.",
    watch: ["Nausea", "Headache", "Insomnia", "Tendon aches (rare)"],
    alert: "Same tendon and heart-rhythm cautions as ciprofloxacin. Blood sugar can swing in diabetics — monitor.",
    brands: ["Levoflox 250", "Levoflox 500", "Loxof 500"],
  },
  {
    salt: "Norfloxacin", cat: "Antibiotics", kind: "Tablet",
    strengths: ["400 mg Tablet"],
    simple: "A fluoroquinolone that concentrates in the urine — the classic tablet for urinary tract infections and traveller's diarrhoea.",
    uses: ["Urinary infection", "Bacterial diarrhoea", "Prostate infection"],
    how: "400 mg twice daily, an hour before or two hours after meals, with lots of water; avoid milk/antacids around the dose.",
    watch: ["Nausea", "Headache"],
    alert: "Tendon pain or swelling means stop the drug and call your doctor. Avoid in children and pregnancy.",
    brands: ["Norflox 400"],
  },
  {
    salt: "Doxycycline", cat: "Antibiotics", kind: "Capsule · Tablet",
    strengths: ["100 mg Capsule"],
    simple: "A tetracycline antibiotic that stops bacteria making proteins. It doubles as an anti-malarial prophylaxis and treats several tick-borne and skin conditions.",
    uses: ["Acne (long course)", "Chest infection", "Scrub typhus", "Malaria prophylaxis", "Sexually transmitted infections"],
    how: "100 mg once or twice daily with a full glass of water, sitting upright; never take just before lying down or with milk (it binds calcium and iron).",
    watch: ["Acidity/oesophagus burning", "Sun sensitivity — skin burns easily"],
    alert: "Severe heartburn or pain on swallowing means stop and consult. Use strong sunscreen on treatment.",
    brands: ["Doxt 100", "Doxy-1 L-DR Forte"],
  },
  {
    salt: "Minocycline", cat: "Antibiotics", kind: "Tablet · Capsule",
    strengths: ["50 mg Tablet", "100 mg Tablet"],
    simple: "A tetracycline cousin used mainly for stubborn acne and some resistant infections; it reaches oily skin and glands well.",
    uses: ["Moderate-to-severe acne", "Resistant skin infection", "Rheumatoid arthritis (adjunct)"],
    how: "50–100 mg once or twice daily as prescribed, with water and not with milk; courses for acne run weeks to months under supervision.",
    watch: ["Nausea", "Dizziness", "Blue-grey skin tint with very long use"],
    alert: "Headache with blurred vision (raised pressure) or a drug rash needs urgent review.",
    brands: ["Minoz 50", "Minoz 100"],
  },
  {
    salt: "Metronidazole", cat: "Antibiotics", kind: "Tablet · Syrup · Gel · Injection",
    strengths: ["400 mg Tablet", "200 mg Tablet", "0.75% Gel"],
    simple: "An antibiotic that kills anaerobic germs (those that live without oxygen) and certain parasites. Famous rule: absolutely no alcohol during it and for 2 days after.",
    uses: ["Amoebiasis", "Giardiasis", "Dental and gut anaerobic infection", "Vaginal infection", "Wound infection"],
    how: "400 mg two or three times daily after food as prescribed; the gel treats rosacea/vaginal infections locally.",
    watch: ["Metallic taste", "Nausea", "Dark urine (harmless)"],
    alert: "Alcohol causes violent flushing and vomiting with this drug. Numbness or tingling in limbs on long courses must be reported.",
    brands: ["Metrogyl 400", "Metrogyl 200 Syrup"],
  },
  {
    salt: "Tinidazole", cat: "Antibiotics", kind: "Tablet",
    strengths: ["300 mg Tablet", "500 mg Tablet"],
    simple: "A longer-acting metronidazole relative for anaerobic germs and parasites — often a shorter, simpler course.",
    uses: ["Amoebiasis", "Giardiasis", "Vaginal trichomonas infection", "Dental infection"],
    how: "As prescribed, commonly 1–2 g once daily after food for 2–3 days, or 500 mg twice daily. Same strict no-alcohol rule.",
    watch: ["Metallic taste", "Nausea"],
    alert: "Alcohol interaction is as severe as metronidazole. Report numbness or seizures.",
    brands: ["Tiniba 300", "Tiniba 500"],
  },
  {
    salt: "Clindamycin", cat: "Antibiotics", kind: "Capsule · Gel",
    strengths: ["150 mg Capsule", "300 mg Capsule", "1% Gel"],
    simple: "An antibiotic for anaerobic and staph germs, used orally for dental and bone infections and as a gel for acne.",
    uses: ["Dental abscess", "Bone/joint infection", "Serious skin infection", "Acne (gel)"],
    how: "150–300 mg every 6–8 hours with a full glass of water; apply a thin acne gel layer at night.",
    watch: ["Diarrhoea (tell your doctor if severe)", "Skin dryness with gel"],
    alert: "Watery, frequent diarrhoea during or weeks after the course can mean C. difficile colitis — needs prompt treatment, not just an antidiarrhoeal.",
    brands: ["Dalacin C 300", "Clindam 300"],
  },
  {
    salt: "Linezolid", cat: "Antibiotics", kind: "Tablet · Injection",
    strengths: ["600 mg Tablet"],
    simple: "A last-line-class oral antibiotic for resistant gram-positive germs — especially MRSA — used when ordinary antibiotics have failed.",
    uses: ["MRSA skin infection", "Hospital pneumonia", "Resistant wound infection"],
    how: "600 mg every 12 hours as prescribed; courses are monitored with blood counts if longer than 10–14 days.",
    watch: ["Nausea", "Headache", "Diarrhoea"],
    alert: "It interacts dangerously with antidepressants and aged cheese (serotonin surge): agitation, sweating, racing heart — call your doctor. Vision changes on long courses need eye checks.",
    brands: ["Linospan 600"],
  },
  {
    salt: "Cotrimoxazole", cat: "Antibiotics", kind: "Tablet · Suspension",
    strengths: ["DS Tablet (800/160 mg)", "200/40 mg/5 ml Suspension"],
    simple: "Two antibiotics in one (sulfamethoxazole + trimethoprim) that block bacteria's folic-acid factory in different spots — a strong double-lock.",
    uses: ["Urinary infection", "Chest infection", "PCP pneumonia in HIV care", "Skin infection"],
    how: "One DS tablet twice daily as prescribed, with plenty of fluids.",
    watch: ["Nausea", "Rash", "Sun sensitivity"],
    alert: "Sulfa allergy can be severe — blistering rash or mouth ulcers mean stop immediately. It interacts with warfarin (bleeding risk) and methotrexate.",
    brands: ["Septran DS", "Septran Syrup"],
  },
  {
    salt: "Nitrofurantoin", cat: "Antibiotics", kind: "Capsule",
    strengths: ["100 mg Capsule"],
    simple: "A urinary-specialist antibiotic that concentrates only in urine — effective for simple bladder infections while barely touching the rest of the body.",
    uses: ["Simple urinary infection", "Recurrent cystitis prevention"],
    how: "100 mg twice daily for 5–7 days with food. Not used for kidney infections (it doesn't reach deep tissue).",
    watch: ["Nausea", "Urine may turn brown (harmless)"],
    alert: "Avoid in significant kidney impairment. Breathlessness or cough during long courses must be reported — rare lung effects.",
    brands: ["Niftran 100"],
  },
  {
    salt: "Rifampicin", cat: "Antibiotics", kind: "Capsule",
    strengths: ["150 mg Capsule", "300 mg Capsule", "450 mg Capsule"],
    simple: "A cornerstone anti-TB antibiotic that shuts down bacterial RNA production. It turns urine, sweat and tears orange-red — harmless and expected.",
    uses: ["Tuberculosis (in combination)", "Leprosy", "Certain staph infections"],
    how: "Always in combination with other TB drugs, taken on an empty stomach in the morning, daily for months as directed.",
    watch: ["Orange body fluids (harmless)", "Nausea", "Liver enzyme rise (monitored)"],
    alert: "It weakens many medicines — birth-control pills, warfarin, diabetic drugs. Yellow eyes, severe fatigue or vomiting need a liver check urgently.",
    brands: ["R-Cin 150", "R-Cin 300", "R-Cin 450"],
  },
  {
    salt: "Isoniazid", cat: "Antibiotics", kind: "Tablet",
    strengths: ["300 mg Tablet"],
    simple: "The other pillar of TB treatment, blocking mycolic acid that builds the TB bacterium's wall. Taken daily for months with vitamin B6 cover.",
    uses: ["Tuberculosis treatment", "TB preventive therapy"],
    how: "300 mg once daily on an empty stomach, usually with pyridoxine (B6) to protect nerves; never taken alone for active TB.",
    watch: ["Numbness/tingling of feet (prevented by B6)", "Appetite change"],
    alert: "Yellowing of eyes, dark urine or persistent vomiting means possible liver injury — stop and see your doctor immediately.",
    brands: ["Isokin 300"],
  },
  {
    salt: "Ethambutol", cat: "Antibiotics", kind: "Tablet",
    strengths: ["400 mg Tablet", "800 mg Tablet"],
    simple: "An anti-TB drug that stops the bacterium building its cell wall. Its famous side effect is on eyesight, so vision is checked before and during treatment.",
    uses: ["Tuberculosis (combination therapy)"],
    how: "Weight-based dose (15–25 mg/kg) once daily with the rest of the TB regimen.",
    watch: ["Difficulty telling red from green", "Blurred vision"],
    alert: "Any change in vision or colours — report the same day; stopping early usually protects sight.",
    brands: ["Combutol 400", "Combutol 800"],
  },
  {
    salt: "Pyrazinamide", cat: "Antibiotics", kind: "Tablet",
    strengths: ["500 mg Tablet", "750 mg Tablet"],
    simple: "The TB drug that clears bacteria hiding in acidic pockets inside the body, letting treatment courses be shortened to six months.",
    uses: ["Tuberculosis (intensive phase)"],
    how: "Weight-based dose once daily with the TB regimen; liver tests are monitored during therapy.",
    watch: ["Joint aches", "Raised uric acid", "Nausea"],
    alert: "Yellow eyes, dark urine, severe fatigue or vomiting = possible liver injury, needs immediate review.",
    brands: ["Pyzina 500", "Pyzina 750"],
  },
  {
    salt: "Faropenem", cat: "Antibiotics", kind: "Tablet · Suspension",
    strengths: ["200 mg Tablet"],
    simple: "An oral penem antibiotic used in India for resistant respiratory and ENT infections when first-line drugs haven't worked.",
    uses: ["Resistant sinusitis", "Bronchitis", "ENT infection"],
    how: "200 mg two or three times daily as prescribed, course completed fully.",
    watch: ["Nausea", "Loose stools"],
    alert: "Rash or allergic swelling needs immediate stop-and-review. Not for trivial colds — resistance matters.",
    brands: ["Farobact 200"],
  },
  {
    salt: "Amikacin", cat: "Antibiotics", kind: "Injection",
    strengths: ["500 mg Injection"],
    simple: "An aminoglycoside 'big gun' injectable for serious hospital infections and resistant TB, given under close monitoring because of kidney and hearing effects.",
    uses: ["Severe hospital infection", "Resistant TB (combination)", "Sepsis"],
    how: "Given by injection once daily, dose adjusted to kidney function and drug levels.",
    watch: ["Reduced urine output", "Ringing in ears or hearing dip", "Balance trouble"],
    alert: "Any hearing change or reduced urination during the course must be reported immediately — effects can be permanent if ignored.",
    brands: ["Mikacin 500 Injection"],
  },
  {
    salt: "Piperacillin + Tazobactam", cat: "Antibiotics", kind: "Injection",
    strengths: ["4.5 g Injection"],
    simple: "A hospital intravenous combination — a broad penicillin with a beta-lactamase shield — used for serious abdominal, lung and blood infections.",
    uses: ["Hospital pneumonia", "Abdominal sepsis", "Blood infection", "Diabetic foot infection"],
    how: "Given by drip every 6–8 hours by hospital staff, dose adjusted for kidney function.",
    watch: ["Rash", "Diarrhoea", "Blood count changes (monitored)"],
    alert: "Allergic reactions need immediate staff attention; prolonged courses watch for fungal superinfection.",
    brands: ["Piptaz 4.5g Injection"],
  },
];
