/* Brain, nerves & mind — real molecules & Indian brands. */
module.exports = [
  {
    salt: "Sertraline", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["25 mg Tablet", "50 mg Tablet", "100 mg Tablet"],
    simple: "A first-line antidepressant — it raises serotonin signalling gradually, lifting low mood, panic and obsessive loops over 2–4 weeks. One of the safest, most-prescribed mind medicines.",
    uses: ["Depression", "Panic disorder", "OCD", "Social anxiety", "PTSD"],
    how: "Morning dose after food, starting low and stepped up by the doctor. It builds over weeks — stopping it early is the commonest failure. Taper slowly when discontinuing.",
    watch: ["Nausea in week one", "Jitteriness", "Sleep changes", "Sexual side effects (discuss openly)"],
    alert: "Any new suicidal thoughts, especially in young adults early in treatment, need immediate contact with the doctor. Never mix with linezolid or tramadol (serotonin surge risk).",
    brands: ["Serta 50", "Daxid 50", "Zosert 50", "Serlift 50"],
  },
  {
    salt: "Escitalopram", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["5 mg Tablet", "10 mg Tablet"],
    simple: "A clean, well-tolerated SSRI antidepressant for depression and anxiety — often chosen for fewer drug interactions and gentler side-effect profile.",
    uses: ["Depression", "Generalised anxiety", "Panic disorder"],
    how: "5–10 mg morning or night; benefit over 2–4 weeks; taper on discontinuation.",
    watch: ["Nausea early", "Sleep change", "Sexual side effects"],
    alert: "QT heart-interval caution at higher doses in heart patients. Same urgent-contact rule for worsening mood.",
    brands: ["Nexito 5", "Nexito 10", "Cipralex 10"],
  },
  {
    salt: "Fluoxetine", cat: "Brain & Mind", kind: "Capsule · Tablet",
    strengths: ["10 mg Tablet", "20 mg Capsule"],
    simple: "The original SSRI with a long half-life (missed doses forgive you) — used for depression, OCD, bulimia and PMDD.",
    uses: ["Depression", "OCD", "Bulimia", "PMDD"],
    how: "Morning dose (it energises some people); 20 mg typical adult dose, adjusted by the doctor.",
    watch: ["Nausea", "Nervousness early", "Sleep change"],
    alert: "Long half-life means washout periods matter when switching drugs — specialist territory. Worsening mood needs immediate contact.",
    brands: ["Prodep 20", "Fludac 20", "Prozac (global)"],
  },
  {
    salt: "Duloxetine", cat: "Brain & Mind", kind: "Capsule (DR)",
    strengths: ["20 mg Capsule", "30 mg Capsule", "60 mg Capsule"],
    simple: "A serotonin-noradrenaline reuptake inhibitor — lifts mood AND dampens nerve pain, making it the dual-use tablet for depression with diabetic nerve or chronic pain.",
    uses: ["Depression", "Generalised anxiety", "Diabetic nerve pain", "Fibromyalgia", "Chronic musculoskeletal pain"],
    how: "Once daily, swallow whole (DR capsule); can be taken with or without food.",
    watch: ["Nausea at start", "Dry mouth", "Constipation", "Sweating"],
    alert: "Liver disease is a contraindication. Abrupt stop causes zappy discontinuation effects — taper always.",
    brands: ["Duzela 20", "Duzela 30", "Dulane 30", "Cymbalta (global)"],
  },
  {
    salt: "Mirtazapine", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["7.5 mg Tablet", "15 mg Tablet", "30 mg Tablet"],
    simple: "An antidepressant that works on a different axis — noradrenaline and serotonin via blocking — famous for restoring appetite and deep sleep, often chosen when weight loss and insomnia accompany depression.",
    uses: ["Depression with insomnia and poor appetite", "Elderly depression", "Anxiety with sleep issues"],
    how: "Bedtime dose; sedation is strongest at LOW doses (7.5–15 mg) and eases as dose rises — counterintuitive but true.",
    watch: ["Sleepiness", "Increased appetite and weight"],
    alert: "Report unusual bruising (rare blood-count effect). Combination with other sedatives stacks drowsiness.",
    brands: ["Mirtaz 15", "Remeron Melt (global)", "Mirtazap 7.5"],
  },
  {
    salt: "Amitriptyline", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["10 mg Tablet", "25 mg Tablet"],
    simple: "The old tricyclic — at tiny doses it's a nerve-pain and migraine-prevention workhorse; at higher doses, a classic antidepressant. Sleepy, so it lives at bedtime.",
    uses: ["Nerve pain", "Migraine prevention", "Depression", "Fibromyalgia", "Insomnia with pain"],
    how: "10–25 mg at night, titrated slowly; the analgesic effect works at far smaller doses than the antidepressant one.",
    watch: ["Morning drowsiness", "Dry mouth", "Constipation", "Weight gain"],
    alert: "Overdose is dangerous with tricyclics — keep quantity limited and away from impulsive access. Heart-rhythm patients need ECG review.",
    brands: ["Tryptomer 10", "Tryptomer 25"],
  },
  {
    salt: "Alprazolam", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["0.25 mg Tablet", "0.5 mg Tablet", "1 mg Tablet"],
    simple: "A fast-acting benzodiazepine for acute panic and severe anxiety spikes — quietens the brain's alarm within the hour. A short-term rescue, not a long-term plan.",
    uses: ["Panic attacks", "Acute severe anxiety", "Short-term situational anxiety"],
    how: "0.25–0.5 mg as prescribed, at most short courses — dependence builds within weeks of daily use, so doctors keep it time-boxed.",
    watch: ["Sleepiness", "Slowed reflexes", "Memory gaps at higher doses"],
    alert: "Never combine with alcohol or opioids — breathing can stop. Abrupt stop after daily use causes seizures; tapering is mandatory.",
    brands: ["Alprax 0.25", "Alprax 0.5", "Alprax 1.0", "Tranax 0.5"],
  },
  {
    salt: "Clonazepam", cat: "Brain & Mind", kind: "Tablet · Tablet (DT)",
    strengths: ["0.25 mg Tablet", "0.5 mg Tablet", "1 mg Tablet"],
    simple: "A longer-acting benzodiazepine that steadies both seizure activity and severe panic — also used in restless legs and certain twitching disorders.",
    uses: ["Seizure disorders", "Panic disorder", "Restless legs syndrome", "Myoclonus"],
    how: "Dose at bedtime usually, titrated slowly; long-term use needs deliberate taper plans.",
    watch: ["Drowsiness", "Coordination slowing", "Drooling at higher doses"],
    alert: "Same dependence and tapering law as alprazolam. Sudden stop can trigger seizures.",
    brands: ["Rivotril 0.5 (global)", "Clonotril 0.5", "Klonopin (global)"],
  },
  {
    salt: "Etizolam", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["0.25 mg Tablet", "0.5 mg Tablet", "1 mg Tablet"],
    simple: "A thienodiazepine popular in Indian practice for anxiety and insomnia — quicker clear-headedness for many users, with the same dependence rules as benzodiazepines.",
    uses: ["Anxiety", "Insomnia", "Panic"],
    how: "0.25–1 mg at night or as prescribed; short courses only.",
    watch: ["Sleepiness", "Impaired coordination"],
    alert: "Dependence and withdrawal risks are real — never self-extend daily use. No alcohol.",
    brands: ["Etilaam 0.25", "Etilaam 0.5", "Etizola 0.5"],
  },
  {
    salt: "Zolpidem", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["5 mg Tablet", "10 mg Tablet"],
    simple: "A sleep-onset tablet — quiets brain activity just enough to fall asleep, without the morning hangover of older sleeping pills. Strictly a bedside-then-bed medicine.",
    uses: ["Short-term insomnia", "Sleep-onset difficulty"],
    how: "5–10 mg at bedtime with nothing else planned — take it IN bed, because some people do complex things (sleepwalking, texting) with no memory of it.",
    watch: ["Metallic taste", "Next-day grogginess (some)", "Complex sleep behaviours (rare)"],
    alert: "Complex sleep behaviours (walking, eating, driving asleep) mean stop and report. Combining with alcohol is dangerous.",
    brands: ["Zolfresh 5", "Zolfresh 10", "Nitrest 5"],
  },
  {
    salt: "Gabapentin", cat: "Brain & Mind", kind: "Capsule · Tablet",
    strengths: ["100 mg Capsule", "300 mg Capsule", "400 mg Tablet"],
    simple: "A nerve-calming agent — dampens over-firing nerves for shooting nerve pain, and steadies seizure thresholds as an add-on. Sedating, so nights are its friend.",
    uses: ["Nerve pain (post-shingles, sciatica)", "Seizure add-on", "Restless legs"],
    how: "Started low at night and stepped up over days-weeks; kidney function sets the dose ceiling.",
    watch: ["Sleepiness", "Dizziness", "Ankle swelling"],
    alert: "Taper when stopping. Breathing depression risk when combined with opioids, especially in the elderly.",
    brands: ["Gabantin 100", "Gabantin 300", "Gabapin 300"],
  },
  {
    salt: "Pregabalin", cat: "Brain & Mind", kind: "Capsule · Tablet (SR)",
    strengths: ["75 mg Capsule", "150 mg Capsule", "75 mg SR Tablet"],
    simple: "Gabapentin's stronger cousin — binds the nerve-calcium-channel to quiet burning, electric-type nerve pain from diabetes, shingles and spine problems.",
    uses: ["Diabetic neuropathy", "Post-shingles pain", "Sciatica", "Fibromyalgia", "Seizure add-on"],
    how: "Twice daily (or once nightly SR) started low; kidney dosing applies.",
    watch: ["Dizziness", "Sleepiness", "Weight gain", "Ankle swelling"],
    alert: "Same opioid-breathing caution. Taper on stopping; abrupt stop can trigger insomnia and anxiety rebound.",
    brands: ["Pregeb 75", "Pregalin 75", "Nervup PG (combo)", "Maxgalin 75"],
  },
  {
    salt: "Pregabalin + Nortriptyline", cat: "Brain & Mind", kind: "Tablet",
    simple: "A powerful nerve-pain pairing — pregabalin quiets the nerve firing while nortriptyline raises the spinal pain gate's threshold; the combination often succeeds where singles fail.",
    uses: ["Resistant diabetic neuropathy", "Chronic sciatic pain", "Post-herpetic neuralgia"],
    how: "Bedtime dosing usually, titrated by the doctor over weeks.",
    watch: ["Morning drowsiness", "Dry mouth", "Constipation"],
    alert: "Heart-rhythm caution with nortriptyline in cardiac patients. Report urinary hesitancy or severe constipation.",
    brands: ["Nervigesic Tablet", "Pregeb NT", "Nortregalin NT"],
  },
  {
    salt: "Levetiracetam", cat: "Brain & Mind", kind: "Tablet · Syrup · Injection",
    strengths: ["250 mg Tablet", "500 mg Tablet", "1 g Tablet"],
    simple: "A modern anti-epileptic with a unique mechanism (binding SV2A) and minimal drug interactions — the frequent first choice for focal seizures, including in pregnant plans.",
    uses: ["Focal seizures", "Generalised seizures (adjunct)", "Post-stroke seizure prevention"],
    how: "Twice daily dosing, stepped up gradually; never stopped abruptly — seizure rebound is real.",
    watch: ["Irritability or mood change (tell doctor)", "Sleepiness", "Dizziness"],
    alert: "Significant personality changes or aggression need dose review. Missing doses invites seizures — adherence is everything.",
    brands: ["Levera 250", "Levera 500", "Torleva 500", "Keppra (global)"],
  },
  {
    salt: "Sodium valproate", cat: "Brain & Mind", kind: "Tablet · Syrup",
    strengths: ["200 mg Tablet", "300 mg Tablet", "200 mg/5 ml Syrup"],
    simple: "A broad-spectrum anti-epileptic that raises the brain's inhibitory signal (GABA) — covers almost every seizure type, and also stabilises bipolar mood.",
    uses: ["Generalised seizures", "Absence seizures", "Bipolar disorder", "Migraine prevention"],
    how: "Twice daily with food (or once nightly ER form); periodic liver tests and blood levels during long therapy.",
    watch: ["Tremor", "Weight gain", "Hair thinning (usually reversible)", "Nausea"],
    alert: "ABSOLUTE for girls/women of childbearing age: severe birth-defect risk — pregnancy plans must involve the specialist first. Vomiting, jaundice or extreme fatigue needs urgent liver tests.",
    brands: ["Valparin 200", "Valparin Chrono 300", "Encorate Chrono 300"],
  },
  {
    salt: "Phenytoin", cat: "Brain & Mind", kind: "Tablet · Capsule · Injection",
    strengths: ["50 mg Tablet", "100 mg Tablet"],
    simple: "The classic anti-seizure drug — stabilises nerve membranes against repetitive firing. Still used widely, but with a narrow blood-level window requiring monitoring.",
    uses: ["Focal and generalised tonic-clonic seizures", "Status epilepticus (injection)"],
    how: "Once or twice daily at fixed times; blood levels guide dosing; gum care matters (gum overgrowth is classic).",
    watch: ["Gum swelling (dental hygiene!)", "Coarse facial changes long-term", "Dizziness", "Balance trouble at toxic levels"],
    alert: "Nystagmus (jumping eyes), slurred speech or stumbling means toxicity — level check urgently. Never stop suddenly.",
    brands: ["Eptoin 50", "Eptoin 100"],
  },
  {
    salt: "Carbamazepine", cat: "Brain & Mind", kind: "Tablet · Tablet (CR)",
    strengths: ["200 mg Tablet", "200 mg CR Tablet"],
    simple: "A membrane-stabilising anti-epileptic that is ALSO the standard drug for trigeminal neuralgia (the 'electric shock' face pain). Interacts with many medicines — disclosure matters.",
    uses: ["Focal seizures", "Trigeminal neuralgia", "Bipolar disorder (selected)"],
    how: "Twice daily (CR once or twice), titrated up slowly; blood counts and sodium are monitored.",
    watch: ["Drowsiness", "Blurred vision", "Low sodium with long use", "Rash"],
    alert: "Blistering rash (Stevens-Johnson risk, especially with a certain gene in Asians) = stop immediately and see a doctor. It weakens the contraceptive pill.",
    brands: ["Tegrital 200", "Mazetol 200", "Carbatol 200"],
  },
  {
    salt: "Oxcarbazepine", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["150 mg Tablet", "300 mg Tablet", "600 mg Tablet"],
    simple: "Carbamazepine's refined sibling — same seizure control with fewer blood-count and rash worries, though sodium still needs watching.",
    uses: ["Focal seizures", "Trigeminal neuralgia (alternative)"],
    how: "Twice daily dosing, titrated to response; periodic sodium checks.",
    watch: ["Drowsiness", "Double vision at high doses", "Low sodium"],
    alert: "Report rash promptly. Hyponatraemia symptoms (confusion, weakness) need electrolyte tests.",
    brands: ["Oxcarb 300", "Oxetol 300", "Trileptal (global)"],
  },
  {
    salt: "Risperidone", cat: "Brain & Mind", kind: "Tablet · Syrup",
    strengths: ["1 mg Tablet", "2 mg Tablet", "3 mg Tablet", "4 mg Tablet"],
    simple: "An atypical antipsychotic that blocks dopamine and serotonin receptors — steadies hallucinations, delusions and severe agitation in psychosis and bipolar mania.",
    uses: ["Schizophrenia", "Bipolar mania", "Severe behavioural symptoms", "Irritability in autism (as advised)"],
    how: "Once or twice daily, started low and titrated; morning sedation can be managed by moving the dose to night.",
    watch: ["Sleepiness", "Weight gain", "Raised prolactin (breast changes, cycle changes)", "Restlessness (akathisia)"],
    alert: "Never stop abruptly. Stiffness, fever and confusion together (rare NMS) is an emergency. Elderly dementia patients have raised mortality warnings — specialist-only.",
    brands: ["Risdone 2", "Sizodon 2", "Sizodon 1", "Risperdal (global)"],
  },
  {
    salt: "Olanzapine", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["2.5 mg Tablet", "5 mg Tablet", "10 mg Tablet"],
    simple: "A broad atypical antipsychotic with strong calming power — workhorse for schizophrenia, bipolar mania and severe agitation, at the cost of weight and metabolic watchfulness.",
    uses: ["Schizophrenia", "Bipolar mania", "Acute agitation (as advised)", "Bipolar maintenance"],
    how: "Bedtime dose typically; metabolic profile (weight, sugar, lipids) is monitored regularly.",
    watch: ["Weight gain (significant)", "Sleepiness", "Raised sugar and lipids"],
    alert: "Metabolic monitoring is not optional — diabetes risk is real. Same never-stop-abruptly rule.",
    brands: ["Oleanz 2.5", "Oleanz 5", "Zyprexa (global)", "Oleanz 10"],
  },
  {
    salt: "Quetiapine", cat: "Brain & Mind", kind: "Tablet · Tablet (SR)",
    strengths: ["25 mg Tablet", "100 mg Tablet", "200 mg SR Tablet"],
    simple: "A gentle-sedating atypical antipsychotic used across psychosis, bipolar maintenance and as a sleep-steadier in mood disorders — dose spans hugely by purpose.",
    uses: ["Schizophrenia", "Bipolar disorder", "Depression adjunct", "Sleep disturbance in mood illness"],
    how: "Small bedtime start, titrated upward; SR forms once nightly.",
    watch: ["Sleepiness", "Orthostatic dizziness", "Weight and metabolic drift"],
    alert: "Same metabolic monitoring and tapering discipline. Sudden dizziness on standing needs dose review.",
    brands: ["Qutipin 25", "Qutipin SR 200", "Seroquel (global)"],
  },
  {
    salt: "Aripiprazole", cat: "Brain & Mind", kind: "Tablet (MT)",
    strengths: ["5 mg Tablet (MT)", "10 mg Tablet (MT)"],
    simple: "A unique 'partial agonist' antipsychotic — it tunes dopamine rather than blocking it fully, giving psychosis control with less weight gain and prolactin trouble.",
    uses: ["Schizophrenia", "Bipolar disorder", "Depression add-on", "Tic disorders (as advised)"],
    how: "Once daily, mouth-melting (MT) or regular tablet, dose per indication.",
    watch: ["Restlessness/akathisia (main quirk)", "Insomnia", "Nausea"],
    alert: "Akathisia (inner restlessness, can't sit still) is treatable — report rather than endure. Metabolic effects are milder but present.",
    brands: ["Arip MT 5", "Arip MT 10", "Abilify (global)"],
  },
  {
    salt: "Donepezil", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["5 mg Tablet", "10 mg Tablet"],
    simple: "A memory-preserving drug for Alzheimer's — it keeps acetylcholine (the memory messenger) from being broken down, modestly steadying cognition and daily function.",
    uses: ["Mild-to-moderate Alzheimer's dementia", "Dementia-related decline"],
    how: "5 mg at bedtime for 4–6 weeks, then possibly 10 mg; GI upset is dose-related.",
    watch: ["Nausea", "Vivid dreams", "Muscle cramps", "Slow pulse"],
    alert: "Fainting or slow heart rate needs ECG review. Caregivers should track response — it stabilises, rarely reverses.",
    brands: ["Donep 5", "Donep 10", "Aricept (global)"],
  },
  {
    salt: "Memantine", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["5 mg Tablet", "10 mg Tablet"],
    simple: "An NMDA-receptor shield for moderate-to-severe dementia — protects brain cells from glutamate over-stimulation, often layered with donepezil.",
    uses: ["Moderate-to-severe Alzheimer's", "Dementia behaviour support"],
    how: "Weekly step-up from 5 mg to 20 mg daily (or 10 mg twice); kidney dosing applies.",
    watch: ["Dizziness", "Headache", "Constipation"],
    alert: "Report worsening confusion or hallucinations — treatment plans get revisited as disease stages change.",
    brands: ["Admenta 5", "Admenta 10", "Memacne 10"],
  },
  {
    salt: "Sumatriptan", cat: "Brain & Mind", kind: "Tablet · Injection · Nasal Spray",
    strengths: ["25 mg Tablet", "50 mg Tablet", "6 mg Injection"],
    simple: "A migraine-specific rescue — constricts the dilated brain vessels and blocks the trigeminal pain cascade, often ending an attack within an hour of the first dose.",
    uses: ["Acute migraine attack", "Cluster headache (injection)"],
    how: "One tablet at attack START (not daily prevention); may repeat once after 2 hours, max 200 mg/day. Injection is hospital/self-taught for severe attacks.",
    watch: ["Tightness in chest/neck (transient)", "Tingling", "Warmth"],
    alert: "NOT with heart disease or uncontrolled BP. Never combine with other triptans or SSRIs without advice (serotonin risk). Frequent use causes medication-overuse headache.",
    brands: ["Suminat 25", "Suminat 50", "Suminat Injection"],
  },
  {
    salt: "Rizatriptan", cat: "Brain & Mind", kind: "Tablet · Tablet (ML)",
    strengths: ["5 mg Tablet", "10 mg Tablet", "5 mg ML Tablet"],
    simple: "A faster-acting triptan with a mouth-melting form — handy when migraine nausea makes swallowing tablets unpleasant.",
    uses: ["Acute migraine", "Migraine with nausea (ML form)"],
    how: "5–10 mg at attack onset; one repeat after 2 hours maximum; ML melts on the tongue.",
    watch: ["Dizziness", "Sleepiness", "Chest tightness (transient)"],
    alert: "Same cardiac contraindications as sumatriptan; propranolol users take lower doses (interaction).",
    brands: ["Rizact 5", "Rizact 10", "Rizact ML 5"],
  },
];
