/* Brain, nerves & mind — second wave: movement, seizures, cognition, addiction care. */
module.exports = [
  {
    salt: "Lamotrigine", cat: "Brain & Mind", kind: "Tablet · Tablet (DT)",
    strengths: ["25 mg Tablet", "50 mg Tablet", "100 mg Tablet"],
    simple: "An anti-epileptic that calms over-active sodium channels and glutamate release — also a respected bipolar mood-stabiliser, especially for the depressive pole.",
    uses: ["Focal and generalised seizures", "Bipolar depression", "Lennox-Gastaut syndrome (specialist)"],
    how: "Titrated very slowly over weeks — rush the dose and rash risk rises; any rash means stop-and-call.",
    watch: ["Headache", "Dizziness", "Blurred vision"],
    alert: "Blistering or mucosal rash (Stevens-Johnson) is an emergency — stop immediately.",
    brands: ["Lamitor 25", "Lamitor 100", "Lamogine 50"],
  },
  {
    salt: "Topiramate", cat: "Brain & Mind", kind: "Tablet · Capsule",
    strengths: ["25 mg Tablet", "50 mg Tablet", "100 mg Tablet"],
    simple: "A broad anti-seizure drug with several mechanisms at once — also a first-line migraine preventer; famous for word-finding difficulty and appetite change.",
    uses: ["Focal/generalised seizures", "Migraine prevention", "Weight effect in some regimens"],
    how: "Titrate slowly; drink plenty of water (kidney stones); cognitive slowing means the dose gets re-discussed.",
    watch: ["Tingling of hands/feet", "Word-finding trouble", "Weight loss", "Kidney stones"],
    alert: "Eye pain with blurred vision shortly after starting is rare glaucoma — same-day review. Metabolic acidosis is monitored.",
    brands: ["Topamac 25", "Topamac 50", "Topamax (global)"],
  },
  {
    salt: "Lacosamide", cat: "Brain & Mind", kind: "Tablet · Injection",
    strengths: ["50 mg Tablet", "100 mg Tablet", "200 mg Tablet"],
    simple: "A modern anti-epileptic that enhances slow sodium-channel inactivation — clean side-effect profile, useful for focal seizures when older drugs fail.",
    uses: ["Focal seizures", "Focal seizures with spread"],
    how: "Twice daily, titrated over a week or two; hospital injections exist for acute settings.",
    watch: ["Dizziness", "Nausea", "Double vision"],
    alert: "PR-interval (ECG) caution in heart patients. Never stop abruptly.",
    brands: ["Lacoset 50", "Lacoset 100", "Torlako 200"],
  },
  {
    salt: "Zonisamide", cat: "Brain & Mind", kind: "Capsule",
    strengths: ["100 mg Capsule"],
    simple: "A sulfonamide-family anti-epileptic for focal seizures, sometimes added in refractory cases and used off-label in weight-sensitive regimens.",
    uses: ["Focal seizures (add-on)"],
    how: "Once or twice daily, titrated slowly, with plenty of fluids.",
    watch: ["Appetite loss", "Drowsiness", "Kidney stone risk"],
    alert: "Sulfa-allergic patients must avoid it. Rash or mood change needs review.",
    brands: ["Zonimax 100", "Zonisamide 100mg Capsule"],
  },
  {
    salt: "Baclofen", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["10 mg Tablet", "25 mg Tablet"],
    simple: "A GABA-B muscle relaxant for spinal-cord and neurological stiffness — loosens rigid, spastic limbs stroke and MS patients struggle with.",
    uses: ["Spasticity", "Trigeminal neuralgia (adjunct)", "Alcohol craving (specialist use)", "Hiccups (persistent)"],
    how: "Titrated up over weeks; NEVER stop suddenly (rebound seizures/hallucinations).",
    watch: ["Drowsiness", "Muscle weakness", "Fatigue"],
    alert: "Abrupt withdrawal can mimic a stroke or cause seizures — always taper.",
    brands: ["Baclofen 10 Tablet", "Liofen 10"],
  },
  {
    salt: "Levodopa + Carbidopa", cat: "Brain & Mind", kind: "Tablet · Tablet (CR)",
    strengths: ["100/10 mg Tablet", "100/25 mg Tablet", "50/200 mg CR Tablet"],
    simple: "The gold-standard Parkinson's pair — levodopa becomes dopamine in the brain while carbidopa stops it breaking down on the way, restoring smooth movement.",
    uses: ["Parkinson's disease", "Parkinsonism symptoms"],
    how: "Taken with or just after food (protein delays absorption), several times daily on a fixed rhythm; dose timing is everything.",
    watch: ["Nausea", "Dizziness on standing", "Dyskinesia (involuntary movements) over years", "Darks urine (harmless)"],
    alert: "Never stop abruptly — parkinsonism can rebound severely (withdrawal-emergent syndrome). Sudden sleep attacks are discussed with the neurologist.",
    brands: ["Syndopa 110", "Syndopa Plus", "Sinemet Plus (global)"],
  },
  {
    salt: "Pramipexole", cat: "Brain & Mind", kind: "Tablet · Tablet (SR)",
    strengths: ["0.25 mg Tablet", "0.5 mg Tablet", "0.25 mg SR Tablet"],
    simple: "A dopamine-agonist for Parkinson's and restless legs — mimics dopamine directly on receptors, smoothing tremor and stopping the night-time leg urge.",
    uses: ["Parkinson's disease (early/adjunct)", "Restless legs syndrome"],
    how: "Bedtime titration for RLS; split doses for Parkinson's; taper never-stop rule.",
    watch: ["Nausea", "Sleepiness with sudden sleep onset", "Impulse-control changes (gambling/shopping urges)"],
    alert: "New compulsive behaviours must be told to the doctor — they reverse on dose change.",
    brands: ["Pramipex 0.25", "Pramipex ER 0.25", "Kampra 0.5"],
  },
  {
    salt: "Ropinirole", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["0.25 mg Tablet", "0.5 mg Tablet", "1 mg Tablet"],
    simple: "Another dopamine-agonist in the Parkinson's/restless-legs family — similar benefits, similar sleep-attack and impulse cautions.",
    uses: ["Parkinson's disease", "Restless legs syndrome"],
    how: "Titrated slowly, usually three times daily for Parkinson's; evening dose for RLS.",
    watch: ["Nausea", "Dizziness", "Sudden sleepiness"],
    alert: "Impulse-control changes and sudden sleep onset are the known emergencies-in-waiting — report early.",
    brands: ["Ropark 0.25", "Ropark 0.5", "Ropark XL"],
  },
  {
    salt: "Trihexyphenidyl", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["2 mg Tablet"],
    simple: "An anti-cholinergic that rebalances dopamine/acetylcholine in Parkinsonism and drug-induced stiffness — old but effective for tremor-predominant cases.",
    uses: ["Parkinsonism tremor", "Drug-induced parkinsonism (antipsychotic side effect)", "Dystonia"],
    how: "2 mg two or three times daily, titrated; strongly drying and sedating.",
    watch: ["Dry mouth", "Blurred vision", "Constipation", "Memory fog in elderly"],
    alert: "Glaucoma and prostate enlargement contraindicate it. Confusion in elderly patients means reduce/stop.",
    brands: ["Pacitane 2", "Trihexane 2"],
  },
  {
    salt: "Amantadine", cat: "Brain & Mind", kind: "Capsule · Tablet",
    strengths: ["100 mg Capsule"],
    simple: "A quirky old drug with three hats — Parkinson's tremor relief, influenza-A treatment, and drug-induced parkinsonism rescue.",
    uses: ["Parkinson's dyskinesia", "Influenza A", "Drug-induced parkinsonism"],
    how: "100 mg once or twice daily; dose reduced in kidney impairment.",
    watch: ["Mottled skin (livedo reticularis)", "Ankle swelling", "Insomnia"],
    alert: "Sudden stop can worsen parkinsonism or cause confusion. Halos/glare or confusion needs review.",
    brands: ["Amantrel 100", "Parkitidin 100"],
  },
  {
    salt: "Rasagiline", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["0.5 mg Tablet", "1 mg Tablet"],
    simple: "An MAO-B inhibitor that preserves the brain's own dopamine — a once-daily early-Parkinson's therapy that smooths 'wearing-off' phases.",
    uses: ["Parkinson's disease", "Wearing-off fluctuations"],
    how: "0.5–1 mg once daily in the morning; avoid pethidine, tramadol and some antidepressants (serotonin risk) — disclose everything.",
    watch: ["Headache", "Insomnia", "Flu-like aches"],
    alert: "Serotonin syndrome with tramadol/SSRIs (agitation, fever, tremor) is an emergency.",
    brands: ["Relgin 0.5", "Relgin 1", "Azilect (global)"],
  },
  {
    salt: "Betahistine", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["8 mg Tablet", "16 mg Tablet", "24 mg Tablet"],
    simple: "A vertigo-regulator — improves inner-ear blood flow and reduces endolymph pressure, easing the spinning attacks of Meniere's disease.",
    uses: ["Vertigo", "Meniere's disease", "Inner-ear imbalance"],
    how: "8–24 mg two or three times daily with food; benefit builds over weeks.",
    watch: ["Mild stomach upset", "Headache"],
    alert: "Persistent vertigo with hearing loss or new neuro signs needs ENT/neurology evaluation, not endless betahistine.",
    brands: ["Vertin 8", "Vertin 16", "Vertin OD 24"],
  },
  {
    salt: "Flunarizine", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["5 mg Tablet", "10 mg Tablet"],
    simple: "A calcium-channel blocker with vestibular talents — a popular migraine preventer and vertigo suppressor in Indian practice.",
    uses: ["Migraine prevention", "Vertigo prophylaxis", "Vestibular disorders"],
    how: "5–10 mg at night; benefit appears over weeks of continuous use.",
    watch: ["Drowsiness", "Weight gain", "Depression (report mood dips)"],
    alert: "Parkinsonism-like stiffness with long use (rare, reversible) — any new slowness or tremor means review.",
    brands: ["Sibelium 5", "Flunarin 5", "Fruniz 10"],
  },
  {
    salt: "Cinnarizine", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["25 mg Tablet"],
    simple: "An anti-vertigo and travel-sickness tablet — calms the inner-ear balance signals and quiets nausea from motion.",
    uses: ["Motion sickness", "Vertigo", "Inner-ear disorders"],
    how: "25 mg before travel or twice daily for vertigo courses.",
    watch: ["Drowsiness", "Weight gain with long use"],
    alert: "Parkinson's patients should avoid it. Long-term daily use is discouraged.",
    brands: ["Stugeron 25", "Cinzine 25"],
  },
  {
    salt: "Nimodipine", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["30 mg Tablet"],
    simple: "A brain-vessel-selective calcium blocker — after a brain bleed from an aneurysm, it prevents vessel spasm and protects blood flow to healing tissue.",
    uses: ["Aneurysmal subarachnoid haemorrhage spasm prevention"],
    how: "30 mg every 4 hours (or 60 mg every 4) for 21 days, exactly per protocol, BP monitored.",
    watch: ["Low BP", "Flushing", "Headache"],
    alert: "Hospital-supervised course — missed timing matters in spasm prevention.",
    brands: ["Nimotop 30", "Nibel 30"],
  },
  {
    salt: "Citicoline", cat: "Brain & Mind", kind: "Tablet · Injection",
    strengths: ["500 mg Tablet"],
    simple: "A brain-membrane building-block drug — supports repair after stroke and head injury, and sharpens attention in cognitive recovery programs.",
    uses: ["Stroke recovery", "Head injury recovery", "Vascular cognitive decline"],
    how: "500 mg once or twice daily, or hospital injections in acute phases; courses run weeks.",
    watch: ["Headache (rare)", "Insomnia if dosed late"],
    alert: "It supports recovery but doesn't replace stroke prevention (BP, statins, antiplatelets).",
    brands: ["Strocit 500", "Citistar 500"],
  },
  {
    salt: "Piracetam", cat: "Brain & Mind", kind: "Tablet · Syrup",
    strengths: ["400 mg Tablet", "800 mg Tablet"],
    simple: "An old 'nootropic' that improves brain-cell membrane fluidity — used in myoclonus, dyslexia protocols and post-stroke cognition support.",
    uses: ["Cortical myoclonus", "Post-stroke cognitive support", "Vertigo (adjunct)"],
    how: "800 mg two or three times daily; kidney dosing applies.",
    watch: ["Nervousness", "Weight gain", "Insomnia"],
    alert: "Never stop abruptly after long use (withdrawal seizures reported). Kidney disease needs dose cuts.",
    brands: ["Nootropil 800", "Pirament 800"],
  },
  {
    salt: "Modafinil", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["100 mg Tablet", "200 mg Tablet"],
    simple: "A wakefulness-promoter for genuine sleep disorders — narcolepsy, shift-work disorder, sleep apnoea residual sleepiness. Not a study drug, despite reputation.",
    uses: ["Narcolepsy", "Shift-work sleep disorder", "Obstructive apnoea residual sleepiness"],
    how: "200 mg in the morning (or an hour before shift); avoid late dosing.",
    watch: ["Headache", "Insomnia", "Anxiety", "Rash (rare, serious)"],
    alert: "Any rash means stop immediately. It reduces efficacy of hormonal contraceptives — discuss backup methods.",
    brands: ["Modalert 200", "Modvigil 200"],
  },
  {
    salt: "Methylphenidate", cat: "Brain & Mind", kind: "Tablet · Tablet (SR)",
    strengths: ["10 mg Tablet", "20 mg SR Tablet"],
    simple: "A stimulant that raises dopamine/noradrenaline signalling in the prefrontal cortex — the core ADHD medicine, improving focus and impulse control.",
    uses: ["ADHD (children and adults)", "Narcolepsy (second-line)"],
    how: "Morning dose(s) per specialist titration; growth, BP and sleep are monitored in children.",
    watch: ["Appetite suppression", "Insomnia", "Rebound irritability", "Slowed growth (monitored)"],
    alert: "Controlled substance — never share. Cardiac screening precedes use; sudden cardiac symptoms need urgent care.",
    brands: ["Concerta 18 (OROS)", "Addwize 10"],
  },
  {
    salt: "Atomoxetine", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["10 mg Tablet", "18 mg Tablet", "25 mg Tablet"],
    simple: "A non-stimulant ADHD medicine — raises noradrenaline gradually over weeks, chosen when stimulants don't suit or anxiety coexists.",
    uses: ["ADHD", "ADHD with anxiety/tics"],
    how: "Once or twice daily, titrated by weight; full effect takes 4–8 weeks.",
    watch: ["Appetite loss", "Nausea", "Mood swings early"],
    alert: "Any liver symptoms (yellowing, dark urine) or severe mood change means stop-and-review immediately.",
    brands: ["Atten 10", "Tomoxetin 18"],
  },
  {
    salt: "Buspirone", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["5 mg Tablet", "10 mg Tablet"],
    simple: "A non-sedating anxiety regulator working on serotonin (5HT1A) — no dependence, no drunkenness, but it builds over 2 weeks rather than calming instantly.",
    uses: ["Generalised anxiety", "Chronic anxiety without panic"],
    how: "5–10 mg two or three times daily; patience required for onset.",
    watch: ["Dizziness", "Nausea", "Nervousness early"],
    alert: "No interaction joy with alcohol like benzodiazepines, but still avoid stacking sedatives. It does NOT treat acute panic.",
    brands: ["Buspin 5", "Buspin 10"],
  },
  {
    salt: "Lithium", cat: "Brain & Mind", kind: "Tablet · Tablet (SR)",
    strengths: ["300 mg Tablet", "400 mg SR Tablet"],
    simple: "The classic mood-stabiliser for bipolar disorder — irreplaceable for preventing mania and suicide risk, but with a narrow blood window requiring 3-monthly levels.",
    uses: ["Bipolar disorder", "Mania", "Suicide-risk reduction", "Augmentation in depression"],
    how: "Same time daily with water; salt intake and hydration must stay steady; levels are checked 12 hours after a dose.",
    watch: ["Fine tremor", "Increased thirst and urination", "Weight gain", "Thyroid slowing (monitored)"],
    alert: "Vomiting, unsteady walking, slurred speech or confusion = toxicity — stop and test blood urgently. Dehydration, NSAIDs and diuretics raise levels dangerously.",
    brands: ["Lithosun 300", "Lithosun SR 400"],
  },
  {
    salt: "Bupropion", cat: "Brain & Mind", kind: "Tablet (SR/XL)",
    strengths: ["150 mg SR Tablet"],
    simple: "A dopamine-noradrenaline reuptake inhibitor — the antidepressant that helps quit smoking, with no weight gain or sexual side effects (often the reason it's chosen).",
    uses: ["Depression", "Smoking cessation", "Seasonal depression"],
    how: "150 mg morning dose (XL form once daily), stepped up after a week; seizure threshold is its watchpoint.",
    watch: ["Insomnia", "Dry mouth", "Tremor"],
    alert: "Seizure history contraindicates it. Report seizures immediately (rare).",
    brands: ["Bupron SR 150", "Bupron XL 150"],
  },
  {
    salt: "Clozapine", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["25 mg Tablet", "100 mg Tablet"],
    simple: "The last-resort antipsychotic for treatment-resistant schizophrenia — uniquely effective, uniquely watched: white-cell counts are mandatory because of a rare crash risk.",
    uses: ["Treatment-resistant schizophrenia", "Suicidal schizophrenia"],
    how: "Started tiny and titrated slowly with weekly (then monthly) blood counts; sedation and drooling are managed actively.",
    watch: ["Severe constipation (dangerous)", "Drooling", "Sedation", "Weight gain", "Myocarditis signs (chest pain, fever early)"],
    alert: "Fever, sore throat or flu-like illness while on it = same-day blood count. Missed doses beyond 48 hours require re-titration rules.",
    brands: ["Clozaril (global)", "Sizopin 25", "Sizopin 100"],
  },
  {
    salt: "Haloperidol", cat: "Brain & Mind", kind: "Tablet · Injection",
    strengths: ["5 mg Tablet", "5 mg Injection"],
    simple: "A classic potent antipsychotic — fast control of severe agitation, psychosis and delirium in hospitals; the decanoate injection gives month-long cover.",
    uses: ["Acute psychosis", "Delirium agitation", "Schizophrenia", "Tourette tics"],
    how: "Tablets once/twice daily; injections by staff with ECG and rigidity monitoring.",
    watch: ["Stiffness and tremor (managed with trihexyphenidyl)", "Restlessness (akathisia)", "ECG QT change"],
    alert: "High fever with rigidity and confusion (NMS) is a medical emergency. Elderly dementia use has mortality warnings.",
    brands: ["Haldol 5 (global)", "Peridol 5"],
  },
  {
    salt: "Trifluoperazine", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["5 mg Tablet"],
    simple: "An older phenothiazine antipsychotic for schizophrenia and severe anxiety-with-agitation — effective, with the classic movement side-effect profile.",
    uses: ["Schizophrenia", "Severe anxiety states (short-term)"],
    how: "2–10 mg daily in divided doses as prescribed.",
    watch: ["Stiffness", "Tremor", "Restlessness", "Sun sensitivity"],
    alert: "Same NMS and movement-disorder vigilance. Long-term use risks tardive dyskinesia — periodic reviews are essential.",
    brands: ["Trinicalm Plus", "Trifluron 5"],
  },
  {
    salt: "Flupentixol + Melitracen", cat: "Brain & Mind", kind: "Tablet",
    simple: "A popular Indian 'DEANXIT-style' pair — a small antipsychotic dose plus a tricyclic, aimed at mixed anxiety-depression with somatic complaints.",
    uses: ["Mixed anxiety-depression", "Psychosomatic complaints", "Somatoform disorders"],
    how: "Usually two tablets daily (morning + noon), never late-evening (activating).",
    watch: ["Dry mouth", "Restlessness", "Insomnia if dosed late"],
    alert: "Mania can be unmasked in bipolar patients — mood history matters. Tricyclic cardiac cautions apply.",
    brands: ["Franxit Tablet"],
  },
  {
    salt: "Naltrexone", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["50 mg Tablet"],
    simple: "An opioid-blocker used in addiction care — removes the reward from alcohol and blocks opioid highs, supporting relapse-prevention programs.",
    uses: ["Alcohol dependence (relapse prevention)", "Opioid blockade after detox"],
    how: "50 mg daily after full opioid detox (never while opioids still in system — precipitates withdrawal).",
    watch: ["Nausea", "Headache", "Liver tests on long courses"],
    alert: "Any opioid painkiller becomes ineffective — tell every doctor. Acute hepatitis contraindicates use.",
    brands: ["Naltima 50", "Naxon 50"],
  },
  {
    salt: "Disulfiram", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["250 mg Tablet"],
    simple: "The alcohol-aversion tablet — drinking while on it causes instant flushing, pounding heart and vomiting, rewiring the drinking decision. Counselling pairs with it.",
    uses: ["Chronic alcohol dependence (aversion therapy)"],
    how: "250 mg daily after 12+ alcohol-free hours; the reaction starts within minutes of any alcohol — even mouthwash and cough syrups count.",
    watch: ["Metallic taste", "Drowsiness", "Skin odour change"],
    alert: "The alcohol reaction can be severe (BP drop, collapse) — patients must know every hidden alcohol source. Liver tests are monitored.",
    brands: ["Disulfiram 250 Tablet", "Disulfiron 250"],
  },
  {
    salt: "Nortriptyline", cat: "Brain & Mind", kind: "Tablet",
    strengths: ["10 mg Tablet", "25 mg Tablet"],
    simple: "A noradrenaline-leaning tricyclic — bedtime workhorse for nerve pain, migraine prevention and depression, often paired with pregabalin in resistant neuropathy.",
    uses: ["Nerve pain", "Migraine prevention", "Depression", "Smoking cessation (off-label)"],
    how: "10–25 mg at bedtime, titrated slowly; cardiac history is reviewed first.",
    watch: ["Morning drowsiness", "Dry mouth", "Constipation", "Urinary hesitancy"],
    alert: "ECG review in cardiac patients. Overdose is dangerous — keep supplies limited.",
    brands: ["Nortrip 10", "Nortrip 25"],
  },
];
