/* Heart & BP — second wave: combos, anti-anginals, peripheral vessels. */
module.exports = [
  {
    salt: "S-Amlodipine", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["2.5 mg Tablet", "5 mg Tablet"],
    simple: "The left-handed mirror of amlodipine — half the milligram does the same BP job with noticeably less ankle swelling for many patients.",
    uses: ["Hypertension", "Angina"],
    how: "One tablet daily, fixed time.",
    watch: ["Milder ankle swelling than plain amlodipine", "Flushing", "Headache"],
    alert: "Same nitrate/ED-drug interaction caution as amlodipine. Dizziness with fainting needs review.",
    brands: ["S-Amvas 2.5", "S-Amlong 5"],
  },
  {
    salt: "Valsartan", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["40 mg Tablet", "80 mg Tablet", "160 mg Tablet"],
    simple: "A widely used ARB — blocks the vessel-tightening hormone, with strong heart-failure and post-heart-attack evidence.",
    uses: ["Hypertension", "Heart failure", "Post-MI left-ventricle protection"],
    how: "One tablet daily; potassium and creatinine checked periodically.",
    watch: ["Dizziness", "Raised potassium (monitored)"],
    alert: "Pregnancy contraindicated. Avoid stacking NSAIDs.",
    brands: ["Valzaar 40", "Valzaar 80", "Diovan (global)"],
  },
  {
    salt: "Valsartan + Amlodipine", cat: "Heart & Blood Pressure", kind: "Tablet",
    simple: "ARB plus calcium-blocker pair — the Exforge-style combination for BP needing two mechanisms in one tablet.",
    uses: ["Hypertension not controlled on monotherapy"],
    how: "One tablet daily.",
    watch: ["Ankle swelling (amlodipine side)", "Dizziness"],
    alert: "Pregnancy contraindicated.",
    brands: ["Exforge 5/160 (global)", "Valzaar AM"],
  },
  {
    salt: "Valsartan + Hydrochlorothiazide", cat: "Heart & Blood Pressure", kind: "Tablet",
    simple: "ARB plus thiazide diuretic — hormone-blocked vessels plus shed salt and water.",
    uses: ["Hypertension", "BP with volume load"],
    how: "Morning tablet; electrolytes checked periodically.",
    watch: ["Cramps", "Dizziness"],
    alert: "Pregnancy contraindicated; gout needs monitoring.",
    brands: ["Valzaar H", "Cresar H"],
  },
  {
    salt: "Nebivolol + Valsartan", cat: "Heart & Blood Pressure", kind: "Tablet",
    simple: "Beta-blocker plus ARB — slows the heart and relaxes vessels together for resistant hypertension.",
    uses: ["Resistant hypertension"],
    how: "One tablet daily at fixed time.",
    watch: ["Slow pulse", "Dizziness"],
    alert: "Never stop abruptly; asthma needs specialist caution.",
    brands: ["Byvalson (global)"],
  },
  {
    salt: "Sacubitril + Valsartan", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["50 mg Tablet", "100 mg Tablet"],
    simple: "The modern heart-failure pillar — enhances protective natriuretic peptides while blocking angiotensin; proven to cut deaths and hospitalisations versus older ACE therapy.",
    uses: ["Chronic heart failure (reduced ejection fraction)"],
    how: "Twice daily, titrated up after a 36-hour washout from ACE inhibitors (mandatory — angioedema risk).",
    watch: ["Low BP", "Raised potassium", "Kidney function drift"],
    alert: "Never combine with an ACE inhibitor — 36-hour gap is law. Swelling of lips/tongue is an emergency.",
    brands: ["Vymada 50", "Vymada 100", "Entresto (global)"],
  },
  {
    salt: "Ezetimibe", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["10 mg Tablet"],
    simple: "A cholesterol-absorption blocker at the gut wall — pairs with statins for extra LDL drop without much side-effect increase.",
    uses: ["High LDL", "Statin-intolerant patients", "Statin combination therapy"],
    how: "One tablet daily, any time; often inside statin combo tablets.",
    watch: ["Headache", "Mild gut upset"],
    alert: "Liver tests occasionally monitored in combination therapy.",
    brands: ["Ezedoc 10", "Zetica 10"],
  },
  {
    salt: "Atorvastatin + Ezetimibe", cat: "Heart & Blood Pressure", kind: "Tablet",
    simple: "Stops cholesterol being made AND absorbed — the two-door blockade for aggressive LDL targets.",
    uses: ["High LDL needing >50% reduction", "Post-ACS targets", "Familial hypercholesterolaemia"],
    how: "One tablet at night after food.",
    watch: ["Muscle aches", "Liver enzymes (monitored)"],
    alert: "Dark urine with muscle pain and fever = stop and test (rhabdo).",
    brands: ["Atorlip-EZ", "Cholib (global)"],
  },
  {
    salt: "Rosuvastatin + Ezetimibe", cat: "Heart & Blood Pressure", kind: "Tablet",
    simple: "The strongest-statin plus absorption-blocker pair for very high-risk LDL control.",
    uses: ["Severe hypercholesterolaemia", "Post-stent aggressive targets"],
    how: "One tablet evening/night.",
    watch: ["Muscle aches", "Headache"],
    alert: "Same muscle-toxicity rules as statins.",
    brands: ["Rosutor EZ"],
  },
  {
    salt: "Nicorandil", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["5 mg Tablet", "10 mg Tablet"],
    simple: "A dual-action anti-anginal — opens potassium channels AND works like a nitrate, dilating both large and small coronary vessels.",
    uses: ["Chronic stable angina", "Vasospastic angina"],
    how: "5–10 mg twice daily with meals.",
    watch: ["Headache (early, common)", "Flushing", "Mouth/skin ulcers with long use (rare, serious)"],
    alert: "Non-healing mouth or anal ulcers on long therapy need specialist review — drug is paused.",
    brands: ["Nikoran 5"],
  },
  {
    salt: "Ranolazine", cat: "Heart & Blood Pressure", kind: "Tablet (ER)",
    strengths: ["500 mg ER Tablet"],
    simple: "A late-sodium-channel blocker that helps the heart muscle relax efficiently between beats — an add-on when angina persists despite standard drugs.",
    uses: ["Chronic angina (add-on)", "Diabetic neuropathic pain (exploratory)"],
    how: "500 mg twice daily; ECG (QT) is monitored.",
    watch: ["Dizziness", "Nausea", "Constipation"],
    alert: "Liver disease and QT-prolonging drug combos need specialist reconciliation.",
    brands: ["Ranexa 500 (global)", "Cardilong 500"],
  },
  {
    salt: "Sotalol", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["40 mg Tablet", "80 mg Tablet"],
    simple: "A beta-blocker with rhythm-stabilising powers — used to keep atrial fibrillation and dangerous ventricular rhythms in sinus.",
    uses: ["Atrial fibrillation maintenance", "Ventricular arrhythmia"],
    how: "Twice daily with kidney-adjusted dosing; QT is monitored closely.",
    watch: ["Slow pulse", "Dizziness", "Breathlessness (asthma risk)"],
    alert: "QT prolongation can trigger dangerous rhythm (torsades) — hospital-titrated initiation is standard.",
    brands: ["Sotagard 40", "Sotalol 40mg Tablet"],
  },
  {
    salt: "Dronedarone", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["400 mg Tablet"],
    simple: "Amiodarone's refined cousin — keeps sinus rhythm in atrial fibrillation without the thyroid and lung toxicity, for stable hearts only.",
    uses: ["Paroxysmal atrial fibrillation maintenance"],
    how: "400 mg twice daily with meals.",
    watch: ["Stomach upset", "Raised creatinine (harmless pattern)"],
    alert: "Contraindicated in heart failure (increased mortality) and permanent AF. Liver injury signs reported promptly.",
    brands: ["Dronedarone 400 Tablet", "Multaq (global)"],
  },
  {
    salt: "Isosorbide dinitrate", cat: "Heart & Blood Pressure", kind: "Tablet · Sublingual",
    strengths: ["5 mg Tablet", "10 mg Tablet"],
    simple: "The shorter-acting nitrate — both swallowed and under-the-tongue forms relax coronary vessels for angina relief and prevention.",
    uses: ["Angina", "Heart failure support"],
    how: "Swallowed 2–3 times daily or dissolved under the tongue at attack onset; nitrate-free overnight window keeps tolerance away.",
    watch: ["Throbbing headache", "Flushing", "Dizziness"],
    alert: "Absolute ban with sildenafil-type ED drugs.",
    brands: ["Sorbitrate 5", "Sorbitrate 10"],
  },
  {
    salt: "Dipyridamole", cat: "Heart & Blood Pressure", kind: "Tablet (ER)",
    strengths: ["75 mg Tablet", "200 mg ER Tablet"],
    simple: "An anti-platelet that raises the 'don't clump' signal (cAMP) inside platelets — classically paired with aspirin after mini-strokes.",
    uses: ["Post-TIA/stroke prevention (with aspirin)", "Mechanical valve support (with warfarin)"],
    how: "200 mg ER twice daily with the aspirin schedule.",
    watch: ["Headache (common early)", "Flushing", "Stomach upset"],
    alert: "Myasthenia gravis worsens with it. Bleeding signs get urgent review like all antiplatelets.",
    brands: ["Persantin 75", "Antiplar DUO"],
  },
  {
    salt: "Cilostazol", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["50 mg Tablet", "100 mg Tablet"],
    simple: "A PDE3 inhibitor that widens vessels and calms platelets — prescribed for walking pain from poor leg circulation (intermittent claudication).",
    uses: ["Intermittent claudication", "Peripheral artery disease"],
    how: "100 mg twice daily, 30 minutes before breakfast and dinner; effect builds over weeks.",
    watch: ["Headache", "Palpitations", "Diarrhoea"],
    alert: "Heart-failure patients must NOT take it. It interacts heavily with CYP3A4 drugs (ketoconazole, erythromycin).",
    brands: ["Pletaal 50", "Cilostazol 100 Tablet"],
  },
  {
    salt: "Pentoxifylline", cat: "Heart & Blood Pressure", kind: "Tablet (ER)",
    strengths: ["400 mg Tablet"],
    simple: "A blood-rheology improver — makes red cells more flexible so oxygen reaches poorly-perfused tissues (legs, ulcers, ear ringing).",
    uses: ["Peripheral vascular disease", "Leg ulcers", "Tinnitus (adjunct)"],
    how: "400 mg two or three times daily with food.",
    watch: ["Nausea", "Dizziness", "Headache"],
    alert: "Recent retinal/brain haemorrhage contraindicates it. Kidney dosing applies.",
    brands: ["Trental 400 (global)", "Floxen 400"],
  },
];
