/* Famous fixed-dose combinations (FDCs) — real Indian brands with their salt pairs. */
module.exports = [
  {
    salt: "Ibuprofen + Paracetamol", cat: "Pain & Fever", kind: "Tablet",
    simple: "India's favourite pain combo — ibuprofen's anti-inflammatory punch plus paracetamol's fever-and-pain cover, each at a lower dose than alone.",
    uses: ["Body pain with fever", "Period pain", "Dental pain", "Sprains"],
    how: "One tablet after food up to three times daily, short courses only (NSAID rules apply).",
    watch: ["Acidity", "Nausea"],
    alert: "Never add another paracetamol product on top (double-dosing). Stomach-ulcer patients should avoid.",
    brands: ["Combiflam Tablet", "Flexon Tablet", "Ibugesic Plus"],
  },
  {
    salt: "Aceclofenac + Paracetamol", cat: "Pain & Fever", kind: "Tablet",
    simple: "A gentler-stomach NSAID paired with paracetamol — the standard orthopaedic prescription for arthritis and back pain flares.",
    uses: ["Arthritis pain", "Back pain", "Post-injury pain", "Joint stiffness"],
    how: "One tablet twice daily strictly after food.",
    watch: ["Acidity", "Stomach discomfort"],
    alert: "Same NSAID cautions: kidney, ulcer, heart-failure avoidance. Report black stools.",
    brands: ["Zerodol-P", "Hifenac-P", "Aceloflam Plus"],
  },
  {
    salt: "Aceclofenac + Paracetamol + Chlorzoxazone", cat: "Pain & Fever", kind: "Tablet",
    simple: "A three-way pain formula — anti-inflammatory, pain cover and a muscle relaxant for cramping back and neck strains.",
    uses: ["Muscle spasm with pain", "Low back strain", "Stiff neck", "Painful sprains"],
    how: "One tablet twice daily after food for a few days.",
    watch: ["Drowsiness", "Acidity"],
    alert: "No driving while drowsy. Short courses only.",
    brands: ["Zerodol MR", "Hifenac-MR"],
  },
  {
    salt: "Tramadol + Paracetamol", cat: "Pain & Fever", kind: "Tablet",
    simple: "A two-gear painkiller — tramadol works on brain pain pathways while paracetamol covers the periphery, bridging moderate-to-severe pain.",
    uses: ["Post-operative pain", "Severe musculoskeletal pain", "Neuropathic pain adjunct"],
    how: "One–two tablets every 6 hours as prescribed, max daily cap respected.",
    watch: ["Drowsiness", "Nausea", "Dizziness"],
    alert: "Same opioid cautions: no alcohol, no sedative stacking, short courses, dependence awareness.",
    brands: ["Ultracet Tablet"],
  },
  {
    salt: "Aspirin + Caffeine", cat: "Pain & Fever", kind: "Tablet",
    simple: "An old headache formula — aspirin's anti-inflammatory action plus caffeine's vessel-tightening boost (and faster absorption).",
    uses: ["Tension headache", "Mild migraine"],
    how: "One–two tablets every 6 hours as needed, with water and food.",
    watch: ["Acidity", "Jitteriness from caffeine"],
    alert: "Not for children (Reye's risk). Avoid in ulcers and bleeding disorders.",
    brands: ["Anacin Tablet"],
  },
  {
    salt: "Pantoprazole + Domperidone", cat: "Acidity & Digestion", kind: "Capsule (SR)",
    simple: "The reflux duo — pantoprazole shuts the acid pumps while domperidone pushes the stomach to empty forward, stopping acid from rising in the first place.",
    uses: ["GERD with bloating", "Reflux with slow stomach emptying", "Acidity with nausea"],
    how: "One capsule 30 minutes BEFORE breakfast, swallowed whole.",
    watch: ["Headache", "Dry mouth"],
    alert: "Domperidone's heart-rhythm caution applies. Persistent reflux beyond weeks needs endoscopy discussion.",
    brands: ["Pan-D Capsule", "Pantocid DSR", "Pantop-D"],
  },
  {
    salt: "Rabeprazole + Domperidone", cat: "Acidity & Digestion", kind: "Capsule (SR)",
    simple: "Same acid-pump-plus-push pairing as Pan-D, with rabeprazole's slightly faster onset — the 'DSR' capsule of reflux care.",
    uses: ["GERD", "Bloating with reflux", "Dyspepsia with nausea"],
    how: "One capsule before breakfast, empty stomach.",
    watch: ["Headache", "Drowsiness (mild)"],
    alert: "Same domperidone rhythm caution; not for long unsupervised use.",
    brands: ["Razo-D", "Nexpro RD", "Rabekind-DSR"],
  },
  {
    salt: "Dicyclomine + Simethicone", cat: "Acidity & Digestion", kind: "Tablet · Drops",
    simple: "Anti-spasm plus anti-gas — dicyclomine relaxes gut cramping while simethicone pops trapped gas bubbles; the colic-pair for kids and adults alike.",
    uses: ["Infant colic (drops)", "Gas with cramping", "IBS-type spasm"],
    how: "Drops dose by infant weight as labelled; tablets 10 mg up to 4 times daily for adults.",
    watch: ["Drowsiness", "Dry mouth"],
    alert: "Crying that persists despite colic drops needs medical review — colic is a diagnosis of exclusion.",
    brands: ["Cyclopam Drops", "Colimex Drops"],
  },
  {
    salt: "Amlodipine + Atenolol", cat: "Heart & Blood Pressure", kind: "Tablet",
    simple: "Vessel-relaxer plus heart-slowener in one tablet — amlodipine opens arteries while atenolol calms the pulse, covering two BP mechanisms together.",
    uses: ["Hypertension", "Hypertension with palpitations", "Angina"],
    how: "One tablet daily at a fixed time.",
    watch: ["Slow pulse", "Ankle swelling", "Tiredness"],
    alert: "Never stop abruptly (beta-blocker rebound). Asthma patients need specialist review before beta-blockers.",
    brands: ["Amlopres-AT", "Amlopress-AT"],
  },
  {
    salt: "Telmisartan + Amlodipine", cat: "Heart & Blood Pressure", kind: "Tablet",
    simple: "ARB plus calcium-channel blocker — the most common two-drug BP combination: angiotensin blocked and vessels relaxed, one tablet each morning.",
    uses: ["Hypertension not controlled on one drug", "BP with kidney protection needs"],
    how: "One tablet daily; kidney and potassium tests are periodic.",
    watch: ["Ankle swelling", "Dizziness on starting"],
    alert: "Pregnancy contraindicated. Avoid regular NSAID painkiller stacking (kidney strain).",
    brands: ["Telma AM", "Telma AM 40", "Telma AM 80"],
  },
  {
    salt: "Telmisartan + Hydrochlorothiazide", cat: "Heart & Blood Pressure", kind: "Tablet",
    simple: "ARB plus water pill — blocks the pressure hormone while nudging salt-and-water out; chosen when swelling or volume matters in hypertension.",
    uses: ["Hypertension", "BP with fluid tendency"],
    how: "One morning tablet; electrolytes are checked periodically.",
    watch: ["Cramps (potassium shifts)", "Dizziness"],
    alert: "Gout and diabetes need monitoring (thiazide effects). Pregnancy contraindicated.",
    brands: ["Telma H", "Telsartan-H"],
  },
  {
    salt: "Losartan + Hydrochlorothiazide", cat: "Heart & Blood Pressure", kind: "Tablet",
    simple: "The older ARB+diuretic pair — losartan relaxes vessels while the thiazide sheds excess salt and water.",
    uses: ["Hypertension", "BP with oedema tendency"],
    how: "Morning tablet; periodic electrolytes and creatinine.",
    watch: ["Dizziness", "Electrolyte shifts"],
    alert: "Pregnancy contraindicated; gout needs monitoring.",
    brands: ["Losar-H", "Repase-H"],
  },
  {
    salt: "Aspirin + Atorvastatin", cat: "Heart & Blood Pressure", kind: "Capsule",
    simple: "Heart-protection pair — low-dose aspirin keeps platelets from clotting while atorvastatin holds cholesterol and plaque stability down.",
    uses: ["Post-cardiac-event prevention", "High-risk vascular prevention"],
    how: "One capsule at night after food, daily and indefinitely as advised.",
    watch: ["Bruising", "Muscle aches (statin)"],
    alert: "Bleeding signs need urgent care; stop before surgery only per surgical team.",
    brands: ["Ecosprin AV 75", "Ecosprin AV 150"],
  },
  {
    salt: "Clopidogrel + Aspirin", cat: "Heart & Blood Pressure", kind: "Tablet",
    simple: "The dual anti-platelet pair (DAPT) after stents — two different platelet blockers so clots can't form on the stent surface.",
    uses: ["After stenting", "Acute coronary syndrome", "High-risk post-MI"],
    how: "One tablet daily each; duration (usually 6–12 months) is set by the cardiologist — never stop early.",
    watch: ["Easy bruising", "Gum bleeding"],
    alert: "Any surgery or dental extraction must be planned around DAPT with both doctors. Black stools are an emergency.",
    brands: ["Deplatt A 75", "Clopilet A 75"],
  },
  {
    salt: "Metformin + Glimepiride", cat: "Diabetes", kind: "Tablet",
    simple: "The Indian diabetes classic — metformin cuts liver sugar output while glimepiride pushes insulin release; combined power at affordable cost.",
    uses: ["Type 2 diabetes inadequately controlled on metformin"],
    how: "Taken WITH breakfast (glimepiride rule); carry glucose for hypos.",
    watch: ["Low sugar episodes", "Weight gain", "Stomach upset"],
    alert: "A hypo with confusion is an emergency. Kidney disease changes suitability — monitored regularly.",
    brands: ["Gluconorm-G 1", "Gluconorm-G 2", "Amaryl M 1", "Glimy M 2"],
  },
  {
    salt: "Sitagliptin + Metformin", cat: "Diabetes", kind: "Tablet",
    simple: "Smart-insulin protector plus the liver-sugar blocker — two complementary mechanisms in one morning tablet, low hypo risk.",
    uses: ["Type 2 diabetes", "Step-up from metformin monotherapy"],
    how: "Twice daily with meals (or per strength), as prescribed.",
    watch: ["Nasal congestion", "Stomach upset"],
    alert: "Report deep upper-abdominal pain (pancreatitis sign) promptly.",
    brands: ["Istamet 50/500", "Istamet 50/1000", "Janumet 50/500"],
  },
  {
    salt: "Amoxicillin + Clavulanic acid (dry syrup)", cat: "Antibiotics", kind: "Dry Syrup",
    simple: "The children's version of the shielded antibiotic — amoxicillin plus clavulanate reconstituted as a banana-flavoured dry syrup.",
    uses: ["Childhood chest/ear/throat infections", "Resistant paediatric infections"],
    how: "Dose by child's weight, twice or thrice daily, exactly as directed; the reconstituted bottle is refrigerated and finished within 7 days.",
    watch: ["Loose stools", "Nappy rash (thrush)"],
    alert: "Finish the course; severe rash or bloody stools need immediate review.",
    brands: ["Augmentin Duo Syrup", "Clavam Dry Syrup", "Moxikind-CV Dry Syrup"],
  },
  {
    salt: "Ofloxacin + Ornidazole", cat: "Antibiotics", kind: "Tablet",
    simple: "Bacteria-killer plus amoeba-killer in one tablet — ofloxacin handles gut bacteria while ornidazole clears amoebae and anaerobes; the classic Indian 'O2' for mixed diarrhoea.",
    uses: ["Infective diarrhoea", "Amoebiasis with bacterial component", "Mixed gut infection"],
    how: "One tablet twice daily after food for 3–5 days.",
    watch: ["Nausea", "Metallic taste"],
    alert: "No alcohol (ornidazole rule). Tendon pain (fluoroquinolone) means stop and report.",
    brands: ["O2 Tablet", "Zenflox-OZ", "Oflox-OZ"],
  },
  {
    salt: "Norfloxacin + Tinidazole", cat: "Antibiotics", kind: "Tablet",
    simple: "Urinary-and-gut pair — norfloxacin for bacteria, tinidazole for protozoa and anaerobes, in the standard travellers'-diarrhoea combination.",
    uses: ["Bacterial diarrhoea", "Mixed urinary infection", "Dysentery (as advised)"],
    how: "One tablet twice daily for 3–5 days.",
    watch: ["Nausea", "Metallic taste"],
    alert: "No alcohol. Blood in stool with fever needs examination rather than self-courses.",
    brands: ["Norflox TZ", "Norflox-TZ RF"],
  },
  {
    salt: "Montelukast + Levocetirizine", cat: "Allergy & Respiratory", kind: "Tablet",
    simple: "The allergy double-blocker night tablet — leukotriene and histamine pathways both shut for stubborn dust allergy and rhinitis.",
    uses: ["Severe allergic rhinitis", "Allergy with wheeze tendency"],
    how: "One tablet at bedtime after food.",
    watch: ["Drowsiness", "Headache"],
    alert: "Mood changes on montelukast are reported to the doctor.",
    brands: ["Montair LC", "Montek LC"],
  },
  {
    salt: "Terbutaline + Bromhexine + Guaifenesin (LS)", cat: "Allergy & Respiratory", kind: "Syrup",
    simple: "The gentler Ascoril-LS mix — levosalbutamol opens airways, ambroxol thins phlegm, guaifenesin eases the cough out, for chesty congested coughs.",
    uses: ["Productive cough with mild wheeze", "Bronchitis congestion"],
    how: "5–10 ml three times daily as prescribed.",
    watch: ["Tremor", "Palpitations (mild)", "Drowsiness"],
    alert: "High fever, blood-streaked sputum or breathlessness needs a chest exam.",
    brands: ["Ascoril LS Syrup", "Grilinctus-LM Syrup"],
  },
  {
    salt: "Vitamin B1 + B6 + B12 (Neurobion)", cat: "Vitamins & Supplements", kind: "Tablet · Injection",
    simple: "The nerve trio — thiamine, pyridoxine and cobalamin keep nerve insulation and blood cells healthy; the go-to for tingling feet and deficiency support.",
    uses: ["Nerve tingling", "Deficiency states", "Adjunct in nerve pain therapy"],
    how: "One tablet daily after food; injections for severe deficiency.",
    watch: ["Yellow urine (harmless)"],
    alert: "Chronic high-dose B6 itself harms nerves — label doses only.",
    brands: ["Neurobion Forte Tablet", "Neurobion Injection"],
  },
  {
    salt: "Calcium carbonate + Vitamin D3 + Zinc", cat: "Vitamins & Supplements", kind: "Tablet",
    simple: "The bone-support triple — calcium, absorbable vitamin D and a zinc assist for bone mineral and immune balance.",
    uses: ["Osteoporosis support", "Pregnancy bone needs", "Post-fracture healing"],
    how: "One tablet after a main meal; keep 4 hours from thyroid and iron tablets.",
    watch: ["Constipation"],
    alert: "Kidney-stone history needs medical dosing.",
    brands: ["Gemcal Capsule"],
  },
  {
    salt: "Iron + Folic acid + B12 (haematinic)", cat: "Vitamins & Supplements", kind: "Tablet · Suspension",
    simple: "The blood-building triple — iron for haemoglobin, folate and B12 for red-cell maturation; the pregnancy and anaemia workhorse.",
    uses: ["Anaemia of mixed cause", "Pregnancy supplementation", "Post-bleeding recovery"],
    how: "One tablet daily away from tea/coffee and calcium, with citrus ideally.",
    watch: ["Black stools", "Constipation", "Nausea"],
    alert: "Recheck haemoglobin in 4–6 weeks; non-response triggers deeper investigation.",
    brands: ["Autrin Tablet"],
  },
  {
    salt: "Cefuroxime + Clavulanic acid", cat: "Antibiotics", kind: "Tablet",
    simple: "Cefuroxime with a resistance-shield — a cephalosporin paired with clavulanate for stubborn respiratory and ENT infections.",
    uses: ["Resistant sinusitis", "Chest infection", "ENT infections"],
    how: "One tablet twice daily with food, full course completed.",
    watch: ["Diarrhoea", "Nausea"],
    alert: "Severe rash or bloody diarrhoea means stop-and-review.",
    },
  {
    salt: "Calcitriol + Calcium + Zinc", cat: "Bones & Joints", kind: "Softgel",
    simple: "Active-vitamin-D bone combo — calcitriol (the kidney-activated form) plus calcium and zinc, used in CKD-related and resistant bone disease.",
    uses: ["Renal bone disease", "Resistant vitamin-D deficiency"],
    how: "One softgel daily as titrated; calcium levels monitored.",
    watch: ["Thirst if calcium rises"],
    alert: "Overdose risk is real with calcitriol — periodic blood calcium is mandatory.",
    },
];
