/* Acidity, digestion, nausea, constipation — real molecules & Indian brands. */
module.exports = [
  {
    salt: "Pantoprazole", cat: "Acidity & Digestion", kind: "Tablet · Injection",
    strengths: ["20 mg Tablet", "40 mg Tablet"],
    simple: "A proton-pump inhibitor — it switches off the stomach's acid pumps at the source, so reflux burns less and ulcers can heal. Strongest class of antacid medicine.",
    uses: ["Acid reflux (GERD)", "Stomach ulcers", "With painkiller courses to protect stomach", "Zollinger-Ellison syndrome"],
    how: "One 40 mg tablet on an EMPTY stomach 30–60 minutes before breakfast — timing decides how well it works. Courses run 2–8 weeks.",
    watch: ["Headache", "Loose stools", "Bloating"],
    alert: "Don't take for years without review — long use can lower B12, magnesium and bone strength. Black stools or coffee-ground vomit is an emergency regardless.",
    brands: ["Pan 20", "Pan 40", "Pantocid 40", "Pantocid DSR"],
  },
  {
    salt: "Omeprazole", cat: "Acidity & Digestion", kind: "Capsule",
    strengths: ["10 mg Capsule", "20 mg Capsule"],
    simple: "The original acid-pump switch-off capsule, used for heartburn, ulcers and to protect the stomach during painkiller courses.",
    uses: ["Heartburn", "Stomach ulcer", "GERD", "NSAID stomach protection"],
    how: "10–20 mg before breakfast, capsule swallowed whole (it's coated to survive stomach acid).",
    watch: ["Headache", "Gas", "Constipation or loose stools"],
    alert: "Review long courses with a doctor. Severe chest pain always needs urgent care — don't assume it's just acidity.",
    brands: ["Omez 20", "Omez 10", "Ocid 20"],
  },
  {
    salt: "Rabeprazole", cat: "Acidity & Digestion", kind: "Tablet · Capsule",
    strengths: ["20 mg Tablet"],
    simple: "A fast-acting acid-pump blocker, often paired with domperidone in one capsule for reflux that comes with bloating and slow stomach emptying.",
    uses: ["GERD", "Ulcers", "Acidity with bloating", "H. pylori regimens"],
    how: "20 mg once daily before breakfast; the DSR form is taken before breakfast too.",
    watch: ["Headache", "Diarrhoea", "Drowsiness (with domperidone forms)"],
    alert: "Pregnancy-safe alternatives should be discussed. Any alarm signs — weight loss, black stools, vomiting blood — need endoscopy, not self-treatment.",
    brands: ["Razo 20", "Razo-D", "Rabium 20"],
  },
  {
    salt: "Esomeprazole", cat: "Acidity & Digestion", kind: "Tablet · Capsule",
    strengths: ["20 mg Tablet", "40 mg Tablet"],
    simple: "The refined left-handed form of omeprazole — same acid-pump shutdown, chosen for stubborn reflux and erosive ulcers.",
    uses: ["Severe GERD", "Erosive oesophagitis", "Ulcer healing"],
    how: "20–40 mg once daily before food, swallow whole.",
    watch: ["Headache", "Gas", "Nausea"],
    alert: "Long-term use needs periodic review. Worsening swallowing difficulty or weight loss needs a doctor promptly.",
    brands: ["Nexpro 20", "Nexpro 40", "Nexpro RD"],
  },
  {
    salt: "Domperidone", cat: "Acidity & Digestion", kind: "Tablet · Suspension",
    strengths: ["10 mg Tablet"],
    simple: "A stomach-movement booster — it tightens the valve between stomach and food pipe and speeds emptying, so food and acid move downward instead of up.",
    uses: ["Nausea and vomiting", "Bloating and early fullness", "Slow stomach emptying", "With acid blockers for reflux"],
    how: "10 mg up to three times daily, 15–30 minutes BEFORE meals. Best used for short periods.",
    watch: ["Dry mouth", "Headache"],
    alert: "Avoid with heart-rhythm problems and some antibiotics (it can lengthen the QT interval). Not for long unsupervised use.",
    brands: ["Domel 10", "Vomistop 10", "Domstal 10"],
  },
  {
    salt: "Ondansetron", cat: "Acidity & Digestion", kind: "Tablet (MD) · Syrup · Injection",
    strengths: ["4 mg Tablet (MD)", "8 mg Tablet", "2 mg/5 ml Syrup"],
    simple: "The go-to anti-vomiting medicine — it blocks serotonin signals in the gut and brain's vomit centre. Works for chemotherapy, post-op, gastroenteritis and motion sickness rescue.",
    uses: ["Vomiting from infection", "Chemotherapy vomiting", "Post-operative vomiting", "Fever-related vomiting in children (as advised)"],
    how: "4–8 mg up to three times daily; MD tablets melt on the tongue — handy when the patient can't keep water down.",
    watch: ["Headache", "Constipation"],
    alert: "Tell your doctor if the heart feels fluttery (QT effect with other drugs). Persistent vomiting beyond 24 hours needs assessment for dehydration.",
    brands: ["Emeset 4", "Emeset 8", "Vomikind 4 MD", "Ondem 4 MD"],
  },
  {
    salt: "Ranitidine", cat: "Acidity & Digestion", kind: "Tablet · Injection",
    strengths: ["150 mg Tablet", "300 mg Tablet"],
    simple: "An older acid-reducer that blocks histamine's acid signal. Many countries have recalled it over impurity concerns, so doctors now usually pick a PPI instead.",
    uses: ["Night-time acidity", "Heartburn", "Ulcer (historical use)"],
    how: "150 mg once or twice daily; if it is prescribed at all, it's usually short-term.",
    watch: ["Headache", "Constipation"],
    alert: "Ask your doctor about newer alternatives. Any chest pain must be medically assessed, not treated as acidity.",
    brands: ["Rantac 150", "Aciloc 150"],
  },
  {
    salt: "Famotidine", cat: "Acidity & Digestion", kind: "Tablet",
    strengths: ["20 mg Tablet", "40 mg Tablet"],
    simple: "A histamine-blocker acid reducer — milder than PPIs, good for occasional night-time heartburn without switching the pumps fully off.",
    uses: ["Occasional heartburn", "Night acidity", "Mild gastritis"],
    how: "20 mg once or twice daily; onset within an hour. Dose reduced in kidney disease.",
    watch: ["Headache", "Dizziness (rare)"],
    alert: "Frequent heartburn most days for weeks needs an endoscopy discussion, not endless self-treatment.",
    brands: ["Famocid 20", "Famocid 40"],
  },
  {
    salt: "Sucralfate", cat: "Acidity & Digestion", kind: "Tablet · Suspension",
    strengths: ["1 g Tablet", "1 g/10 ml Suspension"],
    simple: "A stomach bandage — it forms a protective paste that sticks over ulcers and raw patches, shielding them from acid while they heal.",
    uses: ["Stomach ulcer", "Gastritis", "Mouth ulcers (paste)", "Reflux oesophagitis"],
    how: "1 g four times a day on an empty stomach, taken at least 30 minutes BEFORE other medicines (it can block their absorption).",
    watch: ["Constipation", "Dry mouth"],
    alert: "Not absorbed much, so gentle — but in kidney failure aluminium can build up; use only under advice.",
    brands: ["Sucral O Suspension", "Sucrafil O Gel"],
  },
  {
    salt: "Magnesium hydroxide + Aluminium gel", cat: "Acidity & Digestion", kind: "Suspension · Tablet",
    simple: "Classic antacid liquid — aluminium gel soaks up acid while magnesium hydroxide neutralises it instantly. The minty 'chalk' that ends a heartburn episode in minutes.",
    uses: ["Heartburn attacks", "Acidity after heavy/spicy meals", "Gas and belching"],
    how: "10–20 ml after meals and at bedtime, or when burning starts; chewable forms are chewed then followed with water.",
    watch: ["Loose stools (magnesium-heavy) or constipation (aluminium-heavy)"],
    alert: "Frequent daily antacid use for weeks hides real ulcers — get checked. Keep 2 hours between antacids and other medicines.",
    brands: ["Digene Gel Mint", "Gelusil MPS", "Digene Tablet"],
  },
  {
    salt: "Sodium bicarbonate antacid", cat: "Acidity & Digestion", kind: "Effervescent Powder",
    simple: "A fast fizzing antacid — bicarbonate meets stomach acid and releases gas, ending heartburn within minutes. A rescue remedy, not a daily medicine.",
    uses: ["Sudden heartburn", "Acid indigestion"],
    how: "Stir one sachet in water and drink after it fizzes; occasional use only.",
    watch: ["Burping", "Feeling bloated"],
    alert: "High-salt content — avoid in high BP, kidney and heart disease unless advised. Daily heartburn needs a proper evaluation.",
    brands: ["Eno Fruit Salt Lemon", "Eno Fruit Salt Regular"],
  },
  {
    salt: "Dicyclomine", cat: "Acidity & Digestion", kind: "Tablet · Syrup · Injection",
    strengths: ["10 mg Tablet", "20 mg Tablet", "10 mg/5 ml Syrup"],
    simple: "An anti-spasmodic that relaxes cramping gut muscle — the standard tablet for gripping abdominal pain and period-like gut cramps.",
    uses: ["Stomach cramps", "Irritable bowel cramps", "Infant colic (as advised)", "Gut spasm with diarrhoea"],
    how: "10–20 mg up to four times a day as needed. It dries the mouth slightly and can blur vision briefly.",
    watch: ["Dry mouth", "Dizziness", "Blurred vision (brief)"],
    alert: "Severe abdominal pain should be examined first — spasmodics can mask appendicitis. Glaucoma patients should avoid it.",
    brands: ["Cyclopam Tablet", "Cyclopam Syrup", "Spasmonil Plus"],
  },
  {
    salt: "Mebeverine", cat: "Acidity & Digestion", kind: "Tablet",
    strengths: ["135 mg Tablet"],
    simple: "A gut-specific anti-spasmodic for IBS — it acts directly on colon muscle without the dry-mouth effects of older spasmodics.",
    uses: ["Irritable bowel syndrome", "Cramping with IBS", "Mucus colitis"],
    how: "135 mg three times daily, ideally 20 minutes before meals.",
    watch: ["Nausea (rare)", "Headache"],
    alert: "IBS should be diagnosed by a doctor first — weight loss or bleeding is never IBS.",
    brands: ["Colospa Retard", "Colospa 135"],
  },
  {
    salt: "Loperamide", cat: "Acidity & Digestion", kind: "Tablet · Capsule",
    strengths: ["2 mg Capsule"],
    simple: "An anti-motility medicine that slows the bowel so stools firm up. For simple acute diarrhoea rescue — but it must never be used when there is fever or blood in the stool.",
    uses: ["Acute simple diarrhoea", "Traveller's loose motions (no fever)", "Ileostomy output control"],
    how: "2 mg after each loose stool, maximum 8 mg/day for 2 days, with ORS fluids in between.",
    watch: ["Constipation after overuse", "Bloating"],
    alert: "Never in dysentery (blood/fever) — locking toxins inside worsens illness. Abdominal swelling with no stool means stop and seek care.",
    brands: ["Imodium 2mg", "Lopamide 2mg"],
  },
  {
    salt: "Oral rehydration salts (ORS)", cat: "Acidity & Digestion", kind: "Sachet Powder",
    simple: "The world's most lifesaving sachet — a precise sugar-salt mix that pulls water back into the body through the gut lining, replacing what diarrhoea steals.",
    uses: ["Dehydration from diarrhoea", "Vomiting losses", "Heat dehydration"],
    how: "Dissolve one sachet in exactly 1 litre of clean water (not milk/juice), sip continuously; children take small sips every few minutes. Make a fresh batch every day.",
    watch: ["Mild nausea if gulped fast"],
    alert: "Signs of dehydration — no urine for 8 hours, sunken eyes, drowsiness, cold hands — need hospital care, not just ORS.",
    brands: ["Electral Sachet", "ORS Orange Sachet", "F-75 ORS Sachet"],
  },
  {
    salt: "Lactulose", cat: "Acidity & Digestion", kind: "Syrup",
    strengths: ["10 g/15 ml Syrup"],
    simple: "A sugar the human gut can't digest — bacteria ferment it, pulling water into the stool and softening it naturally over 1–2 days.",
    uses: ["Chronic constipation", "Soft stools after surgery", "Hepatic encephalopathy (higher doses)"],
    how: "15 ml at bedtime, adjustable up to twice daily; drink extra water. Effect builds over a couple of days.",
    watch: ["Gas and rumbling (first days)", "Loose stools if overdosed"],
    alert: "Very sticky sweetness — diabetics should use under advice. No stool plus vomiting and pain means obstruction — hospital now.",
    brands: ["Duphalac Syrup", "Looz Syrup"],
  },
  {
    salt: "Milk of magnesia + Liquid paraffin", cat: "Acidity & Digestion", kind: "Suspension",
    simple: "A two-way laxative: magnesium salts pull water into the bowel while paraffin lubricates the stool so it slides out easily by morning.",
    uses: ["Constipation", "Painful fissure-related constipation", "Bedridden patients"],
    how: "10–30 ml at bedtime with water; keep well hydrated. Rescue use for a few days, not a daily habit.",
    watch: ["Loose stools", "Oil leakage with high doses"],
    alert: "Daily laxative dependence should be reviewed. Sudden constipation with vomiting and pain is an emergency.",
    brands: ["Cremaffin Syrup", "Cremaffin Plus"],
  },
  {
    salt: "Isabgol (Psyllium husk)", cat: "Acidity & Digestion", kind: "Granules Powder",
    simple: "Natural fibre husk that swells into a soft gel in the gut — it bulks loose stools AND softens hard ones, the gentle regulator for daily bowel care.",
    uses: ["Chronic constipation", "IBS stool regulation", "Cholesterol support", "Loose stools with fibre need"],
    how: "1–2 teaspoons in a full glass of water at bedtime, drunk immediately before it gels — followed by more water.",
    watch: ["Bloating first few days", "Needs lots of water or it can firm up instead"],
    alert: "Never take it dry. Swallowing difficulty or unexplained weight loss needs medical review, not just fibre.",
    brands: ["Isabgol Powder Natural", "Sat Isabgol"],
  },
  {
    salt: "Ursodeoxycholic acid", cat: "Acidity & Digestion", kind: "Tablet",
    strengths: ["150 mg Tablet", "300 mg Tablet"],
    simple: "A 'friendly bile acid' that makes bile less stone-forming and shields liver cells — used for gallstones (chosen cases) and itchy liver conditions in pregnancy.",
    uses: ["Small cholesterol gallstones", "Intrahepatic cholestasis of pregnancy", "Fatty liver with bile stasis"],
    how: "8–15 mg/kg per day in divided doses, or as directed; gallstone therapy runs 6–12 months with ultrasound checks.",
    watch: ["Loose stools", "Nausea"],
    alert: "Gallstone attacks (right-upper-belly pain after fatty meals) still need surgical opinion — tablets don't fix a blocked stone.",
    brands: ["Udiliv 300", "Udiliv 150", "Ursocol 300"],
  },
  {
    salt: "Saccharomyces boulardii (probiotic)", cat: "Acidity & Digestion", kind: "Sachet · Capsule",
    simple: "A beneficial yeast that crowds out harmful germs and steadies the gut lining — added to diarrhoea treatment to shorten the loose-stool days.",
    uses: ["Acute diarrhoea (adjunct)", "Antibiotic-associated loose stools", "Traveller's diarrhoea"],
    how: "One sachet/capsule once or twice daily during the episode; can continue a few days after stools normalise.",
    watch: ["Gas", "Mild bloating"],
    alert: "Avoid in severely immunosuppressed patients and central lines — rare fungal spread. Persistent diarrhoea beyond 3 days needs evaluation.",
    brands: ["Econorm Sachet", "Econorm Powder"],
  },
  {
    salt: "Multistrain probiotics", cat: "Acidity & Digestion", kind: "Capsule · Sachet",
    simple: "A mix of friendly Lactobacillus and Bifidobacterium bacteria that re-balances gut flora after antibiotics or infection.",
    uses: ["After antibiotic courses", "Antibiotic-associated diarrhoea", "IBS support"],
    how: "One capsule/sachet once or twice daily, ideally spaced 2–3 hours from the antibiotic dose.",
    watch: ["Gas in the first days"],
    alert: "Immunocompromised patients should ask their doctor first. Severe bloody diarrhoea needs a physician, not probiotics.",
    brands: ["Vizylac Capsule", "Darolac Sachet", "Enterogermina Vial"],
  },
  {
    salt: "Polyethylene glycol (PEG)", cat: "Acidity & Digestion", kind: "Powder Sachet",
    simple: "An osmotic laxative — long sugar chains hold water in the stool mechanically (no stimulant cramping), making it the preferred gentle daily softener.",
    uses: ["Chronic constipation", "Hard painful stools", "Bowel prep before procedures (medical dose)"],
    how: "One sachet dissolved in a glass of water, once daily; effect in 1–3 days. Adjust dose to stool softness.",
    watch: ["Bloating", "Nausea"],
    alert: "Severe abdominal pain or no gas passing means obstruction — emergency. Heart/kidney failure patients use under advice.",
    brands: ["Pegclear Sachet", "Laxipeg Sachet"],
  },
];
