/* Digestion & gut — second wave: IBD, motility, liver. */
module.exports = [
  {
    salt: "Mesalamine", cat: "Acidity & Digestion", kind: "Tablet · Suppository · Enema",
    strengths: ["400 mg Tablet", "800 mg Tablet", "1200 mg ER Tablet"],
    simple: "A gut-targeted anti-inflammatory — releases its effect locally on the bowel lining to keep ulcerative colitis quiet and maintain remission.",
    uses: ["Ulcerative colitis", "Crohn's disease (mild)", "Distal colitis (suppository/enema)"],
    how: "2.4–4.8 g daily in divided doses per protocol; kidney function is checked periodically.",
    watch: ["Nausea", "Headache", "Rare kidney irritation"],
    alert: "Blood in urine or reduced output on long use needs renal review. It is maintenance therapy — never self-stop during remission.",
    brands: ["Mesacol 400", "Mesacol 800", "Asacol (global)"],
  },
  {
    salt: "Sulfasalazine", cat: "Acidity & Digestion", kind: "Tablet",
    strengths: ["500 mg Tablet"],
    simple: "An old two-in-one molecule — a sulfa antibiotic joined to an anti-inflammatory, activated by gut bacteria; treats both ulcerative colitis and rheumatoid arthritis.",
    uses: ["Ulcerative colitis", "Rheumatoid arthritis", "Ankylosing spondylitis"],
    how: "Titrate up to 2–3 g daily with food; folic acid is usually co-prescribed.",
    watch: ["Nausea", "Orange-yellow urine (harmless)", "Headache", "Low counts (monitored)"],
    alert: "Sulfa allergy contraindicates it. Fever with rash needs blood counts the same day.",
    brands: ["Salazopyrin 500", "Saaz 500"],
  },
  {
    salt: "Rifaximin", cat: "Acidity & Digestion", kind: "Tablet",
    strengths: ["200 mg Tablet", "400 mg Tablet", "550 mg Tablet"],
    simple: "A gut-local antibiotic that barely absorbs into blood — floods the bowel to reset bacterial overgrowth and hepatic-encephalopathy toxins without systemic effects.",
    uses: ["Hepatic encephalopathy (long-term)", "IBS-Diarrhoea", "Traveller's diarrhoea", "Small-intestine bacterial overgrowth"],
    how: "550 mg twice daily (HE) or 400 mg three times for 3 days (traveller's); lactulose continues alongside in liver disease.",
    watch: ["Nausea", "Flatulence"],
    alert: "Confusion in liver patients on it still needs hospital review — the medicine helps but doesn't cure the underlying disease.",
    brands: ["Rifagut 550", "Rifagut 400", "Xifaxan (global)"],
  },
  {
    salt: "Racecadotril", cat: "Acidity & Digestion", kind: "Capsule · Sachet",
    strengths: ["100 mg Capsule"],
    simple: "An antisecretory diarrhoea medicine — unlike loperamide it doesn't freeze the gut; it simply tells the intestine to stop pouring water, so stools firm naturally.",
    uses: ["Acute watery diarrhoea", "Childhood diarrhoea (with ORS)"],
    how: "100 mg three times daily (children by weight) until stools normalise, max 7 days, always with ORS fluids.",
    watch: ["Headache", "Thirst"],
    alert: "Fever or blood in stool needs medical review — antisecretories don't treat dysentery.",
    brands: ["Redotil 100", "Qreda 100"],
  },
  {
    salt: "Prucalopride", cat: "Acidity & Digestion", kind: "Tablet",
    strengths: ["1 mg Tablet", "2 mg Tablet"],
    simple: "A 5HT4 agonist that directly kicks the colon's peristaltic reflex back to life — the modern choice when osmotic laxatives aren't enough.",
    uses: ["Chronic constipation unresponsive to laxatives", "Slow-transit constipation"],
    how: "2 mg once daily (1 mg in elderly/kidney disease); effect within 3–4 days.",
    watch: ["Headache", "Nausea", "Abdominal pain (early)"],
    alert: "Severe abdominal pain with no stool means obstruction — hospital, not more tablets.",
    brands: ["Prulife 2", "Resolor (global)"],
  },
  {
    salt: "Itopride", cat: "Acidity & Digestion", kind: "Tablet",
    strengths: ["50 mg Tablet"],
    simple: "A prokinetic popular in Asia — boosts stomach emptying through dopamine-blockade AND acetylcholine release, easing fullness, bloating and early satiety.",
    uses: ["Functional dyspepsia", "Slow stomach emptying", "Bloating with meals"],
    how: "50 mg three times daily BEFORE meals.",
    watch: ["Mild cramping", "Salivation"],
    alert: "It raises acetylcholine — stomach obstruction and bleeding need exclusion before use.",
    brands: ["Ibset 50", "Ganaton 50"],
  },
  {
    salt: "Levosulpiride", cat: "Acidity & Digestion", kind: "Tablet · Capsule (SR)",
    strengths: ["25 mg Tablet", "75 mg SR Capsule"],
    simple: "A prokinetic with a psychotropic twist — dopamine-modulating doses help gut motility and functional dyspepsia with anxiety-linked symptoms.",
    uses: ["Functional dyspepsia", "GERD with slow emptying", "IBS with motility issues"],
    how: "25 mg before meals or 75 mg SR before breakfast.",
    watch: ["Drowsiness", "Weight change", "Prolactin rise (breast changes, cycle changes)"],
    alert: "QT and movement cautions like other dopamine blockers; not for long unsupervised use.",
    brands: ["Levopraid 25", "Levosulpiride SR 75 Capsule"],
  },
  {
    salt: "Mosapride", cat: "Acidity & Digestion", kind: "Tablet",
    strengths: ["5 mg Tablet"],
    simple: "A 5HT4 prokinetic — speeds gastric emptying with minimal heart-rhythm concerns compared to older prokinetics.",
    uses: ["Functional dyspepsia", "GERD adjunct", "Gastroparesis (mild)"],
    how: "5 mg three times daily before meals.",
    watch: ["Headache", "Mild diarrhoea"],
    alert: "Obstruction must be excluded first. QT caution in heavy polypharmacy.",
    brands: ["Mozov 5", "Mosapride 5mg Tablet"],
  },
  {
    salt: "Plecanatide", cat: "Acidity & Digestion", kind: "Tablet",
    strengths: ["3 mg Tablet"],
    simple: "A guanylate-cyclase agonist that mimics the gut's own laxative peptides — pulls water into the colon gently, with little systemic absorption.",
    uses: ["Chronic idiopathic constipation", "IBS with constipation"],
    how: "3 mg once daily, with or without food.",
    watch: ["Diarrhoea (dose-related)", "Bloating"],
    alert: "Severe diarrhoea means pause and review dose. Paediatric use is avoided.",
    brands: ["Trulance (global)"],
  },
  {
    salt: "Silymarin", cat: "Acidity & Digestion", kind: "Tablet",
    strengths: ["70 mg Tablet", "140 mg Tablet"],
    simple: "Milk-thistle extract used as liver support — antioxidant and membrane-stabilising actions, prescribed alongside lifestyle change in fatty liver and toxic exposure.",
    uses: ["Fatty liver support", "Liver protection adjunct", "Drug-induced liver stress (supportive)"],
    how: "140 mg two or three times daily after food for months.",
    watch: ["Mild laxative effect"],
    alert: "Supportive, not curative — the underlying cause (alcohol, weight, hepatitis) still needs the real treatment plan.",
    brands: ["Silybon 140"],
  },
  {
    salt: "N-acetylcysteine", cat: "Acidity & Digestion", kind: "Tablet · Sachet · Injection",
    strengths: ["600 mg Tablet"],
    simple: "The antidote and mucolytic hero — replenishes glutathione to detox paracetamol overdose in hospital, and thins mucus in chest disease as oral therapy.",
    uses: ["Paracetamol overdose (hospital antidote)", "Chronic cough with sticky mucus", "COPD mucus support"],
    how: "Overdose protocols are hospital-only IV schedules; oral 600 mg once-twice daily for mucus.",
    watch: ["Nausea", "Heartburn"],
    alert: "Paracetamol overdose is a medical emergency — the antidote works best within 8 hours; hospital immediately.",
    brands: ["Acetylcysteine 600mg Tablet", "Mucomix 600"],
  },
];
