/* Heart, blood pressure, cholesterol, blood thinners — real molecules & Indian brands. */
module.exports = [
  {
    salt: "Amlodipine", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["2.5 mg Tablet", "5 mg Tablet", "10 mg Tablet"],
    simple: "A calcium-channel blocker that relaxes artery walls so blood flows with less push — lowering pressure gently over 24 hours, once a day.",
    uses: ["High blood pressure", "Angina (chest pain)", "Coronary artery disease"],
    how: "One tablet daily at a fixed time, with or without food. Ankle puffiness is the classic effect — tell your doctor rather than stopping abruptly.",
    watch: ["Ankle swelling", "Flushing", "Headache in the first week"],
    alert: "Dizziness with fainting means BP has dipped too low — needs review. Never combine with sildenafil-type drugs without advice.",
    brands: ["Amlopres 5", "Amlopres 2.5", "Amlong 5", "Amlokind 5"],
  },
  {
    salt: "Telmisartan", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["20 mg Tablet", "40 mg Tablet", "80 mg Tablet"],
    simple: "An ARB — it blocks angiotensin, the hormone that tightens vessels, so arteries stay relaxed and pressure falls. Also protects kidneys in diabetes.",
    uses: ["High blood pressure", "Diabetic kidney protection", "Heart failure (selected)"],
    how: "One tablet daily, with or without food. Kidney function and potassium are checked periodically.",
    watch: ["Dizziness on starting", "Raised potassium (monitored)"],
    alert: "Strictly avoid in pregnancy — it can harm the baby. Combining with painkillers like diclofenac regularly can strain kidneys.",
    brands: ["Telma 20", "Telma 40", "Telma 80", "Telsartan 40"],
  },
  {
    salt: "Losartan", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["25 mg Tablet", "50 mg Tablet"],
    simple: "The original ARB — blocks the vessel-tightening hormone angiotensin, easing pressure and shielding kidneys, especially in diabetics with protein leak.",
    uses: ["High blood pressure", "Diabetic nephropathy", "Stroke risk reduction"],
    how: "25–50 mg once or twice daily as prescribed; potassium-rich salt substitutes should be avoided unless advised.",
    watch: ["Dizziness", "Tiredness early on"],
    alert: "Avoid completely in pregnancy. Regular creatinine and potassium tests are part of therapy.",
    brands: ["Losar 25", "Losar 50", "Repase 50"],
  },
  {
    salt: "Olmesartan", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["20 mg Tablet", "40 mg Tablet"],
    simple: "A potent ARB blood-pressure tablet with 24-hour action, often the base of fixed combinations with amlodipine or a water pill.",
    uses: ["Hypertension", "Hypertension with kidney strain"],
    how: "20–40 mg once daily, fixed time; blood tests monitor kidneys and potassium.",
    watch: ["Dizziness", "Headache"],
    alert: "Pregnancy is an absolute no. Persistent watery diarrhoea on long use (rare sprue-like enteropathy) must be reported.",
    brands: ["Olmesar 20", "Olmesar 40", "Benicar 20"],
  },
  {
    salt: "Ramipril", cat: "Heart & Blood Pressure", kind: "Capsule · Tablet",
    strengths: ["2.5 mg Capsule", "5 mg Capsule", "10 mg Capsule"],
    simple: "An ACE inhibitor — it stops angiotensin being formed at all. Protects the heart after a heart attack and slows diabetic kidney damage.",
    uses: ["Hypertension", "After heart attack", "Heart failure", "Diabetic kidney disease"],
    how: "2.5–10 mg once daily; a dry irritating cough is the class's known quirk — tell your doctor (switching to an ARB fixes it).",
    watch: ["Dry persistent cough", "Dizziness on first doses", "Raised potassium"],
    alert: "Swelling of lips/tongue (angioedema) is a stop-immediately emergency. Avoid in pregnancy.",
    brands: ["Cardace 2.5", "Cardace 5", "Ramistar 5"],
  },
  {
    salt: "Enalapril", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["2.5 mg Tablet", "5 mg Tablet", "10 mg Tablet"],
    simple: "An older ACE inhibitor that lowers pressure and eases the heart's workload in failure — affordable and well-studied.",
    uses: ["Hypertension", "Heart failure", "Left ventricle weakness"],
    how: "2.5–10 mg once or twice daily; keep potassium supplements and salt substitutes off unless advised.",
    watch: ["Dry cough", "Dizziness"],
    alert: "Face/lip swelling = emergency stop. Pregnancy contraindicated.",
    brands: ["Envas 5", "Envas 10", "Nalapres 5"],
  },
  {
    salt: "Metoprolol", cat: "Heart & Blood Pressure", kind: "Tablet · Tablet (XL)",
    strengths: ["25 mg Tablet", "50 mg Tablet", "25 mg XL Tablet"],
    simple: "A beta-blocker that slows and steadies the heart — used after heart attacks, for palpitations, BP and angina. It turns the heart's 'revving' down.",
    uses: ["High blood pressure", "Palpitations", "After heart attack", "Angina", "Thyroid storm support"],
    how: "25–100 mg daily in one or two doses; never stop suddenly — the heart can rebound (taper on doctor's advice).",
    watch: ["Slow pulse", "Tiredness", "Cold hands and feet", "Vivid dreams (XL)"],
    alert: "Pulse under ~50/min, fainting or severe breathlessness needs review. Diabetics: it can hide hypo warning signs.",
    brands: ["Metolar 25", "Metolar 50", "Betaloc 25", "Metolar XL 25"],
  },
  {
    salt: "Bisoprolol", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["2.5 mg Tablet", "5 mg Tablet"],
    simple: "A highly heart-selective beta-blocker — the standard partner in heart-failure therapy, proven to help the weak pump work longer and steadier.",
    uses: ["Heart failure", "Hypertension", "Stable angina"],
    how: "Once daily, started low and escalated by the doctor over weeks. Same never-stop-suddenly rule.",
    watch: ["Slow pulse", "Fatigue in the first weeks", "Dizziness"],
    alert: "Sudden breathlessness or pulse persistently below 50 needs assessment. Asthma patients need specialist judgement before beta-blockers.",
    brands: ["Concor 2.5", "Concor 5", "Corbis 2.5", "Bisotab 5"],
  },
  {
    salt: "Atenolol", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["25 mg Tablet", "50 mg Tablet"],
    simple: "A classic beta-blocker for BP, palpitations and anxiety-related racing heart — long used, inexpensive, once daily.",
    uses: ["Hypertension", "Palpitations", "Angina", "Performance-anxiety racing heart"],
    how: "25–50 mg once daily; taper never-abrupt rule applies.",
    watch: ["Cold extremities", "Slow pulse", "Fatigue"],
    alert: "Asthma can worsen — always disclose it. Combine cautiously with diltiazem/verapamil (pulse can drop dangerously).",
    brands: ["Tenormin 25", "Aten 25", "Tenolol 50"],
  },
  {
    salt: "Propranolol", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["10 mg Tablet", "20 mg Tablet", "40 mg Tablet"],
    simple: "The non-selective beta-blocker — besides BP and palpitations it prevents migraine, steadies essential tremor and calms thyroid-related racing.",
    uses: ["Palpitations", "Migraine prevention", "Essential tremor", "Thyroid overactivity support", "Anxiety symptoms (somatic)"],
    how: "10–40 mg two or three times daily as directed; tapering is required after long use.",
    watch: ["Tiredness", "Cold hands", "Slow pulse"],
    alert: "Never in asthma. Diabetics watch for masked hypos. Sudden stop can trigger rebound palpitations.",
    brands: ["Ciplar 10", "Ciplar LA 20", "Inderal 10"],
  },
  {
    salt: "Carvedilol", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["3.125 mg Tablet", "6.25 mg Tablet"],
    simple: "A beta-blocker with extra vessel-relaxing action — a proven pillar of heart-failure treatment that eases both the pump and the pipes.",
    uses: ["Heart failure", "Hypertension", "Post-heart-attack protection"],
    how: "Taken with food, started tiny (3.125 mg) and escalated slowly by the doctor.",
    watch: ["Dizziness on standing", "Weight gain early", "Slow pulse"],
    alert: "Report worsening breathlessness or swelling in the first weeks — the dose may need slowing. Never stop abruptly.",
    brands: ["Carca 3.125", "Carca 6.25", "Carca 12.5"],
  },
  {
    salt: "Nebivolol", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["2.5 mg Tablet", "5 mg Tablet"],
    simple: "A gentle third-generation beta-blocker that also releases nitric oxide to relax vessels — fewer tiredness complaints than older blockers.",
    uses: ["Hypertension", "Heart failure (selected)"],
    how: "2.5–5 mg once daily, food optional.",
    watch: ["Headache", "Slow pulse", "Tiredness"],
    alert: "Same taper rule. Severe asthma and heart block need specialist caution.",
    brands: ["Nebicard 2.5", "Nebicard 5", "Nobivol 5"],
  },
  {
    salt: "Torsemide", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["5 mg Tablet", "10 mg Tablet", "20 mg Tablet"],
    simple: "A modern loop diuretic that flushes out salt and water — the workhorse for heart-failure swelling in legs and lungs, acting within the hour.",
    uses: ["Heart failure congestion", "Kidney-related swelling", "Liver-related fluid"],
    how: "Morning dose (so sleep isn't disturbed by bathroom trips); potassium levels are monitored.",
    watch: ["More urination", "Cramps from potassium loss", "Dizziness from dehydration"],
    alert: "Weigh yourself daily on diuretics — 2 kg jump in 3 days means congestion is building; call your doctor. Severe cramps or irregular heartbeat needs urgent potassium check.",
    brands: ["Dytor 5", "Dytor 10", "Dytor 20", "Torvas 10"],
  },
  {
    salt: "Furosemide", cat: "Heart & Blood Pressure", kind: "Tablet · Injection",
    strengths: ["20 mg Tablet", "40 mg Tablet", "20 mg Injection"],
    simple: "The classic loop diuretic for pulling fluid out fast — in lungs flooded by heart failure it is the emergency dewatering tool.",
    uses: ["Pulmonary congestion", "Leg oedema", "Hypertension with fluid overload"],
    how: "Morning tablet as prescribed; hospital injections act within minutes for emergencies.",
    watch: ["Excess urination", "Potassium loss cramps", "Low BP on standing"],
    alert: "Daily weight and swelling checks matter; sudden weight gain or breathlessness lying flat needs same-day review.",
    brands: ["Lasix 20", "Lasix 40"],
  },
  {
    salt: "Spironolactone", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["25 mg Tablet", "50 mg Tablet"],
    simple: "A potassium-sparing 'water tablet' that blocks aldosterone — remodels the stressed heart in failure and tames hormonal fluid retention and acne in PCOS.",
    uses: ["Heart failure", "Resistant hypertension", "PCOS hormonal symptoms", "Liver-related fluid"],
    how: "25–50 mg morning dose; potassium and creatinine are rechecked after starting — the doctor pairs it carefully with other drugs.",
    watch: ["Breast tenderness in men", "Period changes in women", "Raised potassium"],
    alert: "Do NOT take potassium supplements or salt substitutes alongside without advice — dangerous potassium peaks.",
    brands: ["Aldactone 25", "Aldactone 50", "Spironol 25"],
  },
  {
    salt: "Hydrochlorothiazide", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["12.5 mg Tablet", "25 mg Tablet"],
    simple: "The classic thiazide water pill — modest salt-and-water loss that meaningfully lowers BP, often inside ARB combination tablets.",
    uses: ["Hypertension", "Mild fluid retention", "Kidney stones (calcium)"],
    how: "Morning dose; it slightly drops potassium and raises uric acid and sugar — blood tests track these.",
    watch: ["Cramps", "Dizziness", "Sun sensitivity"],
    alert: "Gout patients beware — it raises uric acid. Severe weakness from low sodium/potassium needs urgent electrolytes.",
    brands: ["Aquazide 12.5", "Hydrazide 25"],
  },
  {
    salt: "Atorvastatin", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["10 mg Tablet", "20 mg Tablet", "40 mg Tablet", "80 mg Tablet"],
    simple: "A statin — it blocks the liver's cholesterol factory, pulling LDL ('bad cholesterol') down and steadying artery plaques so they don't rupture into heart attacks.",
    uses: ["High cholesterol", "After heart attack/stent", "Diabetes with risk factors", "Stroke prevention"],
    how: "One tablet at night (the liver makes cholesterol overnight), with or without food. It is a lifelong medicine once indicated, not a course.",
    watch: ["Muscle aches (report if severe)", "Mild liver enzyme rise (monitored)"],
    alert: "Dark urine + muscle weakness + fever together suggest rare muscle breakdown (rhabdomyolysis) — stop and test immediately. Avoid grapefruit juice.",
    brands: ["Atorva 10", "Atorva 20", "Atorva 40", "Storvas 20"],
  },
  {
    salt: "Rosuvastatin", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["5 mg Tablet", "10 mg Tablet", "20 mg Tablet"],
    simple: "The most potent common statin — biggest LDL drop per milligram, often chosen after heart attacks or when targets are strict.",
    uses: ["High cholesterol", "Post-stent/heart attack", "High-risk prevention"],
    how: "One tablet evening/night; same lifelong rhythm as atorvastatin with periodic lipid and liver tests.",
    watch: ["Muscle aches", "Headache"],
    alert: "Same muscle-danger rule as atorvastatin. Tell your doctor about all other medicines — interactions matter here.",
    brands: ["Rosuvas 5", "Rosuvas 10", "Rozavel 10", "Rosutor 10"],
  },
  {
    salt: "Fenofibrate", cat: "Heart & Blood Pressure", kind: "Tablet · Capsule",
    strengths: ["145 mg Tablet", "160 mg Tablet", "200 mg Capsule"],
    simple: "A triglyceride-lowering tablet — targets the 'fats' beyond cholesterol, often paired with a statin when both are high.",
    uses: ["High triglycerides", "Mixed dyslipidaemia", "Pancreatitis prevention in very high TG"],
    how: "One tablet daily with food; keep alcohol low (it fuels triglycerides).",
    watch: ["Stomach upset", "Muscle aches (more when combined with statin)"],
    alert: "Gallstones or severe kidney disease need caution. Muscle pain with dark urine = stop and test.",
    brands: ["Lipicard 160", "Lipofen 145", "Fenofib 200"],
  },
  {
    salt: "Clopidogrel", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["75 mg Tablet"],
    simple: "A blood-platelet 'un-sticker' — keeps platelets from clumping inside stents and narrowed arteries. The anti-stroke and anti-stent-clot tablet.",
    uses: ["After stent placement", "After heart attack", "Ischaemic stroke", "Peripheral artery disease"],
    how: "One 75 mg tablet daily, with or without food — never skipped, since even 2 missed days raise stent-clot risk.",
    watch: ["Easy bruising", "Bleeding gums", "Longer bleeding from cuts"],
    alert: "Never start or stop it (or aspirin) around surgery/dental work without telling every doctor. Black stools or vomiting blood is an emergency.",
    brands: ["Clopilet 75", "Deplatt 75", "Clavix 75"],
  },
  {
    salt: "Aspirin (low dose)", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["75 mg Tablet", "150 mg Tablet"],
    simple: "Micro-dose aspirin as a daily blood-platelet un-sticker — proven secondary prevention after heart attacks and strokes. Not started casually; bleeding risk is real.",
    uses: ["After heart attack", "After ischaemic stroke", "High-risk prevention (doctor-decided)"],
    how: "One tablet after breakfast daily; the enteric-coated form reduces stomach contact.",
    watch: ["Stomach burning", "Easy bruising"],
    alert: "Black stools or any unusual heavy bleeding needs urgent care. Stop before surgery only on the operating team's advice.",
    brands: ["Ecosprin 75", "Ecosprin 150", "Loprin 75"],
  },
  {
    salt: "Nitroglycerin", cat: "Heart & Blood Pressure", kind: "Sublingual Tablet · Spray",
    strengths: ["0.5 mg Sublingual Tablet"],
    simple: "The emergency angina tablet that melts under the tongue, instantly widening coronary vessels to relieve chest pain within minutes.",
    uses: ["Angina attack", "Chest pain (known cardiac, as instructed)", "Hospital acute heart failure"],
    how: "At chest pain: sit down, place one tablet under the tongue; may repeat after 5 minutes, max 3 doses. If pain persists beyond 15 minutes — call an ambulance (it may be a heart attack).",
    watch: ["Throbbing headache (common)", "Flushing", "Dizziness"],
    alert: "NEVER combine with sildenafil/tadalafil-type drugs — BP can collapse fatally. Always keep the tablet fresh (replaces every ~6 months).",
    brands: ["Sorbitrate 0.5", "Sorbitrate CT 0.5"],
  },
  {
    salt: "Isosorbide mononitrate", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["10 mg Tablet", "20 mg Tablet", "30 mg ER Tablet"],
    simple: "A long-acting nitrate cousin of nitroglycerin — keeps coronary arteries relaxed through the day to prevent angina attacks rather than treat them.",
    uses: ["Chronic stable angina prevention", "Heart failure support"],
    how: "Morning dose (sometimes with a second midday one) — leaving an overnight nitrate-free window keeps it working; ER forms are once daily.",
    watch: ["Headache in the first week", "Flushing", "Dizziness"],
    alert: "Same absolute ban on sildenafil-type drugs. Low BP with fainting needs dose review.",
    brands: ["Monit 10", "Monit 20", "Monit-GX 30"],
  },
  {
    salt: "Warfarin", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["1 mg Tablet", "2 mg Tablet", "5 mg Tablet"],
    simple: "The classic anticoagulant — blocks vitamin-K clotting factors so blood flows past mechanical valves and clots more slowly. Doses are personalised by INR blood tests.",
    uses: ["Mechanical heart valve", "Atrial fibrillation", "Deep vein thrombosis", "Pulmonary embolism"],
    how: "Same time daily; INR tests keep the dose in the safe band. Leafy greens, alcohol and many drugs swing its effect — consistency and communication matter.",
    watch: ["Bleeding gums", "Bruising", "Nosebleeds"],
    alert: "Blood in urine/stool, severe headache (brain bleed), or a fall with head injury = emergency. Pregnancy is contraindicated.",
    brands: ["Warf 2", "Warf 5", "Uniwarfin 5"],
  },
  {
    salt: "Apixaban", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["2.5 mg Tablet", "5 mg Tablet"],
    simple: "A modern 'NOAC' blood thinner blocking factor Xa — no routine INR tests needed, fewer diet traps than warfarin, standard for atrial fibrillation and DVT today.",
    uses: ["Atrial fibrillation stroke prevention", "DVT", "Pulmonary embolism"],
    how: "5 mg twice daily (2.5 mg twice when criteria say so); take with or without food — but never double up a missed dose.",
    watch: ["Gum bleeding", "Bruising", "Nosebleeds"],
    alert: "Any major unexplained bleeding, or a head injury while on it, is an emergency — tell every doctor you're on a blood thinner.",
    brands: ["Eliquis 5", "Apixabid 5", "Eliquis 2.5"],
  },
  {
    salt: "Rivaroxaban", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["10 mg Tablet", "15 mg Tablet", "20 mg Tablet"],
    simple: "Another factor-Xa blood thinner — once-daily dosing for most uses, widely used for DVT/PE treatment and AF stroke prevention.",
    uses: ["DVT and pulmonary embolism", "Atrial fibrillation", "Post-orthopaedic surgery clots"],
    how: "Dose varies by indication — 20 mg once daily with the evening meal for AF; lower doses for some uses. Never self-adjust.",
    watch: ["Bruising", "Gum or nose bleeding"],
    alert: "Bleeding emergencies are managed exactly like apixaban — inform every clinician; a reversal agent exists in hospitals.",
    brands: ["Xarelto 20", "Rivaflo 20", "Xarelto 15"],
  },
  {
    salt: "Amiodarone", cat: "Heart & Blood Pressure", kind: "Tablet · Injection",
    strengths: ["100 mg Tablet", "200 mg Tablet"],
    simple: "A heavy-duty rhythm stabiliser for dangerous arrhythmias like atrial fibrillation and ventricular tachycardia — powerful, but its long-term side effects need scheduled monitoring.",
    uses: ["Atrial fibrillation", "Ventricular tachycardia", "Rhythm control after cardiac arrest"],
    how: "Usually a loading phase then a low maintenance tablet daily; lung, thyroid and liver tests run periodically.",
    watch: ["Sun sensitivity (use sunscreen)", "Blue-grey skin tint long-term", "Thyroid swings"],
    alert: "Breathlessness or dry cough on it can mean lung injury — report immediately. It interacts with warfarin and digoxin strongly.",
    brands: ["Cordarone 200", "Amiodar 200"],
  },
  {
    salt: "Digoxin", cat: "Heart & Blood Pressure", kind: "Tablet · Injection",
    strengths: ["0.25 mg Tablet"],
    simple: "An old foxglove-derived medicine that strengthens the heart's squeeze and slows atrial fibrillation rates — still valuable in AF with heart failure.",
    uses: ["Atrial fibrillation rate control", "Heart failure (selected)"],
    how: "Once daily, tiny dose, monitored by blood levels and kidney function; potassium balance matters.",
    watch: ["Nausea", "Visual halos/yellow vision", "Slow pulse"],
    alert: "Yellow-tinted vision or halos are classic toxicity signs — report at once. It interacts with amiodarone and many diuretics.",
    brands: ["Lanoxin 0.25", "Digoxin 0.25 Tablet"],
  },
  {
    salt: "Ivabradine", cat: "Heart & Blood Pressure", kind: "Tablet",
    strengths: ["5 mg Tablet", "7.5 mg Tablet"],
    simple: "A pure heart-rate slowener — it works on the SA node's 'tick' without touching BP or contractility, added when rate stays high despite beta-blockers.",
    uses: ["Chronic heart failure with high pulse", "Inappropriate sinus tachycardia"],
    how: "Twice daily with food; doctor targets a resting pulse band (~50–60).",
    watch: ["Visual light trails (transient)", "Slow pulse", "Atrial rhythm changes (monitored)"],
    alert: "Not for atrial fibrillation. Persistent pulse below 50 or new irregular rhythm needs ECG review.",
    brands: ["Ivabrad 5", "Bradia 5", "Ivabid 7.5"],
  },
  {
    salt: "Diltiazem", cat: "Heart & Blood Pressure", kind: "Tablet · Tablet (SR)",
    strengths: ["30 mg Tablet", "60 mg SR Tablet", "90 mg SR Tablet"],
    simple: "A calcium-channel blocker focused on the heart — slows a racing atrial rhythm and eases angina, while also relaxing vessels mildly.",
    uses: ["Angina", "Atrial rate control", "Hypertension", "Anal fissure spasm (topical/low dose)"],
    how: "SR forms once daily; regular forms 2–3 times a day. Combining with beta-blockers needs doctor supervision (pulse can over-slow).",
    watch: ["Slow pulse", "Ankle swelling", "Headache"],
    alert: "Heart block on ECG or fainting spells need review. Avoid grapefruit.",
    brands: ["Dilzem 30", "Diltime SR 90", "Angizem 30"],
  },
  {
    salt: "Trimetazidine", cat: "Heart & Blood Pressure", kind: "Tablet (MR)",
    strengths: ["35 mg MR Tablet"],
    simple: "An anti-anginal that teaches heart cells to burn fuel more efficiently under low oxygen — an add-on when angina persists despite standard drugs.",
    uses: ["Chronic angina (add-on)", "Ischaemic heart disease support"],
    how: "One 35 mg MR tablet twice daily with meals.",
    watch: ["Parkinsonism-like tremor/stiffness (rare, reversible on stopping)"],
    alert: "Any tremor, rigidity or gait change on it means stop-and-review — it is contraindicated in Parkinson's disease.",
    brands: ["Cerez 35 MR", "Flavedon MR 35", "Trimetaz 35"],
  },
];
