/* Anti-fungal, anti-parasitic, anti-viral, anti-malarial — real molecules & Indian brands. */
module.exports = [
  {
    salt: "Fluconazole", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet · Capsule",
    strengths: ["50 mg Tablet", "150 mg Tablet", "200 mg Tablet"],
    simple: "The classic systemic anti-fungal — blocks the fungus from building its cell membrane. One-dose treatments exist for thrush; weeks-long courses for stubborn ones.",
    uses: ["Oral/vaginal thrush", "Systemic fungal infection", "Tinea versicolor", "Fungal UTI"],
    how: "150 mg single dose for thrush; 200 mg daily for weeks in deeper infections, per culture advice.",
    watch: ["Nausea", "Headache", "Stomach discomfort"],
    alert: "It raises levels of many drugs (warfarin, statins, phenytoin) — disclose everything. Liver tests for long courses.",
    brands: ["Forcan 150", "Forcan 200", "Zocon 150"],
  },
  {
    salt: "Itraconazole", cat: "Anti-fungal, Viral & Parasites", kind: "Capsule · Solution",
    strengths: ["100 mg Capsule"],
    simple: "A broader anti-fungal that reaches skin, nails and lungs — treatment for aspergillosis, stubborn nail fungus and histoplasmosis, always timed to stomach acid.",
    uses: ["Nail fungus", "Skin fungal infection", "Aspergillosis", "Sporotrichosis"],
    how: "100–200 mg daily; capsules need FOOD/acid (take right after meals), while the solution goes on an EMPTY stomach — the two forms have opposite rules.",
    watch: ["Nausea", "Rash", "Ankle swelling at higher doses"],
    alert: "Heart-failure patients can't use it. It interacts with a huge drug list (statins, antihistamines) — full disclosure required.",
    brands: ["Itaspor 100", "Itraconz 100", "Sporanox (global)"],
  },
  {
    salt: "Albendazole", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet · Chewable",
    strengths: ["400 mg Tablet"],
    simple: "The deworming tablet — starves intestinal worms (roundworm, hookworm, pinworm) by blocking their glucose uptake. India's school deworming day uses exactly this.",
    uses: ["Intestinal worms", "Pinworm", "Hydatid disease (long course)", "Neurocysticercosis (specialist)"],
    how: "Single 400 mg chewable dose (repeat after 2 weeks for pinworm); fatty food boosts absorption for deep-tissue courses.",
    watch: ["Mild stomach upset", "Dizziness"],
    alert: "Not in early pregnancy. Neurocysticercosis dosing happens only under neurology supervision with steroid cover.",
    brands: ["Zentel 400", "Bandy 400", "Albenza (global)"],
  },
  {
    salt: "Ivermectin", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["6 mg Tablet", "12 mg Tablet"],
    simple: "A parasite nerve-paralysing tablet — kills mites (scabies), lice and strongyloides worms while sparing human nerves (they're protected by the blood-brain barrier).",
    uses: ["Scabies (oral option)", "Strongyloidiasis", "Head lice", "Filariasis programs"],
    how: "200 mcg/kg as a single dose with a full glass of water on an empty stomach; repeated at 1–2 weeks when needed.",
    watch: ["Dizziness", "Nausea"],
    alert: "It is NOT an anti-viral — the COVID claims were false and dangerous. Blood-brain-barrier drugs interactions are screened by the doctor.",
    brands: ["Ivermectol 6", "Ivermectol 12"],
  },
  {
    salt: "Oseltamivir", cat: "Anti-fungal, Viral & Parasites", kind: "Capsule · Suspension",
    strengths: ["30 mg Capsule", "45 mg Capsule", "75 mg Capsule"],
    simple: "An anti-influenza drug — blocks the flu virus's escape enzyme (neuraminidase) so new virus stays stuck inside infected cells. Works best started within 48 hours.",
    uses: ["Influenza A/B treatment", "Flu prophylaxis in outbreaks", "High-risk flu patients"],
    how: "75 mg twice daily for 5 days, ideally within 48 hours of first symptoms.",
    watch: ["Nausea", "Vomiting (take with food)"],
    alert: "It's flu-specific — useless for the common cold or COVID. Confusion/behaviour change (especially children) during treatment is reported promptly.",
    brands: ["Fluvir 45", "Antiflu 75", "Tamiflu (global)"],
  },
  {
    salt: "Acyclovir", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet · Cream · Injection",
    strengths: ["400 mg Tablet", "800 mg Tablet", "5% Cream"],
    simple: "A herpes-virus blocker — the virus's own enzyme turns it into a chain-terminator that stops viral DNA copying. Shortens cold sores, shingles and genital herpes attacks.",
    uses: ["Cold sores", "Shingles", "Genital herpes", "Chickenpox (adults)", "Herpes eye infection (ophthalmic)"],
    how: "400–800 mg five times daily (or as prescribed) with plenty of water for 5–7 days; cream five times daily on lesions.",
    watch: ["Nausea", "Headache", "Kidney crystals if dehydrated — drink well"],
    alert: "Maintain hydration; kidney impairment needs dose reduction. Eye herpes is an ophthalmology emergency, never self-treated.",
    brands: ["Acivir 400 DT", "Acivir 800 DT", "Zovirax Cream (global)"],
  },
  {
    salt: "Valacyclovir", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["500 mg Tablet", "1000 mg Tablet"],
    simple: "Acyclovir's pro-drug upgrade — absorbs far better, so three daily doses replace five, for shingles, cold sores and herpes suppression.",
    uses: ["Shingles", "Genital herpes suppression", "Cold sores"],
    how: "1 g three times daily for shingles (7 days); 500 mg–1 g daily for suppression as prescribed.",
    watch: ["Nausea", "Headache"],
    alert: "Same hydration and kidney-dose rules; immune-compromised patients need higher doses under supervision.",
    brands: ["Valcivir 500", "Valcivir 1000"],
  },
  {
    salt: "Hydroxychloroquine", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["200 mg Tablet", "400 mg Tablet"],
    simple: "An anti-malarial turned autoimmune-modulator — tunes the immune system's over-reactions in lupus and rheumatoid arthritis; also the standard malaria partner drug.",
    uses: ["Lupus (SLE)", "Rheumatoid arthritis", "Malaria (with partner drugs)"],
    how: "200–400 mg daily with food for autoimmunity (months-years); retina is checked yearly because high cumulative doses can damage sight.",
    watch: ["Nausea", "Stomach cramps", "Skin darkening (long-term)"],
    alert: "Yearly eye exams are mandatory on long use. Never used as a COVID cure — no benefit, real heart-rhythm risk.",
    brands: ["HCQS 200", "HCQS 400"],
  },
  {
    salt: "Chloroquine", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet · Syrup",
    strengths: ["250 mg Tablet (150 mg base)", "500 mg Tablet"],
    simple: "The historic anti-malarial — concentrates inside the malaria parasite's food vacuole and poisons it. Resistance limits it in many regions, but it remains useful where parasites are sensitive.",
    uses: ["Sensitive-region malaria", "Amoebic liver abscess partner", "Rheumatoid (historical)"],
    how: "Loading dose then smaller doses over 2–3 days, exactly as the malaria schedule directs.",
    watch: ["Nausea", "Itching (common in Indian patients)", "Headache"],
    alert: "Overdose is rapidly dangerous to the heart — tablets are kept away from children. Retinal checks for long users.",
    brands: ["Lariago 250", "Lariago DS"],
  },
  {
    salt: "Artemether + Lumefantrine", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["80/480 mg Tablet"],
    simple: "The modern ACT malaria cure — artemisinin kills parasites fast while lumefantrine mops up survivors, preventing relapse and resistance.",
    uses: ["Uncomplicated falciparum malaria"],
    how: "Six doses over 3 days (twice daily), taken with fatty food (milk improves absorption dramatically).",
    watch: ["Dizziness", "Palpitations (QT watched)", "Anorexia"],
    alert: "Complete all six doses even after fever breaks. Heart-rhythm drugs are disclosed before starting.",
    brands: ["Lumether Tablet", "Coartem (global)", "Lumerax 80/480 Tablet"],
  },
  {
    salt: "Artesunate", cat: "Anti-fungal, Viral & Parasites", kind: "Injection · Tablet",
    strengths: ["60 mg Injection", "50 mg Tablet"],
    simple: "The fastest malaria killer available — an artemisinin derivative given IV for severe malaria, cutting mortality dramatically versus older drugs.",
    uses: ["Severe falciparum malaria", "Cerebral malaria"],
    how: "Hospital IV schedule followed by oral ACT completion; strictly inpatient.",
    watch: ["Reticulocyte drop (monitored)", "Dizziness"],
    alert: "Severe malaria is an ICU disease — delays in the first IV dose cost lives; treatment starts the moment diagnosis lands.",
    brands: ["Falcigo 60 Injection", "Artesunate 60mg Injection"],
  },
  {
    salt: "Zidovudine + Lamivudine (background ARV)", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["300/150 mg Tablet"],
    simple: "A backbone anti-HIV pair — both block reverse transcriptase so HIV can't copy its RNA into DNA. Always part of a 3-drug combination therapy.",
    uses: ["HIV infection (in combination regimens)", "PMTCT (preventing mother-to-child transfer)"],
    how: "One tablet twice daily as part of the specialist-designed ART regimen; adherence above 95% is the goal.",
    watch: ["Anaemia (zidovudine — blood counts watched)", "Nausea", "Fatigue"],
    alert: "Never skip doses — resistance builds fast. Blood counts are monitored; lactic-acidosis signs (deep fatigue, rapid breathing) are urgent.",
    brands: ["Duovir Tablet", "Combivir (global)"],
  },
  {
    salt: "Tenofovir + Emtricitabine", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["300/200 mg Tablet"],
    simple: "The modern HIV backbone — tenofovir blocks the virus's copying enzyme, emtricitabine reinforces it; kidney and bone markers are the watchpoints.",
    uses: ["HIV (backbone of ART)", "PrEP (pre-exposure prophylaxis)", "Hepatitis B (tenofovir)"],
    how: "One tablet daily; PrEP users test for HIV and kidney function every 3 months.",
    watch: ["Kidney function drift (creatinine monitored)", "Rare bone-density loss"],
    alert: "Hepatitis-B patients must not stop it suddenly — rebound hepatitis is real. Never use PrEP as licence for risk; condoms still rule.",
    brands: ["Tavin-EM Tablet", "Ricovir EM Tablet", "Truvada (global)"],
  },
  {
    salt: "Entecavir", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["0.5 mg Tablet", "1 mg Tablet"],
    simple: "A first-line hepatitis-B suppressor — blocks the virus's polymerase with high barrier to resistance, keeping liver inflammation and cirrhosis risk down.",
    uses: ["Chronic hepatitis B", "HBV-related cirrhosis control"],
    how: "0.5 mg on an empty stomach (2 hours after dinner, before bed); years-long therapy with periodic viral-load tests.",
    watch: ["Headache", "Fatigue"],
    alert: "Stopping abruptly can cause severe hepatitis rebound — only specialist-planned stops. Kidney dosing applies.",
    brands: ["Entecavir 0.5 Tablet", "Baraclude (global)", "Crivax 0.5"],
  },
  {
    salt: "Sofosbuvir + Velpatasvir", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["400/100 mg Tablet"],
    simple: "The hepatitis-C cure — two direct-acting antivirals that stop the virus copying at two different points, curing over 95% of patients in 12 weeks.",
    uses: ["Chronic hepatitis C (all genotypes)", "Post-cirrhosis HCV (with ribavirin in some)"],
    how: "One tablet daily with food for 12 weeks (24 in some cirrhosis cases); viral load confirms cure 12 weeks after finishing.",
    watch: ["Headache", "Tiredness"],
    alert: "Amiodarone causes dangerous heart slowing with it — always disclose. HIV co-infection regimens are reconciled by the specialist.",
    brands: ["Velpanat Tablet", "SoviHep V Tablet", "Epclusa (global)"],
  },
];
