/* Misc hospital molecules — remaining antibiotics, antimalarials, hormones, ICU infusions. */
module.exports = [
  { salt: "Tadalafil", cat: "Urology (Urinary)", kind: "Tablet", strengths: ["5 mg Tablet", "10 mg Tablet"],
    simple: "A longer-lasting PDE5 inhibitor — up to 36 hours of window, and a low-dose daily form for both erectile dysfunction and urinary symptoms of prostate enlargement.",
    uses: ["Erectile dysfunction", "BPH urinary symptoms", "Pulmonary hypertension (specialist)"],
    how: "10–20 mg before need, or 5 mg daily; works only with stimulation.",
    watch: ["Headache", "Back pain", "Flushing", "Muscle aches"],
    alert: "Absolute ban with nitrates (collapse risk). Chest pain during use = emergency, tell the ER what you took.",
    brands: ["Megalis 10", "Tadact 10", "Cialis (global)"] },
  { salt: "Dapoxetine", cat: "Urology (Urinary)", kind: "Tablet",
    strengths: ["30 mg Tablet", "60 mg Tablet"],
    simple: "A short-acting SSRI designed for premature ejaculation — raises serotonin's control over the ejaculatory reflex, taken 1–3 hours before need.",
    uses: ["Premature ejaculation"],
    how: "30 mg with water 1–3 hours before, maximum once in 24 hours; not a daily drug.",
    watch: ["Nausea", "Headache", "Dizziness"],
    alert: "Never with MAO inhibitors or other SSRIs. Sudden fainting on standing — sit down and inform the doctor.",
    brands: ["Duratia 30", "Poxet 30"] },
  { salt: "Desmopressin", cat: "Hormones & Steroids", kind: "Tablet (Melt) · Spray · Injection",
    simple: "A synthetic vasopressin — concentrates urine overnight for diabetes insipidus and bedwetting, and boosts clotting factor in mild haemophilia protocols.",
    uses: ["Diabetes insipidus", "Primary bedwetting", "von Willebrand/haemophilia A procedures (specialist)"],
    how: "Melt tablet under the tongue at bedtime for bedwetting/DI; fluid intake is restricted around doses (water intoxication risk).",
    watch: ["Headache", "Nausea"],
    alert: "Drinking too much around a dose can cause dangerous low sodium — the fluid limits are law.",
    brands: ["Minirin Melt 60", "Desmopressin 0.1mg Tablet"] },
  { salt: "Bromocriptine", cat: "Hormones & Steroids", kind: "Tablet",
    strengths: ["2.5 mg Tablet"],
    simple: "The older dopamine agonist — suppresses prolactin like cabergoline and steadies Parkinson's; slower and side-effect-heavier, but still used.",
    uses: ["Hyperprolactinaemia", "Prolactinoma", "Parkinson's (historical/add-on)"],
    how: "Taken with food at night, titrated slowly over weeks.",
    watch: ["Nausea", "Dizziness on standing", "Sleepiness"],
    alert: "Same impulse-control and sudden-sleep cautions as other dopamine agonists. Report severe headaches or vision changes (tumour growth check).",
    brands: ["Bromocriptine 2.5mg Tablet", "Parlodel (global)"] },
  { salt: "Medroxyprogesterone", cat: "Women's Health", kind: "Tablet · Injection",
    strengths: ["10 mg Tablet", "150 mg Injection"],
    simple: "A progestin that steadies the uterine lining — regulates heavy or irregular periods, and the 3-monthly injection is a long-acting contraceptive.",
    uses: ["Irregular/heavy periods", "Amenorrhoea", "Long-acting contraception (injection)", "Endometrial protection in HRT"],
    how: "10 mg for 5–10 days of the cycle as scheduled; injection every 13 weeks.",
    watch: ["Breast tenderness", "Bloating", "Mood changes", "Bone density loss with long injection use (monitored)"],
    alert: "Breakthrough bleeding that persists needs gynaecological review. Bone-health discussion for long injection users.",
    brands: ["Meprate 10", "Depo-Provera 150 Injection"] },
  { salt: "Norethisterone", cat: "Women's Health", kind: "Tablet",
    strengths: ["5 mg Tablet"],
    simple: "A progestin tablet famous for period control — postpones a period for events, stops prolonged spotting, and steadies the cycle.",
    uses: ["Period postponement", "Heavy irregular bleeding", "Endometriosis support"],
    how: "5 mg two or three times daily — start 3 days before an event to postpone, or as scheduled for bleeding control.",
    watch: ["Breast tenderness", "Nausea", "Mood swings"],
    alert: "Clot-risk symptoms (calf pain, breathlessness) need urgent care. Postponement is occasional use, not a habit.",
    brands: ["Regestrone 5", "Primolut-N 5"] },
  { salt: "Primaquine", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["7.5 mg Tablet", "15 mg Tablet"],
    simple: "The relapse-preventing anti-malarial — clears dormant liver stages of vivax malaria so the fever doesn't return months later. G6PD testing comes first.",
    uses: ["Vivax malaria relapse prevention", "Radical cure with chloroquine"],
    how: "15 mg daily for 14 days after the acute treatment; G6PD deficiency must be excluded (haemolysis risk).",
    watch: ["Stomach upset", "Dark urine (report!)"],
    alert: "In G6PD deficiency it destroys red cells — the test is mandatory before starting.",
    brands: ["Malirid 7.5", "Primaquine 15mg Tablet"] },
  { salt: "Quinine", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet · Injection",
    strengths: ["300 mg Tablet"],
    simple: "The original bark-of-tree anti-malarial — now reserved for severe or resistant malaria when artemisinins aren't available.",
    uses: ["Severe malaria (IV)", "Resistant malaria"],
    how: "Doses under strict monitoring; IV forms are ICU-level therapy with cardiac and sugar monitoring.",
    watch: ["Ringing ears (cinchonism)", "Headache", "Low sugar (monitored)", "Nausea"],
    alert: "Hypoglycaemia during IV therapy is common in severe malaria — glucose is monitored continuously.",
    brands: ["Quinine 300mg Tablet"] },
  { salt: "Praziquantel", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["600 mg Tablet"],
    simple: "The tapeworm and fluke killer — makes parasitic worms' cells leak calcium so they paralysed and are swept out.",
    uses: ["Tapeworm infection", "Schistosomiasis", "Liver flukes", "Neurocysticercosis (specialist)"],
    how: "5–40 mg/kg per protocol, taken with food; neurocysticercosis dosing happens in hospital with steroid cover.",
    watch: ["Dizziness", "Nausea", "Drowsiness"],
    alert: "Don't drive on treatment days. Neuro cases require hospital management — seizures can complicate therapy.",
    brands: ["Biltricide (global)", "Praziquantel 600mg Tablet"] },
  { salt: "Diethylcarbamazine", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["100 mg Tablet"],
    simple: "The filaria drug — kills microfilariae of roundworm parasites that cause elephantiasis; the backbone of mass drug administration programs.",
    uses: ["Lymphatic filariasis", "Tropical pulmonary eosinophilia"],
    how: "6 mg/kg per day courses as scheduled, often after food.",
    watch: ["Fever and rash early (Mazzotti-type reaction)", "Headache"],
    alert: "Heavy parasite loads cause strong reactions — programs pre-treat carefully. Eye involvement needs specialist care.",
    brands: ["Hetrazan 100"] },
  { salt: "Griseofulvin", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["250 mg Tablet", "500 mg Tablet"],
    simple: "An old oral anti-fungal that concentrates in keratin — still valuable for scalp ringworm in children and stubborn nail infections.",
    uses: ["Tinea capitis (scalp ringworm)", "Stubborn skin/nail fungus"],
    how: "Taken WITH fatty food (absorption needs it) for weeks; microsize doses are higher than ultramicrosize.",
    watch: ["Headache", "Nausea", "Sun sensitivity"],
    alert: "It weakens the contraceptive pill. Liver disease and lupus need caution.",
    brands: ["Grisovin FP 250", "Grisovin FP 500"] },
  { salt: "Tenofovir", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["300 mg Tablet"],
    simple: "The hepatitis-B and HIV backbone drug — blocks viral copying enzyme with a high resistance barrier; kidney and bone markers are the watchpoints.",
    uses: ["Chronic hepatitis B", "HIV (in combination)", "PrEP (as Truvada partner)"],
    how: "One tablet daily; never stopped abruptly in hepatitis B (rebound risk).",
    watch: ["Kidney function drift", "Rare bone softening"],
    alert: "Periodic creatinine and phosphate tests are mandatory; dose adjusts in kidney impairment.",
    brands: ["Tavin 300", "Ricovir 300"] },
  { salt: "Bilastine", cat: "Allergy & Respiratory", kind: "Tablet",
    strengths: ["20 mg Tablet"],
    simple: "A modern non-drowsy anti-histamine — clean 24-hour relief for hay fever and hives with the least sedation of its class.",
    uses: ["Allergic rhinitis", "Chronic urticaria"],
    how: "20 mg once daily on an EMPTY stomach (food and fruit juice cut absorption sharply).",
    watch: ["Headache (rare)"],
    alert: "Timing with meals matters — 1 hour before or 2 after food, plain water only.",
    brands: ["Bilastine 20mg Tablet", "Bilaxten 20 (global)"] },
  { salt: "Rupatadine", cat: "Allergy & Respiratory", kind: "Tablet",
    strengths: ["10 mg Tablet"],
    simple: "A dual-action anti-histamine — blocks histamine AND the platelet-activating factor that amplifies allergic inflammation.",
    uses: ["Allergic rhinitis", "Chronic urticaria"],
    how: "10 mg once daily with or without food.",
    watch: ["Drowsiness (mild, some)", "Headache"],
    alert: "Standard allergy-safety: swelling of airway structures is an emergency regardless of tablets.",
    brands: ["Rupatrol 10", "Rupanex 10"] },
  { salt: "AKT-2 Kit (Rifampicin + Isoniazid)", cat: "Antibiotics", kind: "Tablet Kit",
    simple: "India's standard continuation-phase TB kit — rifampicin plus isoniazid in one weekly-thrice blister pack under DOTS supervision.",
    uses: ["Tuberculosis continuation phase"],
    how: "Swallowed on an empty stomach exactly per the DOTS schedule; orange urine is expected.",
    watch: ["Orange body fluids (normal)", "Nausea", "Liver strain (monitored)"],
    alert: "Any yellowing of eyes, vomiting or severe fatigue = stop and liver-test same day.",
    brands: ["AKT-2 Kit"] },
  { salt: "AKT-3 Kit (Isoniazid)", cat: "Antibiotics", kind: "Tablet Kit",
    simple: "The preventive-therapy kit — daily isoniazid (with B6) for contacts and latent TB, supervised across months.",
    uses: ["Latent TB preventive therapy"],
    how: "One kit daily on empty stomach for the prescribed months, with pyridoxine.",
    watch: ["Tingling feet (B6 prevents)", "Appetite change"],
    alert: "Yellow eyes or dark urine needs urgent liver tests.",
    brands: ["AKT-3 Kit"] },
  { salt: "AKT-4 Kit (4-drug TB)", cat: "Antibiotics", kind: "Tablet Kit",
    simple: "The intensive-phase TB kit — rifampicin, isoniazid, pyrazinamide and ethambutol together, the four-drug opening attack on TB.",
    uses: ["Tuberculosis intensive phase"],
    how: "Daily on empty stomach per DOTS; vision checks for ethambutol, liver tests throughout.",
    watch: ["Orange urine (normal)", "Joint aches", "Vision colour changes (report!)"],
    alert: "Any vision change or jaundice signs get same-day review.",
    brands: ["AKT-4 Kit"] },
  { salt: "Meloxicam", cat: "Pain & Fever", kind: "Tablet",
    strengths: ["7.5 mg Tablet", "15 mg Tablet"],
    simple: "A COX-2-leaning NSAID for arthritis — once-daily dosing with a gentler stomach profile than older drugs.",
    uses: ["Osteoarthritis", "Rheumatoid arthritis", "Ankylosing spondylitis"],
    how: "7.5–15 mg once daily with food.",
    watch: ["Indigestion", "Dizziness"],
    alert: "Kidney, ulcer and heart cautions as for all NSAIDs. Black stools are urgent.",
    brands: ["Meloxicam 15mg Tablet", "Mobic (global)"] },
  { salt: "Lornoxicam", cat: "Pain & Fever", kind: "Tablet",
    strengths: ["8 mg Tablet"],
    simple: "A fast-onset oxicam NSAID for short-course pain — dental and post-operative pain especially.",
    uses: ["Post-operative pain", "Dental pain", "Arthritis flares"],
    how: "8 mg once or twice daily with food, short courses.",
    watch: ["Acidity", "Nausea"],
    alert: "Standard NSAID cautions; ulcers and kidney disease avoid.",
    brands: ["Xefo 8"] },
  { salt: "Indomethacin", cat: "Pain & Fever", kind: "Capsule",
    strengths: ["25 mg Capsule"],
    simple: "A strong old NSAID with special jobs — gout attacks, ankylosing spondylitis stiff nights, and closing a heart defect (PDA) in newborn ICUs.",
    uses: ["Gout attack", "Ankylosing spondylitis", "Neonatal PDA closure (hospital)", "Bursitis"],
    how: "25 mg two or three times daily with food; neonatal use is NICU-protocol.",
    watch: ["Headache", "Acidity", "Dizziness"],
    alert: "Among the harshest NSAIDs on stomach and kidney — short supervised courses only.",
    brands: ["Indocap 25"] },
  { salt: "Nabumetone", cat: "Pain & Fever", kind: "Tablet",
    strengths: ["500 mg Tablet"],
    simple: "A pro-drug NSAID designed to spare the stomach — converts to its active form after absorption, away from the gut lining.",
    uses: ["Osteoarthritis", "Rheumatoid arthritis"],
    how: "500–1000 mg once or twice daily with food.",
    watch: ["Headache", "Dizziness"],
    alert: "Same NSAID kidney/heart cautions apply despite the gentler stomach design.",
    brands: ["Nabumetone 500mg Tablet"] },
  { salt: "Ketoprofen", cat: "Pain & Fever", kind: "Capsule · Gel",
    strengths: ["50 mg Capsule", "100 mg Capsule", "2.5% Gel"],
    simple: "A standard NSAID in capsule and gel forms — arthritis and injury pain, with the topical gel sparing the stomach entirely.",
    uses: ["Arthritis", "Tendonitis", "Sports injury (gel)"],
    how: "50–100 mg up to three times daily with food; gel rubbed 2–3 times daily.",
    watch: ["Acidity", "Skin warmth with gel"],
    alert: "NSAID cautions for the capsules; broken skin never gets gel.",
    brands: ["Ketoprofen 50mg Capsule"] },
  { salt: "Mefloquine", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    strengths: ["250 mg Tablet"],
    simple: "A weekly anti-malarial for resistant regions and traveller prophylaxis — effective but with famous vivid-dream and mood side effects.",
    uses: ["Malaria prophylaxis (resistant zones)", "Malaria treatment (selected)"],
    how: "Weekly dose for prophylaxis, started 2–3 weeks before travel; psychiatric history is screened first.",
    watch: ["Vivid dreams", "Dizziness", "Mood changes", "Sleep disturbance"],
    alert: "Anxiety, depression or psychosis on it means stop and consult — neuropsychiatric effects are real.",
    brands: ["Mefloquine 250mg Tablet", "Lariam (global)"] },
  { salt: "Pyrimethamine + Sulfadoxine", cat: "Anti-fungal, Viral & Parasites", kind: "Tablet",
    simple: "A two-hit anti-malarial FDC — blocks two folate steps in the parasite; reserved for resistance patterns and toxoplasmosis protocols.",
    uses: ["Resistant falciparum malaria (selected)", "Toxoplasmosis (with folinic acid)"],
    how: "Per malaria protocol; folinic acid cover in toxoplasmosis therapy.",
    watch: ["Rash (sulfa)", "Mouth ulcers", "Low counts"],
    alert: "Blistering rash or mouth ulcers means stop immediately — blood counts checked.",
    brands: ["Pyrimethamine+Sulfadoxine Tablet", "Fansidar (global)"] },
  { salt: "Vancomycin", cat: "Antibiotics", kind: "Injection · Capsule",
    strengths: ["500 mg Injection", "125 mg Capsule"],
    simple: "The gram-positive heavyweight — IV form conquers MRSA bloodstream and bone infections; the oral capsule treats C. difficile colitis locally.",
    uses: ["MRSA infection", "Resistant gram-positive sepsis", "C. difficile colitis (oral)"],
    how: "IV doses guided by trough blood levels and kidney function; oral capsules for gut-only infection.",
    watch: ["Infusion flushing ('red man' — slow the drip)", "Kidney function drift", "Low counts (rare)"],
    alert: "Fast infusion causes flushing and BP drop — always slow. Trough monitoring is standard.",
    brands: ["Vancomycin 500mg Injection"] },
  { salt: "Colistin", cat: "Antibiotics", kind: "Injection",
    strengths: ["4.5 MIU Injection"],
    simple: "The last-resort ICU antibiotic — a membrane-puncturing polymyxin for bacteria that resist everything else, given under close kidney watch.",
    uses: ["Extensively drug-resistant infections", "Ventilator pneumonia (XDR)", "ICU sepsis (resistant)"],
    how: "IV by weight-based protocols with daily kidney monitoring; inhaled forms exist for lung infection.",
    watch: ["Kidney injury (expected risk, monitored)", "Numbness/tingling", "Breathing muscle weakness (rare)"],
    alert: "It is genuinely last-line — preserving its power means it's never used casually.",
    brands: ["Xist 4.5MIU", "Colistin 4.5MIU Injection"] },
  { salt: "Fosfomycin", cat: "Antibiotics", kind: "Sachet",
    strengths: ["3 g Sachet"],
    simple: "A one-dose urinary antibiotic — a single sachet dissolved in water clears simple bladder infections, a rarity in the antibiotic world.",
    uses: ["Simple cystitis (single dose)", "Pregnancy UTI (as advised)"],
    how: "One 3 g sachet in water, dissolved and drunk at bedtime after emptying the bladder.",
    watch: ["Diarrhoea", "Headache"],
    alert: "Fever or flank pain means kidney involvement — needs longer treatment, not one sachet.",
    brands: ["Monurol (global)", "Fosfomycin 3g Sachet"] },
  { salt: "Cefotaxime", cat: "Antibiotics", kind: "Injection",
    strengths: ["1 g Injection"],
    simple: "A third-generation cephalosporin injectable — a hospital staple for meningitis, sepsis and urinary sepsis before resistance patterns redirect therapy.",
    uses: ["Meningitis", "Sepsis", "Urinary sepsis", "Typhoid (IV)"],
    how: "IV/IM every 6–12 hours by staff, dose adjusted in kidney failure.",
    watch: ["Rash", "Diarrhoea", "Injection-site pain"],
    alert: "Allergy disclosure is essential; severe reactions are managed immediately in hospital settings.",
    brands: ["Taxim 1g Injection"] },
  { salt: "Cefoperazone + Sulbactam", cat: "Antibiotics", kind: "Injection",
    strengths: ["1.5 g Injection"],
    simple: "A cephalosporin with a resistance-shield — the ICU workhorse for abdominal and hospital-acquired infections including gallbladder routes.",
    uses: ["Hospital pneumonia", "Biliary/abdominal sepsis", "ICU resistant infections"],
    how: "IV every 12 hours by staff; liver and kidney status shapes dosing.",
    watch: ["Diarrhoea", "Vitamin K effect (bleeding tendency on long courses)"],
    alert: "Alcohol during and after therapy causes disulfiram-like reactions — no drinking on therapy.",
    brands: ["Magnex Forte 1.5g Injection"] },
  { salt: "Ampicillin + Cloxacillin", cat: "Antibiotics", kind: "Capsule · Injection",
    strengths: ["500 mg Capsule"],
    simple: "A broad penicillin plus a staph-proof penicillin — the classic pair for mixed skin and wound infections.",
    uses: ["Skin infection", "Wound infection", "Post-surgical infection"],
    how: "500 mg every 6 hours as prescribed, course completed.",
    watch: ["Rash", "Diarrhoea"],
    alert: "Penicillin allergy history changes everything — disclose before any dose.",
    brands: ["Ampilox 500"] },
  { salt: "Cefadroxil", cat: "Antibiotics", kind: "Capsule",
    strengths: ["500 mg Capsule"],
    simple: "A first-generation cephalosporin with twice-daily convenience — skin, throat and urinary infections in outpatient care.",
    uses: ["Skin infection", "Throat infection", "Urinary infection"],
    how: "500 mg once or twice daily, full course.",
    watch: ["Nausea", "Rash"],
    alert: "Cephalosporin/penicillin allergy disclosure applies.",
    brands: ["Cefadrox 500"] },
  { salt: "Meropenem", cat: "Antibiotics", kind: "Injection",
    strengths: ["1 g Injection"],
    simple: "A carbapenem — one of the broadest hospital antibiotics, reserved for severe sepsis and resistant gram-negative infections.",
    uses: ["Severe sepsis", "Hospital pneumonia", "Complicated abdominal infection", "Febrile neutropenia"],
    how: "IV every 8 hours by weight and kidney-adjusted protocols.",
    watch: ["Diarrhoea", "Rash", "Low counts (rare)"],
    alert: "Antibiotic stewardship protects carbapenems — they're held back for when nothing else works.",
    brands: ["Meropenem 1g Injection"] },
  { salt: "Verapamil", cat: "Heart & Blood Pressure", kind: "Tablet · Tablet (SR)",
    strengths: ["40 mg Tablet", "120 mg SR Tablet"],
    simple: "A heart-focused calcium blocker — slows conduction through the AV node for rhythm control and eases angina; the classic option for cluster headaches too.",
    uses: ["Supraventricular tachycardia", "Angina", "Hypertension", "Cluster headache prevention"],
    how: "40 mg three times daily or SR once daily; constipation is the classic complaint.",
    watch: ["Constipation", "Slow pulse", "Gum swelling"],
    alert: "Dangerous with beta-blockers (double-slowing) — only combined under supervision. Heart failure worsens with it.",
    brands: ["Calaptin 40", "Verapamil SR 120 Tablet"] },
  { salt: "Venlafaxine", cat: "Brain & Mind", kind: "Capsule (XR)",
    strengths: ["37.5 mg Capsule", "75 mg Capsule"],
    simple: "An SNRI antidepressant with dose-dependent reach — serotonin effects at low doses, noradrenaline added higher; useful for anxiety and severe depression.",
    uses: ["Depression", "Generalised anxiety", "Panic disorder"],
    how: "Morning XR capsule, titrated slowly; blood pressure is monitored at higher doses.",
    watch: ["Nausea", "Dry mouth", "Sweating", "BP rise (higher doses)"],
    alert: "Discontinuation dizziness is famously rough — taper slowly. Uncontrolled hypertension needs stabilising first.",
    brands: ["Venlor XR 75", "Veniz XR 37.5"] },
  { salt: "Prochlorperazine", cat: "Brain & Mind", kind: "Tablet (MD) · Injection",
    strengths: ["5 mg Tablet (MD)"],
    simple: "A dopamine-blocking anti-nausea drug — kills severe vomiting and vertigo (especially migraine and inner-ear), with sedation as the trade-off.",
    uses: ["Severe nausea/vomiting", "Vertigo", "Migraine vomiting"],
    how: "5 mg MD tablet up to three times daily; injections are hospital-only.",
    watch: ["Drowsiness", "Restlessness (akathisia)", "Stiffness"],
    alert: "Movement side effects are common — any stiffness or restlessness means dose review. Elderly dementia patients avoid it.",
    brands: ["Stemetil MD 5"] },
  { salt: "Esmolol", cat: "Emergency & ICU", kind: "Injection (IV)",
    strengths: ["100 mg Injection"],
    simple: "An ultra-short beta-blocker infusion — slows a racing heart within minutes and wears off within minutes of stopping, ideal in ICU rhythm crises.",
    uses: ["Supraventricular tachycardia", "Post-operative hypertension", "Aortic dissection rate control"],
    how: "Loading bolus then pump infusion, titrated to heart rate by staff.",
    watch: ["Slow pulse", "Low BP"],
    alert: "ICU-only infusion with continuous monitoring; asthma patients need caution like all beta-blockers.",
    brands: ["Esmolol 100mg Injection"] },
  { salt: "Calcium gluconate", cat: "Emergency & ICU", kind: "Injection",
    strengths: ["10% Injection"],
    simple: "The emergency calcium — stabilises heart muscle in dangerous high potassium, treats low-calcium tetany, and antidotes magnesium overdose.",
    uses: ["Hyperkalaemia heart protection", "Hypocalcaemia tetany", "Magnesium toxicity antidote"],
    how: "Slow IV by staff with ECG monitoring; rapid push causes arrhythmia.",
    watch: ["Vein irritation", "Bradycardia if too fast"],
    alert: "Never mixed with bicarbonate in the same line (precipitates). Digitalis patients get extra caution.",
    brands: ["Calcium Gluconate 10% Injection"] },
  { salt: "Sodium bicarbonate", cat: "Emergency & ICU", kind: "Injection",
    strengths: ["7.5% Injection"],
    simple: "The pH rescue — corrects dangerous acid build-up in cardiac arrest protocols, severe kidney acidosis and some poisonings.",
    uses: ["Metabolic acidosis", "Cardiac arrest (selected protocols)", "TCA overdose alkalinisation"],
    how: "IV infusion by staff with blood-gas guidance; over-correction is its own hazard.",
    watch: ["Low potassium shifts", "Fluid/sodium load"],
    alert: "Not a routine crash-cart reflex — modern ACLS uses it selectively.",
    brands: ["Sodium Bicarbonate 7.5% Injection"] },
  { salt: "Hypertonic saline", cat: "Emergency & ICU", kind: "Injection (IV)",
    strengths: ["3% Infusion"],
    simple: "Salt water stronger than blood — pulls brain water outward by osmosis in raised-pressure emergencies and corrects profound low sodium under careful pacing.",
    uses: ["Raised intracranial pressure", "Severe symptomatic hyponatraemia"],
    how: "ICU infusion with frequent sodium checks — too-fast correction injures nerves (osmotic demyelination).",
    watch: ["Sodium over-correction", "Vein irritation"],
    alert: "Correction speed is a medical law — this is never a ward-level infusion.",
    brands: ["3% Sodium Chloride Infusion"] },
  { salt: "Potassium chloride", cat: "Emergency & ICU", kind: "Injection · Sachet",
    strengths: ["15% Injection", "600 mg Sachet"],
    simple: "The potassium replenisher — corrects the dangerous-low potassium that causes weakness and arrhythmias, given slowly and always diluted.",
    uses: ["Hypokalaemia", "Diuretic-related potassium loss", "Arrhythmia prevention"],
    how: "IV never pushed — slow dilute infusion by staff; oral sachets/solutions with plenty of water.",
    watch: ["Stomach irritation (oral)", "Vein pain (IV)"],
    alert: "Rapid potassium infusion stops the heart — the dilution and pump-rate rules are absolute.",
    brands: ["Potassium Chloride 600mg Sachet", "K-Sol Syrup"] },
  { salt: "Vitamin K1", cat: "Vitamins & Supplements", kind: "Injection · Tablet",
    strengths: ["10 mg Injection"],
    simple: "The clotting vitamin — reverses warfarin effect and treats newborn haemorrhagic disease; the hospital antidote to over-anticoagulation.",
    uses: ["Warfarin reversal", "Vitamin K deficiency bleeding", "Newborn prophylaxis"],
    how: "IV (slow, diluted) or oral per INR protocol; newborns get a standard IM dose at birth.",
    watch: ["Flushing/reaction risk with rapid IV"],
    alert: "It takes hours to work — severe bleeds need clotting factors alongside, not vitamin K alone.",
    brands: ["Vitamin K 10mg Injection", "Konakion (global)"] },
  { salt: "Omega-3 fatty acids", cat: "Vitamins & Supplements", kind: "Capsule",
    strengths: ["1000 mg Capsule"],
    simple: "Fish-oil triglyceride support — modest triglyceride lowering and heart-health support as an adjunct, not a replacement for statins or lifestyle change.",
    uses: ["High triglycerides (adjunct)", "Cardiovascular support", "Dry-eye support"],
    how: "1–4 g daily with meals per product strength and indication.",
    watch: ["Fishy aftertaste", "Loose stools at high doses"],
    alert: "Bleeding-time effects at very high doses are discussed with doctors on blood thinners.",
    brands: ["Omega-3 1000mg Capsule", "Seven Seas Cod Liver Oil Capsule"] },
  { salt: "Fusidic acid", cat: "Skin, Eye & ENT", kind: "Cream · Ointment",
    strengths: ["2% Cream"],
    simple: "A staph-specialist antibiotic cream — pierces impetigo, infected eczema and staph boils with a sterol-mimicking trick bacteria can't easily dodge.",
    uses: ["Impetigo", "Infected eczema", "Staph skin infection"],
    how: "Thin layer two or three times daily for 1–2 weeks.",
    watch: ["Mild irritation"],
    alert: "Resistance develops with underuse or overuse — finish the course, never share tubes.",
    brands: ["Fucidin Cream", "Fucidin H (with hydrocortisone)"] },
  { salt: "Moxifloxacin + Dexamethasone", cat: "Skin, Eye & ENT", kind: "Eye Drops",
    simple: "Antibiotic plus steroid eye drops — fights infection while calming inflammation in post-operative and mixed eye conditions, strictly under eye-doctor supervision.",
    uses: ["Post-eye-surgery inflammation", "Mixed infection-inflammation conjunctivitis"],
    how: "One drop 3–4 times daily for the prescribed week; bottle never shared.",
    watch: ["Transient blur", "Steroid effects on eye pressure with long use"],
    alert: "Steroid eye drops can worsen herpetic eye disease and raise pressure — ophthalmologist supervision is non-negotiable.",
    brands: ["Moxifloxacin + Dexamethasone Eye Drops", "Vigadexa (global)"] },
  { salt: "Latanoprost + Timolol", cat: "Skin, Eye & ENT", kind: "Eye Drops",
    strengths: ["0.005/5 mg/ml Eye Drops"],
    simple: "Prostaglandin plus beta-blocker in one evening drop — outflow increased and fluid production reduced for stronger glaucoma control in a single bottle.",
    uses: ["Glaucoma needing two-drug control"],
    how: "One drop at bedtime; inner-corner press after instillation.",
    watch: ["Lash/iris darkening", "Stinging", "Slow pulse (absorption)"],
    alert: "Asthma and heart-block cautions apply. Eye pain or vision change is same-day review.",
    brands: ["Xalacom Eye Drops", "Latoprost-T Eye Drops"] },
  { salt: "Saroglitazar", cat: "Diabetes", kind: "Tablet",
    strengths: ["4 mg Tablet"],
    simple: "An India-born dual PPAR agonist — improves both sugar and triglycerides in diabetic dyslipidaemia, unique to the Indian market.",
    uses: ["Type 2 diabetes with high triglycerides", "Diabetic dyslipidaemia"],
    how: "4 mg once daily before breakfast; liver tests are monitored.",
    watch: ["Mild weight change", "Liver enzyme rise (monitored)"],
    alert: "Not for heart failure or significant liver disease. Long-term safety data is thinner than older classes — periodic review matters.",
    brands: ["Lipaglyn 4"] },
];
