/* Pain, fever, inflammation, muscle relaxants — real molecules & Indian brands. */
module.exports = [
  {
    salt: "Paracetamol", cat: "Pain & Fever", kind: "Tablet · Syrup · Drops · Injection",
    strengths: ["500 mg Tablet", "650 mg Tablet", "125 mg/5 ml Syrup", "100 mg Drops"],
    simple: "The most common fever-and-pain medicine. It works on the brain's heat centre to bring a temperature down, and dulls pain signals so aches feel less. It does not reduce swelling.",
    uses: ["Fever", "Headache", "Body ache", "Toothache", "Pain after surgery or vaccination"],
    how: "Adults usually take 500–650 mg with water every 6 hours, after food. Never take more than 3 grams (about 4 tablets) in a day, and avoid alcohol with it — extra doses harm the liver.",
    watch: ["Usually very gentle", "Rarely nausea or a skin rash"],
    alert: "See a doctor if fever lasts beyond 3 days, or if you notice yellow eyes/skin, dark urine or severe tiredness — these can signal liver trouble.",
    brands: ["Dolo 650", "Dolo 500", "Calpol 500", "Calpol Syrup", "Crocin Advance 500", "Crocin Pain Relief", "Pacimol 650", "Metacin 500", "Paracip 650", "Pyrigesic 500"],
  },
  {
    salt: "Ibuprofen", cat: "Pain & Fever", kind: "Tablet · Syrup · Gel",
    strengths: ["200 mg Tablet", "400 mg Tablet", "100 mg/5 ml Suspension"],
    simple: "A painkiller of the NSAID family that reduces pain, fever AND swelling. It blocks body chemicals (prostaglandins) that cause inflammation at an injury site.",
    uses: ["Period pain", "Sprains and muscle injury", "Joint pain with swelling", "Dental pain", "Fever"],
    how: "Take 200–400 mg every 6–8 hours, always after food or with milk — on an empty stomach it can irritate the stomach lining. People with kidney disease, ulcers or dengue should avoid it.",
    watch: ["Stomach burning or acidity", "Nausea", "Fluid puffiness in some people"],
    alert: "Stop and see a doctor if you pass black stools, vomit blood, or have severe stomach pain — signs of stomach bleeding.",
    brands: ["Brufen 400", "Brufen 200", "Ibugesic Syrup", "Ibuvon 400"],
  },
  {
    salt: "Diclofenac", cat: "Pain & Fever", kind: "Tablet · Gel · Injection",
    strengths: ["50 mg Tablet", "100 mg SR Tablet", "1% Gel", "75 mg Injection"],
    simple: "A strong anti-inflammatory painkiller for injuries, arthritis and back pain. Like ibuprofen it blocks prostaglandins, the chemicals that make tissue swollen and painful.",
    uses: ["Back and neck pain", "Arthritis", "Sprains", "Post-operative pain", "Sciatica"],
    how: "Tablets are taken after food (50 mg up to three times a day); the gel is rubbed on the painful area 3–4 times a day. The injection is given by hospital staff only.",
    watch: ["Acidity and heartburn", "Stomach pain", "Raised blood pressure with long use"],
    alert: "Long use can harm kidneys and stomach — never self-take for more than 5 days. Black stools or vomiting blood means urgent medical care.",
    brands: ["Voveran 50", "Voveran SR 100", "Voveran Gel", "Volini Gel", "Dicloran 50"],
  },
  {
    salt: "Aceclofenac", cat: "Pain & Fever", kind: "Tablet",
    strengths: ["100 mg Tablet"],
    simple: "A modern cousin of diclofenac used for arthritis and joint pain. It calms inflammation with, for many people, slightly gentler effects on the stomach than older NSAIDs.",
    uses: ["Osteoarthritis", "Rheumatoid arthritis", "Lower back pain", "Frozen shoulder"],
    how: "Usually 100 mg twice a day after food. Take the smallest dose that works, for the shortest time.",
    watch: ["Indigestion", "Dizziness in some people"],
    alert: "Avoid in active stomach ulcers, severe heart failure or kidney disease; report black stools immediately.",
    brands: ["Zerodol 100", "Hifenac 100", "Aceclo 100"],
  },
  {
    salt: "Naproxen", cat: "Pain & Fever", kind: "Tablet",
    strengths: ["250 mg Tablet", "500 mg Tablet"],
    simple: "A long-acting NSAID painkiller — one dose works for about 12 hours, so it is often chosen for period cramps and arthritis that trouble you through the day.",
    uses: ["Period cramps", "Arthritis", "Gout attacks", "Muscle injuries", "Migraine"],
    how: "250–500 mg twice a day with food. For period pain it is often started at the first sign of cramps.",
    watch: ["Heartburn", "Stomach discomfort", "Ring in the ears at high doses"],
    alert: "Avoid with stomach ulcers, heart failure or kidney problems. Report black stools or breathlessness.",
    brands: ["Naprosyn 250", "Naprosyn 500", "Naxdom 500"],
  },
  {
    salt: "Mefenamic acid", cat: "Pain & Fever", kind: "Tablet · Suspension",
    strengths: ["250 mg Tablet", "500 mg Tablet", "50 mg/5 ml Suspension"],
    simple: "An NSAID painkiller especially trusted for period pain and childhood fevers. It works at the site of pain and also directly lowers fever.",
    uses: ["Painful periods", "Childhood fever", "Toothache", "Muscle pain"],
    how: "500 mg up to three times a day after food for adults; the syrup dose for children is by weight. Best not used for more than 7 days at a stretch.",
    watch: ["Loose stools", "Stomach discomfort"],
    alert: "Avoid in the last 3 months of pregnancy and in kidney disease. Very severe cramps that don't settle need a gynaecologist's check.",
    brands: ["Meftal 250", "Meftal Forte 500", "Meftal P Suspension"],
  },
  {
    salt: "Ketorolac", cat: "Pain & Fever", kind: "Tablet (DT) · Injection",
    strengths: ["10 mg Tablet (DT)"],
    simple: "A powerful short-course painkiller, close to morphine in punch, used for severe pain like kidney stones or after operations. It is only for a few days, never long-term.",
    uses: ["Kidney stone pain", "Post-surgery pain", "Severe injury pain"],
    how: "10 mg every 4–6 hours, with food, for at most 5 days in total. Hospital injections are given into muscle or vein.",
    watch: ["Stomach pain", "Drowsiness", "Dizziness"],
    alert: "It must never be used with other NSAIDs or before major surgery. Bleeding, black stools or reduced urination need a doctor right away.",
    brands: ["Ketorol DT 10"],
  },
  {
    salt: "Etoricoxib", cat: "Pain & Fever", kind: "Tablet",
    strengths: ["60 mg Tablet", "90 mg Tablet", "120 mg Tablet"],
    simple: "A selective anti-inflammatory painkiller designed to spare the stomach — it blocks the inflammation chemical (COX-2) while mostly leaving the stomach-protecting one (COX-1) alone.",
    uses: ["Arthritis", "Gout attacks", "Back pain", "Dental pain", "Ankylosing spondylitis"],
    how: "60–120 mg once a day, with or without food. Gout flares usually take 90–120 mg briefly.",
    watch: ["Ankle swelling", "Headache", "Raised blood pressure with long use"],
    alert: "Not for people with uncontrolled high BP, heart disease or active ulcers. Chest pain or breathlessness while on it needs urgent care.",
    brands: ["Etoshine 60", "Etoshine 90", "Nucoxia 90", "Etova 90"],
  },
  {
    salt: "Celecoxib", cat: "Pain & Fever", kind: "Capsule",
    strengths: ["100 mg Capsule", "200 mg Capsule"],
    simple: "Another stomach-friendlier COX-2 anti-inflammatory, used for arthritis pain that swells and stiffens joints. Taken as a capsule once or twice a day.",
    uses: ["Osteoarthritis", "Rheumatoid arthritis", "Period pain", "Muscle injuries"],
    how: "100–200 mg once or twice daily with food. Sulfa-allergic people should avoid it.",
    watch: ["Indigestion", "Headache", "Swelling of feet"],
    alert: "Avoid after bypass heart surgery and in serious heart or kidney disease. Report chest pain or sudden weakness.",
    brands: ["Celact 100", "Celact 200", "Cobix 100"],
  },
  {
    salt: "Aspirin", cat: "Pain & Fever", kind: "Tablet",
    strengths: ["325 mg Tablet"],
    simple: "The classic pain and fever tablet, and the same family that thins blood. For pain it is used occasionally; the low 75–150 mg dose (see Heart section) is a daily heart medicine.",
    uses: ["Headache", "Fever", "Body pain", "Dental pain"],
    how: "One 325 mg tablet with food and plenty of water, up to 3–4 times a day at most. Never give to children with fever — it can cause Reye's syndrome, a rare liver-brain illness.",
    watch: ["Stomach irritation", "Easy bruising"],
    alert: "Avoid in dengue, ulcers, bleeding disorders and before surgery. Ringing ears or black stools mean stop and call a doctor.",
    brands: ["Disprin 325"],
  },
  {
    salt: "Nimesulide", cat: "Pain & Fever", kind: "Tablet · Suspension",
    strengths: ["100 mg Tablet", "50 mg/5 ml Suspension"],
    simple: "A fast-acting anti-inflammatory painkiller common in India for short-term pain. It is effective but has strict rules: short courses only, and never in children under 12.",
    uses: ["Short-term pain relief", "Period pain", "Sports injury pain"],
    how: "100 mg twice a day after food, for a maximum of 5–7 days. It is banned for children in many countries and should never be used long-term.",
    watch: ["Stomach discomfort", "Nausea"],
    alert: "Yellow urine, dark stools or rash means stop immediately and see a doctor — it can, rarely, injure the liver.",
    brands: ["Nise 100", "Nimulid 100", "Nicip 100"],
  },
  {
    salt: "Piroxicam", cat: "Pain & Fever", kind: "Capsule · Gel",
    strengths: ["20 mg Capsule", "0.5% Gel"],
    simple: "A once-a-day NSAID for arthritis and stiff joints, also available as a gel to rub over aching knees or shoulders.",
    uses: ["Arthritis", "Frozen shoulder", "Muscle stiffness", "Back pain"],
    how: "One 20 mg capsule daily with food, or gel rubbed 2–3 times a day. Long-term use needs monitoring.",
    watch: ["Heartburn", "Stomach ache"],
    alert: "Higher stomach-bleeding risk than many NSAIDs in the elderly — black stools mean stop and seek care.",
    brands: ["Dolonex 20", "Dolonex Gel"],
  },
  {
    salt: "Tramadol", cat: "Pain & Fever", kind: "Capsule · Tablet (SR) · Injection",
    strengths: ["50 mg Capsule", "100 mg SR Tablet"],
    simple: "An opioid-family painkiller for moderate to severe pain that ordinary painkillers cannot touch. It works on the brain's pain pathways and also lifts pain tolerance.",
    uses: ["Severe back pain", "Pain after surgery", "Nerve pain", "Cancer pain"],
    how: "50–100 mg every 6–8 hours as prescribed. It can cause sleepiness — do not drive — and it is habit-forming with long use, so it is always time-limited.",
    watch: ["Drowsiness", "Nausea", "Constipation", "Dizziness"],
    alert: "Never mix with alcohol or sleeping tablets. Confusion, very slow breathing or seizures need emergency care.",
    brands: ["Contramal 50", "Contramal 100", "Tramazac 100 SR"],
  },
  {
    salt: "Tapentadol", cat: "Pain & Fever", kind: "Tablet · Tablet (SR)",
    strengths: ["50 mg Tablet", "100 mg SR Tablet"],
    simple: "A newer opioid-family painkiller for strong pain, acting on pain signals in the brain and spinal cord. Reserved for when milder painkillers have failed.",
    uses: ["Severe chronic back pain", "Post-operative pain", "Cancer pain"],
    how: "50–100 mg as prescribed, usually twice a day for the SR form. Sleepiness is common — driving is unsafe — and long use can cause dependence.",
    watch: ["Sleepiness", "Nausea", "Constipation"],
    alert: "Do not combine with alcohol or sedatives. Very slow breathing is an emergency.",
    brands: ["Tapenta 50", "Tapenta 100"],
  },
  {
    salt: "Thiocolchicoside", cat: "Pain & Fever", kind: "Capsule · Tablet · Injection",
    strengths: ["4 mg Capsule", "8 mg Tablet"],
    simple: "A muscle relaxant — it loosens muscles that have gone into painful spasm after a strain, so the underlying painkiller can work better.",
    uses: ["Painful muscle spasm", "Stiff neck", "Back strain", "Tetany-related spasm"],
    how: "4–8 mg two to three times a day for a few days, usually alongside a painkiller. Can cause loose stools and sleepiness.",
    watch: ["Diarrhoea", "Drowsiness"],
    alert: "Avoid in pregnancy. If muscle weakness or very loose stools appear, stop and inform your doctor.",
    brands: ["Myoril 4", "Thiospas 4", "Myoril 8"],
  },
  {
    salt: "Tizanidine", cat: "Pain & Fever", kind: "Tablet",
    strengths: ["2 mg Tablet"],
    simple: "A muscle relaxant that works through the spinal cord to calm over-tight muscles — used after injuries and in neurological conditions with stiffness.",
    uses: ["Muscle spasm", "Spasticity in MS or stroke", "Neck strain"],
    how: "2 mg at bedtime or up to three times a day as prescribed; it lowers blood pressure slightly, so stand up slowly.",
    watch: ["Drowsiness", "Dry mouth", "Low blood pressure on standing"],
    alert: "Never stop it suddenly after long use. Yellowing of eyes or extreme fatigue needs a liver check.",
    brands: ["Sirdalud 2", "Tizan 2"],
  },
  {
    salt: "Methyl salicylate (topical rub)", cat: "Pain & Fever", kind: "Balm · Ointment",
    simple: "A wintergreen-scented rub that creates warmth on the skin and distracts pain nerves — the classic Indian pain balm for sore muscles, stiff neck and headaches at the temples.",
    uses: ["Sore muscles", "Stiff neck", "Joint ache", "Tension headache (applied to temples)"],
    how: "Massage a small amount over the painful area 2–3 times a day. Never apply to broken skin, and never swallow — it is poisonous by mouth.",
    watch: ["Skin warmth or mild redness", "Rarely skin irritation"],
    alert: "Stop if a rash or blistering appears. Keep away from children — swallowing balm is a medical emergency.",
    brands: ["Moov Balm", "Zandu Balm", "Amrutanjan Balm"],
  },
];
