/* Skin, eye & ENT — real molecules & Indian brands. */
module.exports = [
  {
    salt: "Clotrimazole", cat: "Skin, Eye & ENT", kind: "Cream · Lotion · Powder · Drops",
    strengths: ["1% Cream", "1% Ear Drops"],
    simple: "The standard anti-fungal — it punches holes in fungal cell walls. The cream for ringworm and athlete's foot, drops for fungal ear infection.",
    uses: ["Ringworm", "Athlete's foot", "Jock itch", "Fungal skin folds", "Fungal ear infection"],
    how: "Thin cream layer twice daily, and continue 1–2 WEEKS after the rash disappears — stopping early is why ringworm returns. Keep folds dry.",
    watch: ["Mild stinging on application"],
    alert: "Rash spreading fast with fever needs a doctor (could be bacterial). Face or scalp ringworm needs oral treatment, not cream alone.",
    brands: ["Candid Cream", "Candid Ear Drops", "Candid B Cream (with steroid)"],
  },
  {
    salt: "Ketoconazole", cat: "Skin, Eye & ENT", kind: "Shampoo · Cream · Tablet",
    strengths: ["2% Shampoo", "2% Cream"],
    simple: "A stronger anti-fungal family member — the shampoo for stubborn dandruff and seborrhoea, cream for ringworm and tinea versicolor patches.",
    uses: ["Dandruff", "Seborrhoeic dermatitis", "Tinea versicolor", "Ringworm"],
    how: "Shampoo twice weekly: lather, wait 5 minutes, rinse. Cream twice daily for 2–4 weeks.",
    watch: ["Hair dryness", "Mild irritation"],
    alert: "Oral ketoconazole tablets are no longer used (liver risk) — stick to external forms. Eye contact should be avoided.",
    brands: ["KZ Shampoo", "Nizral Shampoo", "KZ Cream"],
  },
  {
    salt: "Terbinafine", cat: "Skin, Eye & ENT", kind: "Tablet · Cream",
    strengths: ["250 mg Tablet", "1% Cream"],
    simple: "The strongest common oral anti-fungal — actually kills the fungus rather than just suppressing it; the treatment for nail fungus and stubborn ringworm.",
    uses: ["Nail fungus", "Extensive ringworm", "Scalp fungus (oral course)"],
    how: "250 mg once daily for weeks (toenails need 12+ weeks); cream twice daily for local infection. Liver tests for long courses.",
    watch: ["Taste disturbance", "Nausea", "Rash"],
    alert: "Liver disease needs caution and monitoring. Taste loss during the course must be reported.",
    brands: ["Terbicip 250", "Terbin 250", "Sebifin 250"],
  },
  {
    salt: "Mupirocin", cat: "Skin, Eye & ENT", kind: "Ointment",
    strengths: ["2% Ointment"],
    simple: "A topical antibiotic ointment that kills staph and strep on the skin — the standard for infected cuts, boils in early stage and impetigo sores.",
    uses: ["Impetigo", "Infected cuts", "Boils (early)", "Nasal carrier of MRSA (nasal form)"],
    how: "Small amount three times daily on the cleaned area for 5–10 days, or a pea-sized amount inside nostrils twice daily for carrier decolonisation.",
    watch: ["Mild burning", "Itching"],
    alert: "Spreading redness with fever means the infection has gone deeper — needs oral antibiotics, not ointment.",
    brands: ["T-Bact Ointment", "Bactroban Ointment", "Supirocin Ointment"],
  },
  {
    salt: "Neomycin + Polymyxin B", cat: "Skin, Eye & ENT", kind: "Ointment · Powder Spray",
    simple: "A two-antibiotic surface shield for minor cuts and grazes — covers the common skin germs while the wound heals.",
    uses: ["Minor infected cuts", "Grazes", "Post-surgical surface protection (as advised)"],
    how: "Thin layer 1–3 times daily on cleaned skin.",
    watch: ["Contact rash in some people"],
    alert: "Rash worsening rather than settling means allergy — stop. Deep, dirty or animal wounds need proper wound care and tetanus review.",
    brands: ["Neosporin Ointment", "Neosporin Powder"],
  },
  {
    salt: "Clobetasol", cat: "Skin, Eye & ENT", kind: "Cream · Ointment",
    strengths: ["0.05% Cream"],
    simple: "A super-potent steroid cream for thick, stubborn plaques like psoriasis and severe eczema — powerful medicine with strict short-course rules.",
    uses: ["Psoriasis plaques", "Severe eczema patches", "Lichen planus", "Thick palm/sole dermatitis"],
    how: "Thin layer ONCE or twice daily for a maximum of 2 weeks on the same patch, then reviewed — potent steroids thin skin with overuse.",
    watch: ["Skin thinning with overuse", "Stretch marks", "Lightening of colour"],
    alert: "Never on the face, groin or folds unless a dermatologist directs. Never use leftover clobetasol casually for any itch.",
    brands: ["Tenovate Cream", "Dermovate Cream", "Cloben-GM Cream"],
  },
  {
    salt: "Hydrocortisone (topical)", cat: "Skin, Eye & ENT", kind: "Cream · Lotion",
    strengths: ["1% Cream"],
    simple: "The gentle everyday steroid cream — takes the itch and redness out of mild eczema, insect bites and rashes without the strong-steroid risks.",
    uses: ["Mild eczema", "Insect bites", "Contact rash", "Itchy dermatitis"],
    how: "Thin layer twice daily for up to 1–2 weeks on small areas.",
    watch: ["Skin dryness"],
    alert: "If a rash isn't clearly better in 7 days, get it diagnosed instead of continuing blindly. Not for fungal areas (they worsen with steroids).",
    brands: ["Cortisone 1% Cream", "Wycort Cream"],
  },
  {
    salt: "Permethrin", cat: "Skin, Eye & ENT", kind: "Cream",
    strengths: ["5% Cream"],
    simple: "The scabies killer — a nerve poison to mites, safe for humans. Applied as a full-body overnight coat for everyone in the household at once.",
    uses: ["Scabies", "Lice (lotion form)"],
    how: "Apply from neck-down to the WHOLE body (including soles, between fingers) at night, wash off after 8–14 hours; repeat once after 7 days. Treat all family members simultaneously; wash clothes/bedding hot.",
    watch: ["Itching can persist 2–4 weeks after cure (post-scabies itch)"],
    alert: "Continuous new burrows/blisters after two proper applications needs review — maybe crusted scabies requiring oral therapy.",
    brands: ["Permite 5% Cream", "Scaboma Lotion", "Bscab Lotion"],
  },
  {
    salt: "Isotretinoin", cat: "Skin, Eye & ENT", kind: "Capsule",
    strengths: ["10 mg Capsule", "20 mg Capsule"],
    simple: "The definitive severe-acne drug — it shrinks the skin's oil glands, unclogging the root cause. Very effective, very rule-bound, always dermatologist-supervised.",
    uses: ["Severe nodular acne", "Acne not responding to antibiotics", "Rosacea variants (low dose)"],
    how: "0.5–1 mg/kg daily in divided doses with fatty food for 4–6+ month courses, with monthly blood tests (lipids, liver) during therapy.",
    watch: ["Very dry lips (universal)", "Dry eyes and skin", "Sun sensitivity"],
    alert: "ABSOLUTE: causes severe birth defects — pregnancy prevention is mandatory through the course and a month after. Mood changes must be reported immediately.",
    brands: ["Sotret 10", "Sotret 20", "Isotroin 20", "Accutane (global)"],
  },
  {
    salt: "Adapalene + Benzoyl peroxide", cat: "Skin, Eye & ENT", kind: "Gel",
    simple: "The nightly acne duo-gel: adapalene renews pore lining while benzoyl peroxide kills acne bacteria — together clearing comedones and pimples.",
    uses: ["Acne with blackheads", "Inflammatory acne", "Maintenance after isotretinoin"],
    how: "Pea-sized amount for the WHOLE face at night on dry skin, 2–3 nights weekly at first, building to nightly; moisturise mornings and use sunscreen.",
    watch: ["Dryness and peeling early", "Mild burning"],
    alert: "Benzoyl peroxide bleaches fabrics and hair. Strong irritation means space out applications rather than quitting.",
    brands: ["Deriva CMS Gel", "Deriva BPO Gel"],
  },
  {
    salt: "Tacrolimus (topical)", cat: "Skin, Eye & ENT", kind: "Ointment",
    strengths: ["0.03% Ointment", "0.1% Ointment"],
    simple: "A steroid-free immune-calming ointment for delicate areas — face, eyelids, folds — where strong steroids are unsafe in eczema and vitiligo protocols.",
    uses: ["Facial eczema", "Eyelid dermatitis", "Vitiligo (with light therapy)", "Atopic dermatitis in folds"],
    how: "Thin layer twice daily on affected areas; brief burning at first application usually settles in days.",
    watch: ["Initial burning/stinging", "Rarely folliculitis"],
    alert: "Avoid intense sun exposure on treated areas; not for infected skin.",
    brands: ["Tacroz Forte Ointment", "Takfa Ointment"],
  },
  {
    salt: "Moxifloxacin eye drops", cat: "Skin, Eye & ENT", kind: "Eye Drops",
    strengths: ["0.5% Eye Drops"],
    simple: "A broad antibiotic drop for bacterial conjunctivitis — pink eye with sticky discharge — hitting the common eye germs in four daily doses.",
    uses: ["Bacterial conjunctivitis", "Corneal ulcer (as advised)", "Post-eye-surgery infection prevention"],
    how: "One drop 3–4 times daily for about a week, as prescribed; never share the bottle.",
    watch: ["Brief stinging", "Blurred vision for a minute"],
    alert: "Steroid-containing eye drops need an eye doctor's direction. Vision drop, severe pain or light sensitivity is same-day ophthalmology territory.",
    brands: ["Vigamox Eye Drops", "Milflox Eye Drops", "Moxicip Eye Drops"],
  },
  {
    salt: "Timolol eye drops", cat: "Skin, Eye & ENT", kind: "Eye Drops",
    strengths: ["0.5% Eye Drops"],
    simple: "A beta-blocker eye drop that reduces fluid production inside the eye — the classic glaucoma pressure-lowering drop, usually twice daily.",
    uses: ["Glaucoma", "Ocular hypertension"],
    how: "One drop twice daily, pressing the inner corner briefly after instilling (reduces body absorption).",
    watch: ["Mild stinging", "Rarely slow pulse or asthma-like wheeze (body absorption)"],
    alert: "Asthma and heart-block patients must tell the ophthalmologist. Missed glaucoma drops quietly damage vision — adherence matters.",
    brands: ["Glucomol 0.5 Eye Drops", "Timoptic Eye Drops"],
  },
  {
    salt: "Carboxymethylcellulose (lubricating drops)", cat: "Skin, Eye & ENT", kind: "Eye Drops",
    strengths: ["0.5% Eye Drops", "1% Eye Drops"],
    simple: "Artificial tears — a protective lubricant layer for dry, screen-tired eyes. Preservative-free forms are gentlest for frequent use.",
    uses: ["Dry eyes", "Computer vision strain", "Post-LASIK dryness", "Contact lens comfort (approved forms)"],
    how: "One drop in each eye as needed — even 4–6 times daily for preservative-free versions.",
    watch: ["Blurring for seconds after instillation"],
    alert: "Eye pain, redness with light sensitivity or vision loss is NOT dryness — see an eye doctor.",
    brands: ["Refresh Tears Eye Drops", "Tear Plus Eye Drops", "Optive Eye Drops"],
  },
  {
    salt: "Olopatadine eye drops", cat: "Skin, Eye & ENT", kind: "Eye Drops",
    strengths: ["0.1% Eye Drops", "0.7% Eye Drops"],
    simple: "An anti-histamine-plus-stabiliser eye drop for itchy allergic eyes — relieves the itch within minutes and calms the mast cells that keep it flaring.",
    uses: ["Allergic conjunctivitis", "Itchy watery eyes in pollen/dust season"],
    how: "One drop twice daily during the allergy period.",
    watch: ["Brief stinging", "Headache (rare)"],
    alert: "Vision change or pain needs ophthalmology. Don't share drop bottles between family members.",
    brands: ["Opatanol Eye Drops", "Patanol Eye Drops", "Olopat Eye Drops"],
  },
  {
    salt: "Xylometazoline + antiseptic throat lozenge", cat: "Skin, Eye & ENT", kind: "Lozenges",
    simple: "Soothing medicated lozenges for a scratchy throat — local antiseptic plus mild anaesthetic that numbs pain while saliva washes the inflamed lining.",
    uses: ["Sore throat", "Throat irritation from cough", "Voice strain"],
    how: "Dissolve one lozenge slowly every 2–3 hours as needed; don't chew or swallow whole.",
    watch: ["Mild mouth numbness"],
    alert: "Fever with white patches on tonsils, or sore throat beyond 5 days, needs a strep assessment — lozenges don't treat strep.",
    brands: ["Strepsils Lozenges", "Vicks Cough Drops", "Halls Lozenges"],
  },
];
