/* Vitamins, supplements, bone health — real molecules & Indian brands. */
module.exports = [
  {
    salt: "Vitamin D3 (cholecalciferol)", cat: "Vitamins & Supplements", kind: "Sachet · Drops · Tablet",
    strengths: ["60,000 IU Sachet", "2,000 IU Tablet"],
    simple: "The sunshine vitamin — it lets the gut absorb calcium and keeps bones, muscles and immunity supplied. Indian indoor lifestyles make deficiency extremely common.",
    uses: ["Vitamin D deficiency", "Bone and joint pains", "Muscle weakness", "Osteoporosis support"],
    how: "Weekly 60,000 IU sachet with milk for 6–8 weeks (doctor-planned), then a maintenance dose; daily 1,000–2,000 IU is the common maintenance.",
    watch: ["Essentially none at prescribed doses"],
    alert: "More is NOT better — unsupervised megadoses for months can raise calcium dangerously (thirst, confusion, stones). Follow the schedule.",
    brands: ["Calcirol Sachet", "Uprise D3 Sachet", "D-Rise Sachet", "Uprise D3 2K Tablet"],
  },
  {
    salt: "Calcium carbonate + Vitamin D3", cat: "Vitamins & Supplements", kind: "Tablet · Suspension",
    strengths: ["500 mg Tablet", "250 mg Tablet"],
    simple: "The bone-building pair — calcium as the building block plus vitamin D so the calcium is actually absorbed. Standard in pregnancy, teens, and osteoporosis care.",
    uses: ["Osteoporosis", "Pregnancy and lactation", "Calcium-deficient diets", "Bone healing"],
    how: "One tablet after lunch or dinner (split from levothyroxine, iron and tetracyclines by 4 hours — they block each other).",
    watch: ["Constipation", "Gas"],
    alert: "Kidney-stone formers and high blood calcium need medical dosing. Spread doses — the gut absorbs ~500 mg at a time best.",
    brands: ["Shelcal 500", "Shelcal 250", "Gemcal Tablet", "Calcimax Tablet"],
  },
  {
    salt: "Vitamin B-complex", cat: "Vitamins & Supplements", kind: "Tablet · Capsule · Injection",
    strengths: ["B1+B6+B12 Tablet"],
    simple: "The nerve-and-energy vitamin trio — B1, B6 and B12 keep nerves insulated, blood cells forming and metabolism humming; deficiencies show as tingling, fatigue and mouth sores.",
    uses: ["Nerve tingling", "Anaemia support", "Mouth ulcers", "Alcohol-related deficiency", "With TB/metformin therapy"],
    how: "One tablet/capsule daily after food; injections are given for severe deficiency.",
    watch: ["Bright yellow urine (B12 — harmless)", "Occasional nausea"],
    alert: "High-dose B6 taken for months can paradoxically damage nerves — stick to label doses.",
    brands: ["Neurobion Forte", "Nurokind Plus", "Becosules Capsule"],
  },
  {
    salt: "Methylcobalamin (Vitamin B12)", cat: "Vitamins & Supplements", kind: "Tablet · Capsule · Injection",
    strengths: ["1500 mcg Tablet"],
    simple: "The active form of B12 — the nerve-repair and blood-making vitamin. Vegetarians, metformin users and the elderly are the usual deficient groups.",
    uses: ["B12 deficiency", "Diabetic nerve pain support", "Tingling feet", "Anaemia"],
    how: "One tablet daily after food, or weekly injections for severe deficiency, under blood-test guidance.",
    watch: ["None at normal doses"],
    alert: "Numbness that persists needs proper neurological workup — B12 is not a cure-all for every tingling.",
    brands: ["Methycobal 1500", "Nervup Tablet", "Nurokind LC"],
  },
  {
    salt: "Vitamin C (ascorbic acid)", cat: "Vitamins & Supplements", kind: "Tablet (Chewable)",
    strengths: ["500 mg Tablet"],
    simple: "The citrus vitamin — needed to build collagen, heal wounds and keep immunity supplied; deficiency shows as bleeding gums and slow healing.",
    uses: ["Vitamin C deficiency", "Wound healing", "Immunity support", "Iron absorption booster"],
    how: "One chewable tablet daily, ideally with or after food; extra vitamin C doesn't cure colds but supports general needs.",
    watch: ["Acidity at high doses", "Loose stools (over 2 g/day)"],
    alert: "Kidney-stone formers should avoid megadoses — oxalate stones can be encouraged.",
    brands: ["Limcee 500", "Celin 500"],
  },
  {
    salt: "Multivitamin + Zinc", cat: "Vitamins & Supplements", kind: "Tablet · Capsule · Syrup",
    simple: "A one-a-day safety net of essential vitamins with zinc for immunity and wound healing — useful in poor intake, recovery illness, and picky diets.",
    uses: ["General deficiency cover", "Recovery after illness", "Weakness and fatigue", "Poor diet periods"],
    how: "One tablet daily after breakfast; courses of 1–3 months are typical.",
    watch: ["Dark urine from B vitamins", "Mild nausea if taken empty stomach"],
    alert: "Not a substitute for diagnosing real fatigue — persistent weakness needs tests, not just supplements.",
    brands: ["Zincovit Tablet", "A to Z NS Tablet", "Supradyn Daily"],
  },
  {
    salt: "Ferrous ascorbate + Folic acid", cat: "Vitamins & Supplements", kind: "Tablet · Suspension",
    strengths: ["100 mg/1.5 mg Tablet"],
    simple: "A gentle modern iron with vitamin C built in for absorption, plus folate for blood-cell building — the standard pregnancy and anaemia prescription.",
    uses: ["Iron-deficiency anaemia", "Pregnancy anaemia", "Post-blood-loss recovery"],
    how: "One tablet daily on an empty-ish stomach with water or citrus (NOT with milk, tea or calcium — they block iron). Stools turn black: normal.",
    watch: ["Black stools (normal)", "Constipation", "Nausea"],
    alert: "Haemoglobin is rechecked after 4–6 weeks; if it hasn't risen, causes beyond iron are investigated. Keep away from children — iron overdose is toxic.",
    brands: ["Orofer XT Tablet", "Ferrous XT Tablet", "Orofer XT Suspension"],
  },
  {
    salt: "Ferrous sulphate + Folic acid", cat: "Vitamins & Supplements", kind: "Capsule",
    strengths: ["150 mg/1.5 mg Capsule"],
    simple: "The classic iron-folate capsule used in national anaemia programmes — effective, economical, with the usual iron stomach rules.",
    uses: ["Anaemia", "Pregnancy supplementation", "Menstrual blood-loss anaemia"],
    how: "One capsule daily with citrus juice, away from tea/coffee and calcium by 2 hours.",
    watch: ["Constipation", "Black stools", "Metallic taste"],
    alert: "Recheck haemoglobin in 4–6 weeks. Children must never access iron capsules.",
    brands: ["Fefol Capsule", "Autrin Capsule"],
  },
  {
    salt: "Vitamin E (tocopherol)", cat: "Vitamins & Supplements", kind: "Capsule",
    strengths: ["200 IU Capsule", "400 IU Capsule"],
    simple: "A fat-soluble antioxidant vitamin — protects cell membranes from oxidation; used in deficiency states, some skin conditions and nerve support.",
    uses: ["Vitamin E deficiency", "Dry skin support", "Fat-malabsorption states"],
    how: "One capsule daily with a meal containing fat for absorption.",
    watch: ["Essentially none at 200–400 IU"],
    alert: "High-dose long-term E has been linked to bleeding tendency — don't megadose without advice.",
    brands: ["Evion 200", "Evion 400"],
  },
  {
    salt: "Zinc", cat: "Vitamins & Supplements", kind: "Tablet · Syrup",
    strengths: ["50 mg Tablet", "20 mg Tablet"],
    simple: "The immunity-and-healing mineral — required for hundreds of enzymes, taste, wound repair and infection defence; WHO gives zinc in childhood diarrhoea.",
    uses: ["Diarrhoea in children (with ORS)", "Zinc deficiency", "Immunity support", "Taste disturbance"],
    how: "20 mg once daily for 14 days in childhood diarrhoea; adults 25–50 mg short courses as advised.",
    watch: ["Nausea on empty stomach", "Metallic taste"],
    alert: "Months of high-dose zinc can deplete copper and cause nerve symptoms — supplementation should be time-bounded.",
    brands: ["Zinconia 50", "Zincovit Syrup", "Zinc-20 Tablet"],
  },
  {
    salt: "Alendronate", cat: "Bones & Joints", kind: "Tablet",
    strengths: ["35 mg Tablet", "70 mg Tablet"],
    simple: "A bisphosphonate that slows the cells dissolving bone, tipping the balance back to bone-building — the standard osteoporosis treatment after fractures or on steroids.",
    uses: ["Osteoporosis (post-menopausal)", "Steroid-induced bone loss", "Fracture prevention"],
    how: "One weekly 70 mg tablet: on waking, EMPTY stomach, with a full glass of plain water, sitting/standing upright 30 minutes, no food or other pills — the ritual protects the oesophagus.",
    watch: ["Heartburn", "Muscle-bone aches early"],
    alert: "Chest pain on swallowing means stop and call. Jaw bone issues are rare but dental work should be mentioned to the dentist.",
    brands: ["Osteofos 70", "Osteofos 35", "Restofos 70"],
  },
  {
    salt: "Risedronate", cat: "Bones & Joints", kind: "Tablet",
    strengths: ["35 mg Tablet"],
    simple: "Another weekly bisphosphonate for osteoporosis — same bone-resorption slowdown, alternative when alendronate doesn't suit.",
    uses: ["Osteoporosis", "Paget's disease", "Steroid-related bone loss"],
    how: "Weekly tablet with water on an empty stomach, upright for 30 minutes — identical ritual to alendronate.",
    watch: ["Reflux", "Bone aches"],
    alert: "Same oesophagus-protection rules; dental team should know you're on it.",
    brands: ["Risofos 35", "Gemfos 35"],
  },
  {
    salt: "Zoledronic acid", cat: "Bones & Joints", kind: "Injection",
    strengths: ["4 mg Injection", "5 mg Injection"],
    simple: "The once-a-year IV bisphosphonate — one hospital drip strengthens bones for months, ideal when weekly tablets are forgotten or poorly tolerated.",
    uses: ["Osteoporosis (annual therapy)", "Cancer-related bone disease", "High calcium from malignancy"],
    how: "Given as a slow IV infusion by staff with hydration and dental checks beforehand; yearly for osteoporosis.",
    watch: ["Flu-like aches and fever for 1–2 days after (common)", "Renal function monitored"],
    alert: "Kidney disease dosing is specialist territory; jaw health review before therapy is standard.",
    brands: ["Zoldria 4mg Injection", "Zometa 4mg Injection"],
  },
  {
    salt: "Teriparatide", cat: "Bones & Joints", kind: "Injection (Pen)",
    strengths: ["20 mcg Pen"],
    simple: "A parathyroid-hormone fragment that is the only true bone-BUILDER — used for severe osteoporosis with fractures, daily self-injected for up to 2 years.",
    uses: ["Severe osteoporosis", "Multiple fragility fractures", "Steroid-induced severe bone loss"],
    how: "One daily subcutaneous injection into thigh/abdomen; cold-chain storage; courses capped at 24 months then followed by a bisphosphonate.",
    watch: ["Leg cramps", "Dizziness after dose", "Nausea"],
    alert: "Avoid in prior bone cancer or raised calcium. Sit or lie down briefly after the first doses if dizzy.",
    brands: ["Bonista Pen", "Forteo Pen"],
  },
  {
    salt: "Calcitriol", cat: "Bones & Joints", kind: "Capsule · Softgel",
    strengths: ["0.25 mcg Capsule", "0.5 mcg Capsule"],
    simple: "The ACTIVE form of vitamin D — used when kidneys can't convert ordinary vitamin D themselves (CKD, hypoparathyroidism). Calcium levels are watched closely.",
    uses: ["Chronic kidney disease bone disease", "Hypoparathyroidism", "Post-parathyroidectomy care"],
    how: "0.25–0.5 mcg daily as titrated by blood calcium levels; taken with calcium as instructed.",
    watch: ["Thirst and excess urination if calcium rises"],
    alert: "Overdose risk is real (unlike plain vitamin D) — never self-escalate; periodic calcium blood tests are mandatory.",
    brands: ["Calcibest 0.25", "Rocaltrol 0.25", "Calctrol 0.25"],
  },
  {
    salt: "Glucosamine + Chondroitin", cat: "Bones & Joints", kind: "Tablet",
    simple: "Cartilage building-block supplements — evidence is modest, but many knee-osteoarthritis patients report smoother joints over 2–3 months of use.",
    uses: ["Knee osteoarthritis support", "Joint stiffness"],
    how: "One tablet twice or thrice daily with meals for at least 2–3 months before judging benefit.",
    watch: ["Mild gas", "Stomach comfort"],
    alert: "Shellfish-derived products need allergy disclosure. Diabetics monitor sugars initially. It eases symptoms — it doesn't rebuild lost cartilage.",
    brands: ["Cartigen Duo", "Rejoint Tablet", "Glucomax Tablet"],
  },
];
