/* Women's health — real molecules & Indian brands. */
module.exports = [
  {
    salt: "Ethinylestradiol + Levonorgestrel", cat: "Women's Health", kind: "Tablet",
    simple: "The classic combined birth-control pill — a low oestrogen plus a progestin that stops ovulation and thickens cervical mucus, giving reliable contraception when taken daily at the same time.",
    uses: ["Contraception", "Cycle regulation", "Painful/heavy periods (selected)"],
    how: "One pill daily at a fixed time from day 1 of the cycle; a missed pill is taken as soon as remembered (see pack rules). Smoking over 35 years old raises risks — disclose it.",
    watch: ["Nausea first cycles", "Breast tenderness", "Spotting between periods"],
    alert: "Severe leg calf pain/swelling, sudden breathlessness or one-sided weakness = possible clot — emergency. Migraine with aura contraindicates it.",
    brands: ["Femilon Tablet", "Ovral-L Tablet", "Nordette Tablet"],
  },
  {
    salt: "Ethinylestradiol + Drospirenone", cat: "Women's Health", kind: "Tablet",
    simple: "A modern combined pill whose progestin (drospirenone) counters water retention — often chosen for acne or bloating with contraception needs.",
    uses: ["Contraception", "PMDD/bloating relief", "Hormonal acne"],
    how: "One tablet daily at a fixed time through the 21+7 pack schedule.",
    watch: ["Breast tenderness", "Nausea", "Mood changes"],
    alert: "Same clot warning as all combined pills. Potassium-raising drugs (ACE inhibitors) need caution with drospirenone.",
    brands: ["Yasmin Tablet", "Yasminelle Tablet"],
  },
  {
    salt: "Ethinylestradiol + Cyproterone", cat: "Women's Health", kind: "Tablet",
    simple: "An anti-androgen pill — cyproterone blocks male-hormone effects while oestrogen cycles the uterus; the standard hormonal therapy for PCOS acne and excess hair growth.",
    uses: ["PCOS acne and hirsutism", "Severe hormonal acne", "Contraception"],
    how: "One tablet daily from day 1 of the cycle, usually for months under gynaecological review; liver tests are monitored.",
    watch: ["Nausea", "Breast heaviness", "Mood swings"],
    alert: "Clot risk is slightly higher than plain pills — no smoking, report leg pain or breathlessness urgently. Not to be combined with other oestrogens.",
    brands: ["Krimson 35", "Diane 35"],
  },
  {
    salt: "Dydrogesterone", cat: "Women's Health", kind: "Tablet",
    strengths: ["10 mg Tablet"],
    simple: "A progesterone-like hormone that prepares and steadies the uterine lining — famous in pregnancy-support and recurrent-miscarriage care, and for irregular cycles.",
    uses: ["Threatened miscarriage (as advised)", "Recurrent pregnancy loss", "Irregular periods", "Endometriosis", "Luteal support in IVF"],
    how: "10 mg once or twice daily as the gynaecologist schedules it — timing depends on the cycle day or pregnancy situation.",
    watch: ["Mild nausea", "Breast tenderness"],
    alert: "Bleeding with pain in pregnancy always needs same-day examination, whatever the medicine.",
    brands: ["Duphaston 10", "Dydroboon 10"],
  },
  {
    salt: "Natural micronised progesterone", cat: "Women's Health", kind: "Capsule (SR)",
    strengths: ["200 mg Capsule", "300 mg Capsule"],
    simple: "The body-identical progesterone hormone in capsule form — supports the uterine lining in early pregnancy, regulates cycles and aids luteal-phase support.",
    uses: ["Early pregnancy support", "Luteal phase support", "Secondary amenorrhoea", "Perimenopausal bleeding patterns"],
    how: "Orally at night (it causes drowsiness) or vaginally as instructed — the route matters, so follow the prescription exactly.",
    watch: ["Sleepiness", "Dizziness", "Breast tenderness"],
    alert: "Take at bedtime if dizziness occurs; never drive after a vaginal/oral high dose until you know your response.",
    brands: ["Susten 200", "Naturogest 200", "Duragest 200"],
  },
  {
    salt: "Clomiphene", cat: "Women's Health", kind: "Tablet",
    strengths: ["25 mg Tablet", "50 mg Tablet", "100 mg Tablet"],
    simple: "An ovulation-inducer — it tricks the brain into releasing more FSH so the ovary develops and releases an egg; the classic first tablet in infertility care.",
    uses: ["Anovulatory infertility (PCOS)", "Ovulation induction with timed cycles"],
    how: "Started day 2–5 of the cycle for 5 days under monitoring (follicular scans confirm response); never self-cycle without scans.",
    watch: ["Hot flushes", "Mood swings", "Ovarian discomfort"],
    alert: "Severe abdominal swelling and pain after the course can mean ovarian hyperstimulation — urgent gynaecological review. Multiple pregnancy risk rises.",
    brands: ["Fertyl 50", "Clome 50", "Fertomid 50"],
  },
  {
    salt: "Letrozole", cat: "Women's Health", kind: "Tablet",
    strengths: ["2.5 mg Tablet"],
    simple: "An aromatase blocker that lowers oestrogen — used for ovulation induction in PCOS (often ahead of clomiphene) and as hormonal therapy in breast cancer.",
    uses: ["Ovulation induction", "Hormone-receptor-positive breast cancer"],
    how: "2.5 mg daily for 5 cycle days (fertility) or daily long-term (oncology) — strictly per specialist.",
    watch: ["Hot flushes", "Joint aches", "Tiredness (oncology use)"],
    alert: "Bone density is monitored in long oncology use. Pregnancy must be excluded before fertility cycles.",
    brands: ["Fempro 2.5", "Letova 2.5", "Cantol 2.5"],
  },
  {
    salt: "Tranexamic acid", cat: "Women's Health", kind: "Tablet · Injection",
    strengths: ["500 mg Tablet", "500 mg Injection"],
    simple: "A clot-stabiliser — it stops the enzymes that dissolve fresh clots, so bleeding slows. The standard tablet for heavy periods and a hospital injection for trauma bleeding.",
    uses: ["Heavy menstrual bleeding", "Dental extraction bleeding", "Trauma bleeding (injection)", "Surgical bleeding control"],
    how: "1–1.5 g two or three times daily during heavy days of the period; injections are hospital-only.",
    watch: ["Nausea", "Mild cramps", "Headache"],
    alert: "Not used with a history of clotting problems (DVT/stroke). Red-brown urine or leg swelling on it needs review.",
    brands: ["Trapic 500", "Texid 500", "Tranex 500"],
  },
  {
    salt: "Mefenamic acid + Dicyclomine", cat: "Women's Health", kind: "Tablet · Suspension",
    simple: "A period-pain pair: mefenamic calms the prostaglandin cramps while dicyclomine relaxes the uterine and gut muscle spasm — the two-hit approach to dysmenorrhoea.",
    uses: ["Severe period cramps", "Gut cramps with periods", "Spasmodic dysmenorrhoea"],
    how: "One tablet up to three times daily during painful days, after food; syrup doses for girls are weight-based.",
    watch: ["Drowsiness", "Dry mouth", "Stomach discomfort"],
    alert: "Take after food (NSAID rule). Cramps that suddenly worsen or don't respond need a gynaecological check.",
    brands: ["Meftal Spas", "Colme-Forte"],
  },
  {
    salt: "Myo-inositol + D-chiro-inositol", cat: "Women's Health", kind: "Sachet · Tablet",
    simple: "Insulin-sensitising nutrient pair for PCOS — improves how the ovary and muscles respond to insulin, easing cycles, acne and metabolic markers over months.",
    uses: ["PCOS with insulin resistance", "Irregular cycles", "Metabolic support in PCOS"],
    how: "One sachet (or tablet) daily, usually morning, for 3–6 months; works best alongside diet, exercise and weight goals.",
    watch: ["Mild nausea", "Loose stools at high doses"],
    alert: "It's supportive, not a replacement for prescribed diabetes or fertility therapy. Cycle changes should be reviewed by a gynaecologist.",
    brands: ["Ovacare Forte Sachet", "Myo-inositol Sachet", "Ovabless Sachet"],
  },
  {
    salt: "Folic acid", cat: "Women's Health", kind: "Tablet",
    strengths: ["0.4 mg Tablet", "5 mg Tablet"],
    simple: "Vitamin B9 — the pre-pregnancy essential. Adequate folate in the first weeks of pregnancy prevents neural-tube defects in the baby; it also supports red-cell production.",
    uses: ["Pregnancy planning and first trimester", "Folate-deficiency anaemia", "With methotrexate therapy"],
    how: "0.4–0.8 mg daily when planning pregnancy (from at least a month before); 5 mg doses are for deficiency or special cases.",
    watch: ["Essentially none at normal doses"],
    alert: "Never use the 5 mg tablet casually as a multivitamin — doses should match the purpose.",
    brands: ["Folvite 5mg", "Folic Acid 0.4 Tablet"],
  },
  {
    salt: "Cabergoline", cat: "Women's Health", kind: "Tablet",
    strengths: ["0.5 mg Tablet"],
    simple: "A dopamine agonist that switches off prolactin — restarts cycles and fertility when a prolactin-secreting pituitary problem has shut them down.",
    uses: ["High prolactin (hyperprolactinaemia)", "Prolactinoma", "Cycle restoration"],
    how: "Low doses twice weekly initially, titrated to prolactin levels; taken with food at night.",
    watch: ["Nausea", "Dizziness on standing", "Headache"],
    alert: "Report new urges or compulsions (rare behavioural effect), breathlessness or chest pain on long use — heart valves are monitored.",
    brands: ["Cabergolin 0.5", "Cabergyn 0.5"],
  },
];
