"""Diet and activity guidance for common post-discharge diagnoses (spec §10):
cardiac, post-surgical, diabetes, respiratory."""

from seed import chunk

CHUNKS = [
    chunk(
        "Eating after surgery: from clear fluids back to normal food",
        "guideline", "diet",
        """After many operations your digestive system needs a gentle restart, and your team's plan usually moves through stages: clear fluids first, then full fluids, then soft foods, then your regular diet. Clear fluids are things you can see through — water, clear broth, strained juice, weak tea. Full fluids add milk, yogurt drinks, and smooth soups. Soft foods include khichdi, porridge, mashed vegetables, scrambled egg, curd, and soft pasta. Move up a stage only when the current one sits comfortably with no nausea, bloating, or vomiting.
Small portions win at every stage: six to eight small meals beat three large ones while your gut is waking up. Eat slowly and chew thoroughly, and stop when you feel full rather than cleaning the plate. Sip fluids steadily through the day rather than gulping large amounts, which can cause nausea and stretch a tender abdomen.
Some patterns are common and temporary: little appetite for a week or two, early fullness, changed taste, or mild bloating with gas. All of these improve as you heal. Help them along with protein at every meal, because healing tissue needs it; add fluids unless your team has restricted them; and keep moving with short walks, which wake the bowel up better than anything else.
Call your care team if you cannot keep fluids down for more than a day, if your abdomen becomes swollen, hard, or increasingly painful, if you have no bowel movement and no passing of gas for several days after abdominal surgery, or if food feels stuck when you swallow. Until then, expect appetite to lead a slow recovery curve — judge your intake over a whole day, not one disappointing meal, and favor the soft, familiar foods you actually enjoy over heroic attempts at perfect nutrition.""",
        ["post-surgery diet", "clear fluids", "soft foods", "appetite"],
    ),
    chunk(
        "Protein and healing: feeding your recovery",
        "guideline", "diet",
        """Wound healing, immune defense, and rebuilding strength are construction projects, and protein is their raw material. After surgery or serious illness your protein needs rise substantially at exactly the time appetite falls, so recovery meals deserve deliberate planning rather than leftovers-eaten-where-you-stand.
Good everyday protein sources include eggs, milk, curd and paneer, dal and other lentils, chickpeas and beans, fish, chicken, tofu, soy chunks, and nuts. A practical pattern is to include one protein food at every meal and one at a snack: curd with breakfast, dal at lunch, paneer or eggs at dinner, milk or a handful of nuts between meals. If your appetite is small, drink your protein — milk-based drinks, lassi, or soups fortified with blended dal — because fluids are easier than plates.
Vitamin C from citrus, guava, amla, and fresh vegetables supports collagen formation; zinc from whole grains, legumes, and seeds supports tissue repair; and steady hydration keeps everything moving. You do not need supplements if you eat a reasonably varied diet, unless your team prescribed specific ones — iron, for example, if you were anemic at discharge.
If weight is dropping faster than expected, add energy density rather than volume: nut butters, ghee in moderation on dal or roti, full-fat milk, and extra egg in dishes. If instead your team asked you to lose weight, keep protein high while trimming fried foods, sweets, and sugary drinks, so the loss comes from fat and not muscle.
Diabetes, kidney disease, and some liver conditions change these rules meaningfully, so your discharge diet sheet and your own team's advice override this general guidance. And if chewing, swallowing, or appetite make eating genuinely hard for more than a few days, say so at your follow-up — early help with nutrition shortens the whole recovery.""",
        ["protein", "nutrition", "healing foods", "weight"],
    ),
    chunk(
        "Preventing constipation after surgery and painkillers",
        "guideline", "diet",
        """Constipation after discharge is nearly universal and thoroughly preventable. Surgery itself slows the bowel, opioid-type pain medicines slow it further, iron tablets add to the effect, and being less active than usual removes the movement that normally keeps things going. Left alone, it causes bloating, pain that mimics wound complications, poor appetite, and straining that stresses incisions.
Prevention is a daily rhythm: fluids steadily through the day unless your team restricted them, fiber at every meal — vegetables, fruits with skins, whole grains, dal, prunes or papaya work especially well — and short walks several times a day, because walking is the bowel's favorite medicine. If your pain plan includes opioids and your team prescribed a stool softener alongside, take it from day one rather than rescuing yourself later; the combination is deliberate, not optional.
Practical targets that work for most people: a warm drink on waking, breakfast within an hour, a walk after each main meal, and a toilet attempt about twenty to thirty minutes after breakfast when the bowel reflex is naturally strongest. Do not postpone the urge when it comes; habitually ignoring it resets the reflex. Put your feet on a small stool when sitting on the toilet so your knees are above your hips — this position makes passage significantly easier.
If you have not had a bowel movement by the number of days your team mentioned, or you are straining hard, call before reaching for strong laxatives; some are inappropriate after certain surgeries. Seek care urgently for constipation with vomiting, a hard swollen painful abdomen, or no gas passing at all after abdominal surgery, because that pattern can mean a blockage rather than simple constipation. And remember the trend: your first bowel movement after surgery may be slower than usual, but days of increasing bloating and discomfort are a message, not a phase to endure.""",
        ["constipation", "fiber", "opioids", "walking"],
    ),
    chunk(
        "Lifting and movement restrictions after surgery",
        "guideline", "activity",
        """Surgeons restrict lifting and straining because healing tissue is strongest at rest and weakest under sudden pull; every restriction exists to protect the exact repair you just received. Follow the specific limits your team gave you — common patterns are 'nothing heavier than a couple of kilograms', roughly the weight of a full kettle or a small bag of rice, for the first few weeks, with the limit easing as healing confirms.
What counts as lifting is broader than it feels: laundry baskets, shopping bags, grandchildren, pets, full cooking pots, suitcases, and pushing heavy supermarket trolleys. Straining counts too — forceful coughing without supporting the incision, straining on the toilet, pushing a stuck door, and sudden twisting movements like catching a falling object. Support any cough or sneeze with a pillow held gently against abdominal or chest incisions.
Movement is still encouraged, and encouraged strongly: walk early and often, starting with short, flat, slow walks and adding a few minutes each day as comfort allows. Gentle range-of-motion movement that does not stretch the incision keeps stiffness away. The line between helpful movement and harmful strain is simple — steady, planned, supported effort is good; sudden, heavy, or twisting effort is not.
Work your household around the limit: slide loads along counters instead of carrying them, divide shopping into many small bags, ask family for the heavy jobs for a few weeks, and use a small backpack to keep weight centered if you must carry anything. Return to lifting in stages as your team approves, starting with light objects and building over days. Call your care team if you feel a sudden pull or pop at the incision with new pain or bulging, if the wound starts leaking after a strain, or if sharp pain limits walking altogether — those are check-it-today signs, not push-through-it signs.""",
        ["lifting limits", "straining", "movement", "recovery"],
    ),
    chunk(
        "Walking your way back: the safest post-surgery exercise",
        "guideline", "activity",
        """Walking is the unsung hero of post-surgical recovery: it wakes the bowel, protects against clots, rebuilds stamina, lifts mood, and costs nothing. Start where you are, not where you were. Most people begin with short, flat, indoor walks — a corridor, a garden loop, several laps to the letterbox — a few times a day, then extend by five minutes every couple of days as breathing and comfort allow. A useful rhythm is three short walks daily rather than one long exhausting one.
Pace yourself with the talk test: you should be able to speak in full sentences while walking. If you cannot, slow down; if you finish a walk feeling pleasantly tired rather than drained, you have it right. Expect good and bad days — stamina returns in a staircase pattern, not a straight line, and an off day is not a setback unless it follows a trend of several.
Build in rest before you think you need it, especially in the first two weeks, and time walks for when pain medicine is working. Dress for the weather: overheating and shivering both cost energy you want for healing. Hydrate before and after unless your team restricted fluids.
Stop a walk and rest if you get chest pain or pressure, unusual breathlessness that does not settle within a few minutes of stopping, dizziness, palpitations, sudden sharp calf pain with swelling, or you feel faint. Those symptoms need a same-day conversation with your care team, and chest pain or breathing difficulty need emergency care.
Climbing stairs is generally fine if your team allowed it — go slowly, hold the rail, and lead with the stronger leg going up. Save formal exercise, gyms, swimming, and sports until your team clears you, usually at a follow-up visit, because they add strain and infection risk that daily walking does not. When you do return, halve your remembered intensity; fitness rebuilds faster than people fear once the foundation is laid.""",
        ["walking", "exercise", "talk test", "stamina"],
    ),
    chunk(
        "Heart failure at home: daily weights, fluid and salt awareness",
        "guideline", "diet",
        """With heart failure, small daily habits catch trouble weeks before it becomes an admission. The most powerful is the daily weight: every morning, after using the toilet, before breakfast, wearing similar clothing, on the same scale. Write it down. What matters is the trend — a gain of two kilograms or more over two days, or around two and a half kilograms in a week, usually means your body is holding onto fluid, and that is a call-your-care-team trigger, not a wait-and-see.
Salt makes the body retain fluid, so keep added salt low: taste before you salt, skip salt at the table, and limit pickles, papad, packaged snacks, instant noodles, processed meats, and restaurant food, which carry hidden salt regardless of taste. Read labels for sodium and prefer fresh-cooked food where you control the salt. A salt substitute is not automatically safe with heart medicines, so ask your team before using one.
Fluid limits apply only if your team set them; if they did, follow the number they gave and count everything liquid, including milk in tea, soup, and curd. Weighing your usual cup once teaches you what a 'cup' really is. If fluids are restricted, dividing your allowance across the day, sipping slowly, and rinsing your mouth with cold water for dry mouth all make it livable.
Balance this with a heart-friendly plate built on vegetables, whole grains, dal, fish or lean protein, and fruit for dessert. Keep your diuretic and other heart medicines on schedule even on days you feel fine, because they are doing quiet work. Attend every follow-up, and call your team for increasing breathlessness on less activity than before, new swelling in ankles or belly, needing more pillows to sleep, a cough that worsens lying flat, or that weight-trend trigger. Early calls are the difference between a phone adjustment and an emergency admission.""",
        ["heart failure", "daily weight", "salt", "fluid restriction"],
    ),
    chunk(
        "After a heart procedure: diet and activity basics",
        "guideline", "diet",
        """Recovery after a heart procedure such as angioplasty or bypass follows a steady pattern, and the plan your cardiac team gave you leads; these are the supporting habits behind it. For the first days, keep the wrist or groin puncture site clean and dry, avoid lifting with that arm or straining, and follow the puncture-specific instructions on bruising — a coin-sized bruise is common, a growing, painful, or pulsing swelling is a same-day call.
Walking starts almost immediately and grows steadily: short flat walks several times a day, extending by a few minutes every couple of days, guided by the talk test and your team's milestones. Avoid pushing, pulling, and lifting heavy loads, vigorous sports, and driving until your team clears you — timing varies by procedure and your recovery. Climb stairs slowly if allowed. Sexual activity can usually resume when you can climb two flights of stairs comfortably without chest symptoms; ask at follow-up rather than guessing.
The food pattern that protects your heart is the same one that protects your recovery: plenty of vegetables and fruit, whole grains, dal and legumes, fish a few times a week if you eat it, nuts in small handfuls, and healthy oils like mustard, groundnut, or olive in moderation. Cut back hard on fried food, sweets, sugary drinks, refined flour, and processed or red meat, and keep added salt low for blood pressure. If you smoke or use tobacco in any form, quitting is the single most powerful step available to you — ask your team for help; cessation support genuinely works.
Take every heart medicine exactly as prescribed even when you feel entirely well; these medicines prevent the narrowing from returning. Know the red flags: chest pain or pressure, breathlessness out of proportion to effort, palpitations with dizziness, or fainting need emergency care, not a wait for the next clinic. Cardiac rehabilitation, if offered, is strongly worth attending — it turns advice into a supervised, confident routine.""",
        ["angioplasty", "bypass", "cardiac diet", "puncture site"],
    ),
    chunk(
        "Cardiac rehabilitation and building heart-safe activity",
        "guideline", "activity",
        """Cardiac rehabilitation is a supervised program of gradually increasing exercise plus education about food, medicines, and stress, designed for people recovering from heart attacks, procedures, and heart surgery. If your team offered it, attend; people who complete it recover faster, feel more confident, and stay out of hospital more often. If it was not offered, ask whether a home-based walking plan with clear milestones can serve the same purpose.
The core idea is progressive loading: begin with comfortable, flat, slow walks of ten to fifteen minutes, add five minutes every few days, and only add pace or gentle slopes after weeks, not days. Keep the talk test as your regulator — conversational breathing means safe effort; gasping means slow down. Warm up with five easy minutes, and cool down the same way; sudden sprints and heavy lifting are off the menu until your team approves them.
Track your walking in a notebook or phone: minutes, distance or steps, and how you felt. Patterns in that record let your team adjust medicine and milestones intelligently at follow-up. Stop and rest for any chest discomfort, pressure, unusual breathlessness, palpitations with light-headedness, or dizziness; symptoms that appear with effort and settle with rest must still be reported the same day, because 'it went away' is exactly what your team needs to know about. Chest pain that does not settle within minutes of stopping is an emergency call.
Beyond exercise, the rehab mindset covers the whole day: break heavy chores into small pieces, rest half an hour after meals before activity, avoid exertion in extreme heat or cold, and pace emotionally demanding conversations and commutes in the early weeks. Aim for a rhythm — activity, rest, activity — rather than boom-and-bust days that leave you wiped out tomorrow. Steady beats heroic in cardiac recovery, every single time.""",
        ["cardiac rehab", "progressive walking", "effort pacing"],
    ),
    chunk(
        "Diabetes after discharge: a steady-eating pattern",
        "guideline", "diet",
        """While your diabetes team's plan leads, a few steady eating habits make sugars easier to manage during any recovery. Anchor three meals at regular times, because skipping meals and then eating large ones swings sugars unpredictably, especially with diabetes medicines. Build each plate half vegetables, a quarter protein — dal, eggs, fish, chicken, paneer, curd — and a quarter whole-grain starch such as roti from whole wheat, brown rice, millets, or oats. This balance slows glucose rise and keeps you full.
Favor whole fruit over juice; the fiber matters. Keep sweets, fried snacks, sugary drinks, and refined flour portions small and occasional rather than banned-and-binged. If you use insulin or sugar-lowering tablets that can cause lows, eat at consistent times and never skip a meal after taking them; carry a fast-sugar source — glucose tablets, a small juice box, or sugar sachets — in your pocket and your bedside drawer, and tell family where it is.
Recovery changes appetite, so if you cannot finish meals, eat small frequent portions and favor the protein, because healing needs it; a few days of imperfect sugars with good protein beats starvation during healing. Drink water steadily; dehydration concentrates sugars. And keep moving with the gentle activity your team approved, since even light walking after meals lowers post-meal sugar spikes meaningfully.
Check your sugars as often as your team asked and log them — during recovery, illness, and new medicines, patterns shift and the log is how your team adjusts intelligently. Call your team if sugars run persistently higher or lower than your target range, if you cannot keep food down, or if you are unsure how a new medicine interacts with your diabetes plan. Recovery is not the moment for dietary heroics; it is the moment for boring, steady, well-timed meals, which is precisely what good sugar control looks like.""",
        ["diabetes diet", "plate method", "meal timing", "fast sugar"],
    ),
    chunk(
        "Diabetes sick-day rules when you are recovering from illness",
        "guideline", "diet",
        """Illness and recovery raise blood sugars even when you are not eating normally, because stress hormones fight insulin. Sick-day rules are the plan for exactly that situation, and if your diabetes team gave you one in writing, follow it; if not, ask for one at your next contact. The general shape is this.
Do not stop your diabetes medicines or insulin during illness unless your written plan or your team explicitly says so; skipping them during stress is the most common way recovery turns into a crisis. Continue taking them even with reduced eating, adjusting only per your written plan. Check sugars more often than usual — commonly every four hours during active illness — and if you use ketone strips or your meter reads ketones, check as instructed.
Keep drinking fluids steadily, aiming for small sips every fifteen to thirty minutes if nausea limits you; water, clear soups, coconut water, and weak tea all count. If eating is hard, replace meals with easier carbohydrate in similar amounts — khichdi, curd rice, toast, fruit, milk — since you still need glucose while your medicines are working. Rest, and treat fever normally with the medicines your team approved.
Call your diabetes team the same day if sugars stay much higher than your target despite following the plan, if you are vomiting and cannot hold fluids, if ketones are moderate or large, if you develop rapid breathing, fruity-smelling breath, belly pain, or confusion, or if you are simply unsure what to do — that is precisely what the phone is for. Emergency care is needed for confusion or drowsiness, vomiting that will not stop, or severe breathing difficulty. Recovering from one illness should not cost you a second admission; sick-day rules are short, simple, and exist to prevent exactly that trade.""",
        ["sick day rules", "ketones", "hyperglycemia", "hydration"],
    ),
    chunk(
        "Diabetic foot care and safe activity during recovery",
        "guideline", "activity",
        """Feet deserve daily attention during recovery, particularly with diabetes, when reduced sensation and slower healing turn small problems into large ones. Inspect both feet every single day — tops, soles, between toes, heels — using a mirror or a helper. Look for cuts, blisters, redness, swelling, warm spots, calluses with dark discoloration, ingrown nails, and anything new. If you find a break in the skin, clean it with mild soap and water, cover it with a clean dressing, and watch it daily; any wound on a diabetic foot that is not clearly closing within a day or two deserves a call to your care team.
Protect feet mechanically: never walk barefoot indoors or out, check inside shoes with your hand before wearing for hidden objects, wear clean dry socks, and trim nails straight across — better yet, have family or the clinic do it if vision or reach is limited. Do not use hot water bottles, heating pads, or very hot baths on feet, since nerves that cannot feel a blister also cannot feel a burn; test water with your elbow. Avoid self-treating corns or calluses with sharp tools or chemical removers.
For activity, choose foot-friendly exercise: walking in well-fitting shoes is excellent if your feet are intact, while swimming or cycling may suit painful or healing feet — ask your team which fits your situation. Stop any activity that creates a red or hot spot on the foot, and treat that spot as information, not weakness.
Seek urgent care for a foot wound with spreading redness, pus, swelling that climbs up the leg, black tissue, fever, or pain that becomes severe in a foot that used to feel nothing. Routine foot checks at every follow-up, and annual full foot examinations, catch problems years earlier than symptoms do. Your feet carry the whole recovery; ten minutes of daily attention is the cheapest insurance in this entire document.""",
        ["diabetic foot", "inspection", "barefoot", "footwear"],
    ),
    chunk(
        "COPD at home: breathing techniques and energy conservation",
        "guideline", "activity",
        """With COPD, breathlessness during recovery is managed with technique as much as medicine, and two techniques repay daily practice. Pursed-lip breathing: inhale gently through the nose for two counts, then exhale slowly through pursed lips — as if whistling — for four counts, letting the exhale be longer than the inhale. It keeps airways open longer and empties the lungs better, and it works best exactly when you feel breathless. Diaphragmatic breathing: with a hand on your belly, breathe in through the nose so the hand rises, then exhale slowly. Ten minutes twice a day builds these into reflexes you can call on when it counts.
Match breathing to effort: exhale during the strain of any action — standing up, lifting a kettle, climbing a step — and never hold your breath during effort. For climbing stairs, breathe out with each step or two and rest halfway if needed; there is no prize for reaching the top gasping.
Energy conservation is a skill, not laziness. Sit for showers and cooking, wear a robe rather than toweling vigorously, lay out clothes the night before, cook double portions and freeze half, keep frequently used items at waist height to avoid bending and reaching, and pace the day as activity-rest-activity. Use your rescue inhaler as prescribed before activities that usually trigger breathlessness if your plan says so, and keep it with you always.
Clear mucus with the techniques your physiotherapist taught, drink fluids unless restricted to keep sputum manageable, and take your inhalers with correct spacer technique — ask the nurse to watch you use it once; nearly everyone improves with one correction.
Call your care team for sputum that turns thicker, darker, or more copious, increasing breathlessness over hours to days, needing your reliever inhaler more often than usual, or new fever. Seek emergency care for severe breathlessness at rest, bluish lips or fingertips, confusion or drowsiness, or a reliever that is not helping. Early calls during a flare shorten it; waiting lengthens it.""",
        ["COPD", "pursed lip breathing", "energy conservation", "inhaler"],
    ),
    chunk(
        "Recovering from pneumonia: rebuilding your lungs and strength",
        "guideline", "diet",
        """Pneumonia recovery continues for weeks after you feel 'over the infection', and the fatigue that surprises most people is normal — your body is repairing lung tissue and clearing debris while also rebuilding fitness lost during bed rest. Expect tiredness to lift gradually over two to six weeks; plan lighter days and do not judge yourself against your pre-illness pace yet.
Breathing exercises are the backbone of lung recovery. Practice deep breathing several times daily: sit upright, breathe in slowly through your nose as fully as comfortable, hold for a couple of counts, and exhale slowly and completely. Follow with ten gentle huffs — a short forceful breath out with an open glottis, as if fogging a mirror — to help move any remaining mucus. Use the incentive spirometer you were given, if you were given one, ten times an hour while awake in the first days, then as advised. Change position regularly and get up for short walks; bed rest and silent sitting both let mucus settle.
Eat to rebuild: protein at every meal for tissue repair, fruit and vegetables for vitamins, and steady fluids — unless your team restricted them — to keep mucus thin and easy to clear. Small frequent meals beat large ones when breathing is still effortful, since a full stomach pushes on the lungs; rest briefly after eating.
Take the full antibiotic course exactly as prescribed even once you feel better, attend the follow-up chest review, and keep every appointment for repeat imaging if asked. Get the vaccines your team recommends, typically flu and pneumococcal, since repeat pneumonia is preventable.
Call your care team for fever returning, cough worsening again, sputum turning green or rust-colored, breathlessness increasing, or chest pain with breathing. Emergency care is needed for severe breathlessness at rest, bluish lips, confusion, or drowsiness. Slow and steady fully recovers pneumonia; pushing hard early reliably backfires.""",
        ["pneumonia", "breathing exercises", "fatigue", "vaccines"],
    ),
    chunk(
        "Home oxygen: safety and practical basics",
        "guideline", "activity",
        """If you went home with oxygen, a few rules keep you safe and comfortable, and they mostly reduce to one idea: oxygen makes everything burn faster and hotter. Keep oxygen equipment at least two meters from open flames — candles, stoves, agarbatti, diyas, gas burners — and never smoke or let anyone smoke in the room or near the equipment, including e-cigarettes. Keep oxygen tubing away from kitchen flames entirely; many people remove the cannula and step away from any cooking flame, then reconnect afterward.
Do not use petroleum-based creams near your face with oxygen; water-based moisturizers are safe. Avoid aerosol sprays nearby. Keep the concentrator in a ventilated space, not closed in a cupboard, keep filters clean per the manual, and have a backup plan — a spare cylinder and the supplier's emergency number — for power cuts. Do not adjust your oxygen flow rate yourself; the prescribed rate is a medical decision. If breathlessness is not relieved at your prescribed rate, call your care team rather than turning the dial.
Practical comfort matters just as much. Cannula tubing irritates ears and cheeks; soft foam covers help. Humidify the air you breathe if your equipment supports it, since oxygen dries the nose; saline nasal drops ease dryness. Keep tubing untangled with slack for walking, and coil it safely at night to avoid trips. Keep a list of your oxygen settings, supplier contacts, and backup cylinder location where family can find it.
Use oxygen exactly as prescribed, including during sleep if prescribed — many people under-use night oxygen because they feel fine, but the prescribed hours protect the heart. Travel needs planning: notify the airline or railway in advance, carry prescriptions, and never store cylinders in a hot car boot. Call your team for breathlessness at your prescribed rate, new headaches on waking, unusual drowsiness, or confusion — these can signal that settings need review. And keep every follow-up; oxygen needs are re-checked, not assumed.""",
        ["oxygen safety", "fire", "concentrator", "cannula"],
    ),
]
