"""General medication-adherence guidance (spec §10) — deliberately generic,
never drug-specific dosing."""

from seed import chunk

CHUNKS = [
    chunk(
        "Why finishing the full course matters",
        "guideline", "medication",
        """Courses of medicine, especially antibiotics, are prescribed for a length of time chosen to fully clear the problem, not just to make you feel better. Stopping early because symptoms improved is one of the most common reasons illness returns, sometimes stronger than before, and is part of how resistance develops. Unless your prescriber or pharmacist explicitly told you otherwise, finish the course exactly as written, at the stated times, for the stated number of days.
The same principle applies to most discharge medicines. Blood pressure medicines, heart medicines, and stomach-protecting medicines are usually long-term protectors, not short-term fixes. They work silently, so feeling fine is not evidence they are unnecessary. If a medicine seems to cause side effects, the correct move is a call to your care team or pharmacist to adjust it, not a quiet decision to skip it.
Practical tricks make courses easier to finish: count out the days on a calendar and tick each dose; keep the box somewhere visible next to something you do daily, like the kettle or your toothbrush; set phone alarms; and ask a family member to give you a nudge on the days you are likely to forget. If you realize you have been taking it wrong, do not double up to catch up — call your pharmacist and ask how to restart correctly.
Running out early is a logistics problem with a simple fix: request the refill several days before the last dose, and tell your care team if cost, transport, or pharmacy access is the barrier, because they can often solve it. If you simply cannot keep a medicine down because of vomiting, or you are told before a procedure to pause it, ask precisely when to restart. Your discharge instructions and the medicine label are the source of truth; when they seem to disagree, a quick call settles it in minutes.""",
        ["adherence", "course completion", "antibiotics", "refill"],
    ),
    chunk(
        "Missed a dose? The general rules",
        "guideline", "medication",
        """Almost everyone misses a dose at some point, and there is a safe general way to respond. First, do not panic and do not double up. Taking two doses together can be more risky than missing one, particularly for medicines that affect the heart, blood sugar, or bleeding. The usual pattern, which applies to most but not every medicine, is: if you remember soon after the missed time, take it straight away; if it is nearly time for the next dose, skip the missed one and continue with the normal schedule. Your pharmacist can tell you in one sentence exactly which rule applies to each of your specific medicines, so it is worth asking while you collect them.
Build a habit that catches misses before they happen. Keep a simple written or phone checklist for each medicine and tick as you go; the tick list turns 'I think I took it' into 'I know I took it'. Morning-and-evening medicines pair well with fixed anchors like breakfast and brushing teeth. Weekly medicines deserve a specific calendar day and an alarm. Pill organizers, filled weekly by you or a family member, remove the daily guesswork entirely and are inexpensive at any pharmacy.
Some situations need a call rather than a guess: if you have missed two or more doses in a row, if the medicine is for a serious condition such as heart failure, seizures, or blood thinning, or if you feel unwell after missing it. Tell your care team honestly how many doses were missed and when; they would far rather give you a safe restart plan than have you improvise. And if the reason you missed doses is side effects, cost, or simply forgetting because the schedule is confusing, say so — schedules can be simplified, substitutes exist, and no one is judging. The goal is steady protection, and steady is achieved with systems, not willpower.""",
        ["missed dose", "double dose", "pill organizer", "routine"],
    ),
    chunk(
        "Building a medication routine you will not forget",
        "guideline", "medication",
        """Remembering several medicines a day is a system problem, not a memory contest. Start by listing every medicine with its times, then group them around anchors you never skip: waking up, breakfast, lunch, dinner, and bedtime. Write the final schedule on one sheet and stick it where the medicines live. Most people find that two or three anchor points beat five scattered ones; your pharmacist can often suggest timing adjustments that safely cluster your medicines.
Use a weekly pill organizer with morning, afternoon, evening, and night compartments, and fill it the same day every week, perhaps Sunday evening after dinner. The filling ritual doubles as a stock check: you discover early when a box is running low instead of on the last pill. Keep the organizer visible, not in a drawer; bathroom cabinets are actually a poor home because humidity affects some medicines, so a kitchen shelf away from the stove or the bedside table usually works better.
Technology helps if you let it: phone alarms labeled with the medicine name, medication reminder apps with tick-boxes, or a simple wall calendar with a square to cross off each day. Pair the routine with someone else when possible; a spouse, adult child, or neighbor who asks 'did you take your morning tablets?' doubles reliability without any effort.
Travel and routine changes cause most lapses, so plan them: carry medicines in hand luggage in original boxes, set alarms for the destination time zone, and keep a one-day spare in a separate bag. When you come home from hospital with new medicines alongside old ones, do a spring clean: ask the pharmacist which old medicines to stop, and remove them from the organizer so nothing gets taken twice. A tidy system takes an hour to build and quietly protects every day after.""",
        ["routine", "adherence system", "reminders", "travel"],
    ),
    chunk(
        "Reading your medicine label and discharge instructions",
        "guideline", "medication",
        """Your medicine label is a compact instruction sheet, and reading it carefully prevents most medicine mistakes. It tells you the medicine name and strength, who it is for, how much to take each time, how often, and any special timing such as with food, on an empty stomach, or at bedtime. It may also carry warnings like 'may cause drowsiness' or 'avoid alcohol'. Check these five things every time you start a new box: the name matches your list, the strength matches, the frequency matches, the timing note is followed, and the expiry date has not passed.
Discharge instructions may use different words than the label, for example 'twice daily' versus the label's 'every 12 hours'. Usually they match, but if the instructions say one thing and the label seems to say another, call your pharmacist before adjusting anything; mismatched instructions are usually simple to resolve and risky to guess. Keep the patient information leaflet in the box; it lists common side effects and when to seek help.
Learn the difference between the brand name and the chemical name, because pharmacies sometimes substitute a generic version that looks different but is the same medicine. A different color or shape after a refill is normal; the active name on the box is what matters. If your box looks genuinely unfamiliar, show the pharmacist rather than assuming.
Keep one master list of all your medicines, including eye drops, inhalers, patches, injections, vitamins, and herbal or Ayurvedic products, since these interact too. Update the list whenever anything changes and carry a copy in your wallet; every doctor you meet will ask for it, and in an emergency it speaks for you. Photograph the list and the labels of new medicines when you get home from hospital — it takes two minutes and gives you a reference for every later question.""",
        ["label", "generic", "master list", "instructions"],
    ),
    chunk(
        "Vomited a dose, or took an extra dose by mistake",
        "guideline", "medication",
        """Two awkward situations happen to nearly everyone, and both have calm answers. If you vomit shortly after taking a dose, the medicine may not have absorbed. General practice is not to retake immediately, because you cannot know how much was absorbed, and doubling risks side effects; instead, note the time it happened and continue with the next scheduled dose as normal. If vomiting is repeated, that is a separate problem: contact your care team, both because you are losing doses and because repeated vomiting after discharge matters on its own. They may prescribe an anti-sickness medicine or adjust timing.
If you accidentally take an extra dose or two doses too close together, do not wait for symptoms to decide what to do. For most everyday medicines one extra tablet is reassuringly tolerable, but for medicines affecting the heart, blood sugar, blood clotting, or breathing, an extra dose can matter quickly. Call your pharmacist, doctor, or the poison/emergency advice line for your area, tell them the medicine name, strength, how many extra, and when, and follow their instructions. Watch for warning signs in the hours after: unusual drowsiness, racing or pounding heartbeat, dizziness, unusual bleeding, sweating with shakiness, or breathlessness; any of these needs prompt medical attention.
Practical prevention: use a pill organizer so 'did I take it?' becomes visible, take medicines in the same well-lit place rather than in the dark, and never take medicines directly from bottle to hand at bedtime without checking the day's tick-list first. Keep the phone number of your pharmacy saved under 'pharmacy' so help is one tap away. Honest reporting matters more than embarrassment — pharmacists answer questions like this many times a day, and no question about a possible double dose is ever a silly one.""",
        ["vomiting", "double dose", "overdose caution", "pharmacist"],
    ),
    chunk(
        "Storing medicines safely at home",
        "guideline", "medication",
        """Medicines quietly lose strength when stored badly, and home storage is also a child-safety issue. Store most medicines in a cool, dry place away from direct sunlight; a high kitchen shelf or a locked bedside drawer is usually better than the bathroom, where showers create heat and humidity that degrade tablets and labels. Refrigerate only what the label says to refrigerate, such as some insulins, eye drops, and syrups; never freeze them, and keep them off the door shelf where temperature swings are largest.
Keep everything in original packaging with the label attached, including boxes for blister strips. Original packaging carries the name, strength, expiry date, and batch information you or a doctor may need later. Decanting pills into unmarked organizers or bowls leads to mix-ups; fill the weekly organizer instead and return bottles to their place immediately.
Child and pet safety deserves real attention: medicines belong up high, out of sight, and ideally in a locked box, because children are natural climbers and gummy vitamins look like sweets. Never call medicine 'candy' to persuade a child to take it. Keep the poison-control number for your area saved in your phone.
Check expiry dates every three to six months and return expired or leftover medicines to a pharmacy for safe disposal; do not bin them loose or flush them down the toilet, and never keep old medicines 'just in case' — leftovers invite accidental double-dosing and wrong-medicine mistakes. If a medicine changes color, smells odd, grows fuzz, or its tablets stick together, do not take it, even before its expiry date. Heat, damp, and time are the three enemies of medicine strength, and a little organizing defeats all three. Finally, if anyone in the house depends on critical daily medicine, keep a small emergency spare supply in a separate, labeled place in case a bag is lost or travel delays a refill.""",
        ["storage", "expiry", "child safety", "disposal"],
    ),
    chunk(
        "Blood thinners: general safety points",
        "guideline", "medication",
        """Blood-thinning medicines protect you from dangerous clots, and they work by making it slightly harder for blood to clot anywhere — which is why small lifestyle cautions matter with them. These are general points; your own prescriber's instructions always come first.
Take your thinning medicine exactly as prescribed, at the same time each day, and never double up after a missed dose without asking; the missed-dose rule for these medicines specifically should come from your pharmacist. Keep every follow-up blood test you are asked for, because some thinners need monitoring and dose adjustment based on results.
Watch for the signs that your blood is being thinned more than intended and tell your care team promptly: unusual or large bruises, bleeding gums when you brush, frequent nosebleeds, blood in urine making it pink or red, black or tarry stools, or heavy bleeding from small cuts that will not stop with ten minutes of firm pressure. Seek emergency care for bleeding that will not stop, a head injury of any kind — even a minor bump days ago followed by headache, drowsiness, confusion, or vomiting — or coughing or vomiting blood.
Tell every dentist, surgeon, and pharmacist that you take a blood thinner before any procedure, tooth extraction, or new medicine, including over-the-counter painkillers and herbal or Ayurvedic supplements, because several interact with thinning medicines. Use a soft toothbrush and an electric razor to reduce small bleeds, wear shoes outdoors, and take care with sharp kitchen work. Falls matter more on thinners: clear loose rugs, use night lights, and ask for a falls review if you feel unsteady. Carry a card or phone note stating you take a blood thinner, and mention it at every appointment. With these habits, thinners are among the most protective medicines you can be on, and the cautions quickly become routine.""",
        ["blood thinner", "anticoagulant", "bleeding signs", "procedures"],
    ),
    chunk(
        "Insulin and diabetes medicines: general adherence points",
        "guideline", "medication",
        """Diabetes medicines, including insulin, only work when they are taken consistently, so steadiness is the whole game. These general points support whatever plan your diabetes team has set; they do not change any dose they prescribed.
Build injections or tablets into fixed daily anchors — waking, breakfast, dinner, bedtime — and keep glucose tablets or a small sugar source with you, wherever you go. Rotate injection sites within the areas your team showed you to keep skin healthy, and use a new needle each time; reusing needles dulls them and hurts more. Store unopened insulin in the fridge and the pen you are using at room temperature away from heat and sunlight, and never use insulin that is cloudy when it should be clear or discolored in any way. Do not share pens, needles, or lancets with anyone, ever.
Know your personal low-sugar warning signs — usually shakiness, sweating, sudden hunger, blurred vision, confusion, or a racing heart — and treat lows promptly with fast sugar, then follow the plan your team gave you. If lows are happening more than rarely, that is a message about dose or timing that your team needs to hear, not something to manage alone by skipping medicine.
Sick days need a plan agreed in advance: when you are ill, sugars often behave unpredictably, so ask your team for written sick-day rules covering what to keep taking, what to check, and when to call. Never stop diabetes medicine during illness without that guidance. Keep a written list of your medicines and doses in your wallet and show it at every appointment. Bring your glucose log or app to reviews, because patterns there drive better dose decisions than memory. And if cost, technique, or side effects are making you skip doses, tell your team — adjustments exist, and adherence problems have practical solutions when they are spoken aloud.""",
        ["insulin", "diabetes", "hypoglycemia", "sick day rules"],
    ),
    chunk(
        "Pain relief after discharge: using it safely",
        "guideline", "medication",
        """Good pain control after discharge is not just comfort — it lets you breathe deeply, sleep, walk, and heal faster. The goal is a steady, tolerable level of pain, not zero, and usually the prescribed schedule works best in the first days rather than waiting until pain is severe and then chasing it.
Take pain medicine exactly as prescribed, with food if the label says so, and do not combine different painkillers on your own, because several contain the same active ingredient under different brand names and doubling up harms the liver or stomach. If your plan includes strong opioid-type painkillers, use them only as prescribed, never with alcohol, never drive while taking them, and expect constipation — ask early for the stool-softening plan rather than waiting for the problem. Keep them locked away from children and visitors, and dispose of leftovers at a pharmacy once you no longer need them.
Know what your pain should look like: it should trend downward day by day. Pain that suddenly intensifies, pain that becomes sharp with fever, pain with new swelling or redness, or pain that no medicine touches are not 'more of the same' — they are a reason to contact your care team that day. Pain in the calf with swelling, chest pain, or new severe headache belong to the urgent categories and need prompt assessment.
Non-medicine helpers multiply the effect of every tablet: regular short walks, elevating a swollen area, ice packs wrapped in cloth over sore muscles for fifteen minutes at a time, deep breathing exercises, and simply pacing your day so the hardest tasks come when medicine is working at its peak. If pain stops you sleeping for more than two nights, or you find yourself taking extra doses beyond the plan, call your care team — adjusting the plan is normal, easy, and exactly what follow-up is for.""",
        ["pain relief", "opioid safety", "constipation", "pain trend"],
    ),
    chunk(
        "Never stop suddenly, never share, never save leftovers",
        "guideline", "medication",
        """Three quiet habits cause a large share of medicine trouble after discharge, and all three are easy to fix once named. First, never stop a prescribed medicine suddenly just because you feel better, unless your prescriber told you it was short-term. Several classes — steroids, blood pressure and heart medicines, antidepressants, seizure medicines, and acid-suppressing medicines among them — can rebound badly when stopped abruptly: steroids need tapering, stopping blood pressure medicines can cause spikes, and stopping seizure medicines risks seizures. If side effects or cost are the reason you want to stop, call your care team; there is almost always a taper, a substitute, or a schedule fix.
Second, never share prescription medicines, and never take someone else's, even a close relative with 'the same problem'. Doses are chosen for your body, your kidneys, your other medicines, and your diagnosis; borrowed medicine is a guess with side effects, and leftover antibiotics from an old illness may be the wrong drug entirely for a new one.
Third, do not save leftover course medicine 'for next time'. Illnesses that feel identical can need different treatment, expired or badly stored medicine loses strength, and duplicates lurking in cupboards cause accidental double-dosing. Return leftovers to a pharmacy for safe disposal and start each course fresh from a labeled box.
One more silent trap: restarting an old medicine yourself after a hospital admission changed your list. Keep the single master list your team gave you, cross off what was stopped, and when in doubt about any item, call before you take. The pattern behind all three rules is the same: medicines are safe within the plan written for you, and every departure from that plan deserves a quick call rather than a quiet decision. Your care team can adjust almost anything; what they cannot do is adjust a plan they do not know you left.""",
        ["stopping suddenly", "sharing medicine", "leftovers", "medication list"],
    ),
]
