"""Red-flag symptom lists per diagnosis category (spec §10), matching the
categories the ARIA risk engine uses. Every chunk ends with the same rule:
emergency signs -> emergency services, not chat."""

from seed import chunk

CHUNKS = [
    chunk(
        "Cardiac red flags: symptoms that need emergency care now",
        "guideline", "red_flags",
        """Certain symptoms after any hospital stay — and especially with any heart condition — are emergency signs, and knowing them cold is protective. Call emergency services immediately for: chest pain, pressure, tightness, or heaviness that lasts more than a few minutes, or that comes and goes; pain spreading to the jaw, neck, either arm, shoulder, or back; chest discomfort together with sweating, nausea, or a feeling of impending doom; breathlessness at rest or on tiny effort that is new or clearly worse than usual; fainting or near-fainting; a racing, pounding, or irregular heartbeat with light-headedness or chest discomfort; or sudden overwhelming fatigue with cold sweat.
Do not drive yourself or have family drive you if an ambulance is available — ambulances can begin treatment on the way, and paramedics need to know what they are dealing with. If advised by your care team and it is within your plan, chew one adult aspirin while waiting for the ambulance unless you have been told not to take it; when in doubt, ask the emergency dispatcher on the phone, who will guide you.
Symptoms that are concerning but not necessarily emergency-level still deserve a same-day call to your care team: chest discomfort that is clearly tied to a strained muscle or a cough and changes with position or pressing on the spot; new palpitations that settle quickly; ankle swelling by evening that resolves overnight; needing two pillows instead of one to sleep comfortably; or weight gain of around two kilograms over two or three days. Describe exactly what you felt, what you were doing, how long it lasted, and what made it better or worse.
The reason over-calling is safe: heart problems treated early have dramatically better outcomes, and the evaluation is quick and harmless. Nobody regrets the false alarm; people deeply regret waiting. When your chest is involved and you are not sure — that uncertainty itself is the indication to call.""",
        ["chest pain", "cardiac emergency", "aspirin", "ambulance"],
    ),
    chunk(
        "Breathing red flags: when breathlessness is an emergency",
        "guideline", "red_flags",
        """Some breathlessness is ordinary recovery — being more tired than before, feeling winded on stairs you used to take easily — and improves week by week. Other breathlessness is an emergency, and the difference is speed, severity, and company it keeps. Call emergency services immediately for: sudden severe breathlessness or struggling to breathe; breathlessness at rest that does not settle within a few minutes of sitting still; breathlessness with chest pain or pressure; breathlessness with coughing up blood; breathlessness with bluish or grayish lips, fingertips, or face; breathlessness with high fever and confusion; gurgling or inability to speak full sentences; or breathlessness in someone becoming drowsy or hard to rouse.
Call your care team the same day, urgently but not by ambulance, for: breathlessness that is clearly worse than yesterday and continuing to worsen; new wheezing not relieved by your reliever inhaler; needing to sleep upright in a chair because lying flat brings on breathlessness; breathlessness with one calf that is painful, swollen, and warm, which together can indicate a clot that has traveled to the lungs; or a reliever inhaler that is being used far more often than prescribed.
While waiting for help: sit upright, lean slightly forward with arms supported on a table, loosen tight clothing, use your prescribed reliever inhaler as directed, and practice pursed-lip breathing. Keep doors open for airflow and stay calm — anxiety multiplies the sensation of breathlessness, and someone speaking calmly to you genuinely helps.
If you use home oxygen, do not increase the flow yourself beyond your prescribed rate; call instead. Anyone with breathing difficulty that is new, severe, or rapidly getting worse should be seen by professionals without delay — breathless patients should not wait at home to see whether it passes, because with breathing, hours matter more than with almost any other symptom.""",
        ["breathlessness", "respiratory emergency", "inhaler", "clot"],
    ),
    chunk(
        "Bleeding and wound red flags after surgery",
        "guideline", "red_flags",
        """Most surgical wounds ooze a little in the first day and then settle; the skill is telling that from bleeding that needs action. Seek emergency care immediately for: bleeding that soaks through dressings and does not stop after ten minutes of firm, continuous pressure with clean gauze or cloth; blood that is spurting or gushing; vomiting blood or material that looks like coffee grounds; coughing up blood in more than a trace; black, tarry stools or visible blood with dizziness, fast heartbeat, or pale clammy skin; bleeding with confusion, severe drowsiness, or fainting; or a wound that suddenly opens with visible deeper tissue.
Call your care team urgently the same day for: wound drainage that changes from clear to cloudy yellow or green, smells bad, or increases after the second day; a wound edge that is separating; a small gap that opens after staples or stitches are removed; bleeding that stops with pressure but restarts each time you move; a nosebleed or gum bleeding that recurs repeatedly, especially if you take blood thinners; or a growing, firm, painful bruise, particularly near a groin or wrist puncture site from a heart procedure.
While applying pressure, keep the person still and the part raised if practical; do not keep lifting the dressing to check every minute — hold ten full minutes before assessing. Take blood thinners into account: anyone on anticoagulants gets less benefit of the doubt, and head injuries of any kind on blood thinners need same-day assessment even without visible bleeding, because delayed internal bleeding can appear hours to days later with headache, drowsiness, vomiting, or confusion.
Keep a clean supply of gauze at home before you need it, and photograph any wound change before covering it again — the photo documents progression for your care team. With bleeding, the rule is generous: pressure first, call early, and let professionals decide whether it was necessary.""",
        ["bleeding", "wound red flags", "blood thinners", "pressure"],
    ),
    chunk(
        "Stroke: think F.A.S.T. and call immediately",
        "guideline", "red_flags",
        """Stroke treatment works in minutes, not hours, and the fastest way to protect yourself or someone near you is the F.A.S.T. check, learned once and used instantly: F — Face: ask the person to smile; does one side of the face droop? A — Arms: ask them to raise both arms; does one arm drift downward or feel weak or numb? S — Speech: ask them to repeat a simple sentence; is speech slurred, jumbled, or are they unable to speak? T — Time: if any one of these is present, note the time and call emergency services immediately.
Additional stroke signs count the same way: sudden numbness or weakness on one side of the body; sudden confusion, trouble understanding, or trouble finding words; sudden trouble seeing in one or both eyes; sudden severe headache with no known cause, often described as the worst ever; sudden dizziness, loss of balance, or trouble walking, especially combined with any other sign.
The core principle: do not wait to see whether it passes, even if symptoms vanish after a few minutes. Symptoms that resolve on their own can be a transient ischemic attack — a warning stroke — and it needs same-day assessment to prevent a full stroke. Do not give food, water, or medicines by mouth to someone with stroke signs, since swallowing may be impaired; do not drive yourself; call the ambulance and report 'possible stroke' plus the time symptoms started, because that single time-stamp determines which treatments are available.
Recovery patients and their families: keep this list on the fridge. People recovering from cardiac surgery, diabetes, high blood pressure, or a previous stroke carry higher risk, and strokes during recovery are not rare. The phrase worth memorizing: time is brain. Every fifteen minutes of delay costs recoverable tissue. Any F.A.S.T. sign — even one, even faint, even gone — is an emergency call, every single time.""",
        ["stroke", "FAST", "TIA", "emergency"],
    ),
    chunk(
        "Diabetes red flags: severe low and high blood sugar",
        "guideline", "red_flags",
        """Blood sugar emergencies come in two flavors, and both are serious. Severe low sugar (hypoglycemia): shakiness, sweating, sudden intense hunger, palpitations, blurred vision, tingling lips, confusion, slurred speech, unusual behavior, drowsiness, seizures, or unconsciousness. If the person can swallow safely, fast sugar first — glucose tablets, half a glass of juice, or three teaspoons of sugar — then recheck in fifteen minutes and repeat if still low, followed by a proper snack once it recovers. If they cannot swallow, are confused enough to resist, are unconscious, or are having a seizure: this is an emergency call, do not put food or liquid in their mouth, roll them on their side, and stay with them. Anyone using insulin should also have glucagon available if their team prescribed it, and family should know where it is and how to use it.
Severe high sugar (hyperglycemia and ketoacidosis): thirst and frequent urination climbing over hours, sugars far above your target despite following the plan, vomiting, belly pain, fruity or nail-polish-smelling breath, deep rapid breathing, and increasing drowsiness or confusion — the last cluster suggests ketoacidosis, which is an emergency call, not a wait-for-morning problem. It can develop even when eating little, during infections, or after missed insulin.
Same-day calls, not emergencies: sugars running consistently above or below target for more than a day or two during recovery, more than one or two mild lows in a week, illness with vomiting but still holding fluids, or any new medicine that seems to be disturbing sugar patterns. Recovery from surgery or illness commonly destabilizes sugars, which is expected and manageable — but it is managed by your team being told, not by you quietly skipping or doubling medicine. Keep your written sick-day rules on the fridge next to the fast sugar, and make sure at least one other person in the house knows both the signs and where the sugar lives.""",
        ["hypoglycemia", "hyperglycemia", "ketoacidosis", "glucagon"],
    ),
    chunk(
        "Blood clots: DVT and pulmonary embolism warning signs",
        "guideline", "red_flags",
        """Recovery after surgery and hospital stays carries an increased risk of blood clots, because you are moving less while your body is also healing and sometimes inflamed. Clots matter in two places: in the deep veins of the leg (DVT) and, if a piece travels to the lungs (pulmonary embolism), where it becomes an emergency.
Learn both pictures. DVT in a leg: swelling of one calf or thigh — measurably bigger than the other; pain or tenderness, often in the calf, that may feel like cramp or soreness; warmth; and skin that looks red or darker than the other leg. The swelling is usually one-sided. Do not massage a suspected clot; note the signs and call urgently the same day.
Pulmonary embolism: sudden breathlessness that is out of proportion to what you were doing, sharp chest pain that is worse with a deep breath, coughing (sometimes with blood), a racing heart, lightheadedness or fainting, and unexplained anxiety. Any of these — especially breathlessness with pleuritic chest pain after a period of less activity — is an emergency call, immediately.
Prevention is unglamorous and effective: take the clot-prevention injections or tablets your team prescribed for exactly as long as prescribed, even when you feel fine; walk frequently, several short walks daily, since calf movement is the pump that prevents stasis; do ankle circles and pump your feet up and down whenever sitting; stay hydrated; avoid long periods sitting with crossed legs; and on any car or flight journey over a few hours, get up and walk every hour and do seat exercises.
Risk climbs with obesity, cancer treatment, prior clots, inherited clotting tendency, estrogen medicines, and long immobilization, so mention any of these at follow-up. And remember the pattern that fools people: DVT can be quiet, so compare calves in the mirror daily during the first weeks — one visibly different leg is a finding, not a quirk.""",
        ["DVT", "pulmonary embolism", "calf swelling", "prevention"],
    ),
    chunk(
        "Sepsis: the signs that need emergency care tonight",
        "guideline", "red_flags",
        """Sepsis is the body's overreaction to an infection, and it is one of the few conditions where hours genuinely decide outcomes. Anyone discharged after surgery, with a wound, a drain, a urinary catheter, or an infection, should know its face. Sepsis usually starts as an infection getting worse, then the whole body joins in.
The combination to fear: fever above 38 C (100.4 F) or alternatively an abnormally low temperature; shaking chills or rigors; heart racing; fast breathing or breathlessness; and — most distinctive — confusion, disorientation, slurred speech, or unusual drowsiness, in a person who may or may not look severely ill otherwise. Skin can become clammy, sweaty, pale, mottled, or develop a rash that does not fade when pressed. Passing much less urine than usual is another red signal. In short: infection plus the body acting strangely equals emergency call, tonight, not tomorrow morning.
The situations that demand extra vigilance: a wound becoming increasingly red, hot, swollen, and painful with pus or red streaks tracking away from it; a drain site or line site looking infected; fever appearing after days of normal temperature; or feeling 'the worst I have ever felt' with chills after any procedure. Elderly people and those with diabetes, kidney disease, or weakened immunity may not mount a fever — in them, new confusion alone with any suspected infection is enough to seek emergency care.
Do not wait for a morning clinic for suspected sepsis, and do not attempt to treat it at home with leftover antibiotics; sepsis moves through the body in hours and needs intravenous treatment, fluids, and monitoring that no home can provide. When you call emergency services, say the word 'sepsis' and describe the infection source. Families: this page is worth reading aloud to everyone in the house, because the person becoming septic is often the least able to recognize it in themselves.""",
        ["sepsis", "rigors", "confusion", "emergency"],
    ),
    chunk(
        "Fever after discharge: what each degree means",
        "guideline", "red_flags",
        """Fever after a hospital stay is a signal worth reading carefully, because its meaning depends on when it comes and what accompanies it. Get a thermometer — guessing by hand-warmth fails precisely when it matters. Normal is roughly 36.5-37.5 C (97.7-99.5 F). Fever means 38 C (100.4 F) or above, measured at least twice, ideally thirty minutes apart.
Same-day call to your care team for: any fever of 38 C or above in the first days after surgery, since wound, urine, chest, and line infections announce themselves this way; fever with a wound that is redder, hotter, more swollen, or leaking; fever with worsening cough, breathlessness, or phlegm; fever with burning on passing urine or new back pain; fever with a drain in place; fever with diarrhea or vomiting lasting beyond a day; or fever that returns after having settled, which often marks a new infection beginning.
Emergency care, immediately, for: fever above 39.5 C (103 F) that does not come down with paracetamol as prescribed; fever with shaking chills and rigors; fever with confusion, unusual drowsiness, or a stiff painful neck; fever with breathlessness at rest; fever with a spreading skin rash or red streaks; fever in someone whose immunity is lowered (chemotherapy, transplants, strong steroids) — for this group, even 38 C counts as urgent; or fever with severe headache and vomiting.
Meanwhile, support comfortably: prescribed paracetamol per its schedule, steady fluids since fever dries you out, light clothing, and rest. Do not double up fever medicines that may share ingredients, and do not use ice baths or alcohol rubs. Track the numbers with times on paper — a fever chart of even two days tells your team far more than 'I had fever'. In short: fever plus recovering surgery plus feeling unwell is never 'just a virus until proven otherwise'; it is a reason to call and let professionals decide.""",
        ["fever", "thermometer", "infection", "fever chart"],
    ),
    chunk(
        "Dehydration from vomiting or diarrhea: danger signs",
        "guideline", "red_flags",
        """Vomiting and diarrhea after discharge are usually brief and self-limiting, but they carry two risks during recovery: dehydration, and the loss of important medicines you cannot keep down. Knowing the danger signs keeps a nuisance from becoming an admission.
Watch for dehydration climbing in this order: increased thirst and dry mouth; urine becoming dark and scant — the toilet is your gauge, and dark amber with long gaps between visits is a warning; tiredness and dizziness on standing; sunken eyes; and in older people especially, new confusion. For children — if you are caring for one — add no tears when crying, sunken fontanelle, and unusual sleepiness. Rehydration is the treatment: small sips of oral rehydration solution every few minutes — sachets from the pharmacy mixed exactly as instructed — rather than large gulps that bring everything back up. Rest the stomach for an hour after the last vomit, then start sipping. Once fluids hold, return to bland foods: rice, curd, banana, toast.
Emergency care is needed for: vomiting or diarrhea that will not let you keep even sips down for twenty-four hours; signs of moderate or severe dehydration as above; blood in vomit or stool; severe abdominal pain; vomiting with a hard, swollen, painful abdomen or complete inability to pass gas; high fever with the vomiting; confusion or inability to stay awake; or more than six to eight loose stools in a day not improving after two days.
Two special cautions: first, if you take diabetes, heart, or blood-pressure medicines and cannot keep them down, call your team the same day — some need replacing, some need pausing, and the decision should not be guessed. Second, keep hand hygiene strict and isolate towels, since several stomach bugs travel through households. Recovery from surgery plus a stomach bug is a poor combination; early rehydration and an early call keep it minor.""",
        ["dehydration", "ORS", "vomiting", "diarrhea"],
    ),
    chunk(
        "Medication reaction warning signs",
        "guideline", "red_flags",
        """New medicines after discharge occasionally cause reactions, and distinguishing an inconvenient side effect from a dangerous one is genuinely lifesaving knowledge. Seek emergency care immediately for: any swelling of the face, lips, tongue, or throat; difficulty breathing or a feeling of the throat closing; widespread hives with breathlessness or faintness — this cluster suggests a severe allergic reaction (anaphylaxis) and minutes count; widespread blistering or peeling of skin, or a rash with painful mouth or eye ulcers and fever, which can indicate severe drug skin reactions; fainting or near-fainting after taking a new medicine; a racing or dangerously irregular heartbeat with chest discomfort; or new confusion with a rash and fever.
Call your care team the same day for: a rash that is itchy but not spreading or blistering; persistent nausea, vomiting, or diarrhea after a new medicine; jaundice — yellowing of eyes or skin with dark urine; unusually dark or reduced urine; severe dizziness on standing; repeated nosebleeds, gum bleeding, or large bruises after starting a blood thinner; numbness, tingling, or hearing changes; or mood changes, severe anxiety, or depression after a new medicine.
Practical habits reduce the risk: take new medicines one at a time where feasible so any reaction has an obvious culprit; keep the patient information leaflet and read the 'seek medical help if' section; do not restart a medicine that previously caused a reaction — tell every doctor it happened and what the reaction was; and report suspected reactions to your pharmacist, who can flag them in your record and suggest alternatives.
When you call about a reaction, have ready: the medicine name and strength, when you started it, when the reaction began, what it looks like, a photo if visible, and anything you took for it. Most reactions are manageable with a switch or dose change — but only when reported. The dangerous ones, per the first paragraph, are managed in emergency departments. Either way, the medicine story belongs in your records, told by you, early.""",
        ["drug reaction", "anaphylaxis", "rash", "side effects"],
    ),
    chunk(
        "Mood and mental health after hospitalization: when to reach out",
        "guideline", "red_flags",
        """Feeling low, anxious, tearful, or unusually irritable after a hospital stay is common and does not mean you are ungrateful or weak. Illness, pain, lost independence, disrupted sleep, and strong medicines all affect mood, and recovery is as much psychological as physical. For most people, mood lifts gradually as strength returns — usually within a few weeks. Getting dressed daily, opening curtains, short walks, talking honestly with someone you trust, and celebrating small returned abilities genuinely help.
Reach out to your care team the same week for: low mood or anxiety lasting more than two weeks without lifting; losing interest in things you normally enjoy; sleep that stays broken or excessive; appetite loss beyond your physical recovery; feeling like a burden; or finding that worry about your health is stopping you from doing your rehabilitation. These are treatable, and treating them speeds physical recovery too — mood and mobility climb together.
Seek help urgently — same day — for: thoughts of harming yourself, thoughts that you would be better off dead, a plan forming, or urges to act on despair. In that moment, do not be alone: tell a family member or friend right now, call your care team, a mental health helpline for your region, or emergency services. Remove means of harm from your reach if you can, and stay with someone until help arrives. If you are worried about a family member who has become withdrawn, hopeless, or is talking about death, ask them directly and kindly — asking does not plant the idea, it opens the door — and help them make the call.
Caregivers need this page too: exhaustion, irritability, and hopelessness in the person doing the caring are common and deserve the same early attention. There is no shame in any of this; hospitals treat broken bones and broken spirits with equal seriousness, and the strongest recovery stories almost always include someone who asked for help at the right moment.""",
        ["mood", "mental health", "self-harm", "support"],
    ),
    chunk(
        "Recovery soreness or warning-sign pain? How to tell them apart",
        "guideline", "red_flags",
        """After discharge, every new ache triggers the same question: is this normal recovery or a warning? Use the trend, the character, and the company it keeps.
The trend: normal post-procedure pain peaks in the first two to three days and then trends downward week over week. Pain that suddenly escalates after having been improving, or new pain appearing after a quiet patch, is worth attention regardless of where it is. The character: healing pain is typically sore, aching, pulled, or bruised-feeling, worse with movement or position changes, and eased by your prescribed pain relief and rest. Warning pain tends to be different from everything before it: sharp and stabbing with breathing, crushing or pressing, burning with numbness, throbbing with a hot swollen area, or severe and unresponsive to usual painkillers.
The company it keeps — this is the strongest signal. Normal soreness arrives alone. Worrying pain arrives with friends: fever or chills; a wound becoming red, hot, swollen, or leaking; a hot swollen calf; breathlessness; dizziness or fainting; vomiting; confusion; black or bloody stools; or a pulse that feels racing or irregular. Pain plus any of those companions needs a same-day call to your care team — or emergency services if the combination includes chest pain with pressure, breathlessness at rest, one-sided weakness or slurred speech, uncontrolled bleeding, or thoughts of self-harm.
Practical tests at home: press gently on the painful spot — pain that exactly reproduces when pressing a specific point on a muscle or the rib edge and changes with position behaves like musculoskeletal soreness; observe whether it eases with the pain schedule and gentle movement; and compare with yesterday rather than with zero. Photograph anything visible. If after all this you remain unsure, that uncertainty is your permission slip: call your care team and describe it. They would rather triage ten phone calls of ordinary soreness than miss one case where it was not soreness at all.""",
        ["pain assessment", "soreness", "red flags", "trend"],
    ),
]
