"""What each ARIA risk tier means and how the ARIA follow-up process works
(spec §10) — written to match the platform's actual behavior."""

from seed import chunk

CHUNKS = [
    chunk(
        "What your LOW risk tier means",
        "guideline", "process",
        """ARIA's risk engine read your discharge information and placed you in the LOW tier, which is good news with a simple meaning: your combined picture — diagnosis, age, vital signs, medicines, and warning signals in your documents — suggests a smooth recovery is the most likely path. LOW does not mean 'nothing to watch'; it means the early warning signs that would worry the system are absent so far.
What to expect from ARIA at LOW risk: SMS monitoring rather than phone calls. You will receive text reminders covering your medicines, warning signs to watch, and check-in prompts during a monitoring window of about five days after discharge, and you can reply to those messages; replies are read by your care team's dashboard. No voice call is routinely scheduled at this tier because the protocol reserves calls for situations where closer contact adds value.
What ARIA hopes you will do anyway: take medicines exactly as prescribed, keep every follow-up appointment, walk daily as advised, watch your wound or condition-specific warning signs, and use the Ask ARIA chat for questions that come up — about your medicines, diet, activity limits, or anything in your discharge instructions that is unclear.
When LOW risk changes meaning: contact your care team directly — or emergency services for the red-flag symptoms this Copilot lists — if you develop new chest pain, breathlessness, uncontrolled bleeding, one-sided weakness or slurred speech, fainting, fever with shaking chills, or a wound that is worsening rather than improving. New warning signs can change your tier, and your care team reviews risk if your condition changes.
Think of LOW risk as a green traffic light with mirrors: you proceed with confidence, keep glancing around, and the system keeps watching with you. Most people at this tier need nothing more than their reminders and their scheduled follow-up — and that quiet success is exactly the outcome ARIA exists to protect.""",
        ["low risk", "SMS monitoring", "expectations"],
    ),
    chunk(
        "What your MEDIUM risk tier means",
        "guideline", "process",
        """ARIA placed you in the MEDIUM tier because its risk engine found a combination worth closer attention — perhaps a chronic condition like diabetes or COPD, a medicine needing monitoring, a prior admission, or warning signals in your discharge documents. MEDIUM means: recoverable, but the first days matter more.
What to expect from ARIA at MEDIUM risk: an SMS monitoring schedule across about seven days, plus a voice follow-up call. The system places calls at this tier because talking through medicines, symptoms, and questions catches small problems while they are small. Your call and reminders are part of a schedule you can see in your monitoring calendar; answer them even on a good day, because the day's 'nothing to report' is itself useful information to your care team.
What makes the biggest difference at this tier: medicines taken exactly as prescribed — adherence is the single strongest lever MEDIUM-risk patients control; daily attention to the specific warning signs your discharge sheet lists; steady gentle activity as advised; and asking questions early rather than accumulating worry. The Ask ARIA chat exists precisely for this tier: ask about your medicines, your diet, what a symptom means, what the follow-up process will look like.
Escalation built into your tier: if you describe warning-sign symptoms during an SMS reply or a call, the system can schedule family or doctor notifications — and if you ever describe an emergency in this chat, the Copilot stops and pushes emergency contact immediately, because conversations never replace the judgment that urgent symptoms deserve.
Do not read MEDIUM as a verdict on your health; read it as a resource allocation. It means ARIA and your care team are leaning in a little closer during the window when leaning in pays most. Most MEDIUM-risk recoveries complete their monitoring window uneventfully — and the monitoring is a large part of why.""",
        ["medium risk", "voice call", "adherence", "monitoring window"],
    ),
    chunk(
        "What your HIGH risk tier means",
        "guideline", "process",
        """ARIA placed you in the HIGH tier because its risk engine found strong signals — a serious diagnosis such as heart failure, stroke, kidney disease, or pneumonia; abnormal vital signs; many medicines; or a prior admission pattern. HIGH is not a prediction of failure; it is a decision that this recovery gets the fullest watching.
What to expect from ARIA at HIGH risk: SMS monitoring across about ten days, a voice follow-up call as part of the schedule, and — if warning signs appear in your replies — family and doctor notifications are arranged so the people who can act are informed quickly. Your monitoring calendar shows the plan day by day. Calls may feel repetitive; they are deliberately so, because high-risk recoveries are won on early detection, and repetition is how detection works.
What matters most at this tier: take every medicine exactly as prescribed, including the ones that make you feel nothing; keep the daily habits your discharge sheet names — for heart conditions that usually means daily weights and salt awareness, for diabetes it means sugars and feet, for lung conditions it means breathing exercises and inhaler technique; watch your wound or condition-specific signs daily; and keep every follow-up appointment, because HIGH-risk plans are built around them.
Use this Copilot freely for questions — about your medicines, diet, activity limits, what a symptom pattern means, what your care schedule will look like. But know its one hard rule, which is your rule too: anything that sounds like an emergency in this chat — chest pain, breathlessness, heavy bleeding, stroke signs, fainting, severe allergic reaction, thoughts of self-harm — stops the conversation and directs you to emergency services and your care team immediately. That is not the Copilot declining to help; it is the system doing precisely what HIGH-risk monitoring exists to do, as fast as possible.
A HIGH tier that completes its window without incident is the intended outcome, and your daily habits are the main character in that story.""",
        ["high risk", "monitoring", "family alerts", "vigilance"],
    ),
    chunk(
        "The SMS reminders you will receive",
        "guideline", "process",
        """ARIA's SMS reminders are the platform's daily heartbeat, and they are simple by design so they work on any phone. Expect messages at a fixed morning time during your monitoring window — typically five days at LOW risk, seven at MEDIUM, ten at HIGH. Each message asks about the things your condition needs watched: whether medicines were taken, how you are feeling, and the specific warning signs relevant to your diagnosis — for example wound redness after surgery, breathlessness for heart or lung conditions, or sugars for diabetes.
Reply to them. The replies land on your care team's dashboard, where they are read and acted on: a 'medicine taken' builds your adherence record; a described symptom can schedule a nurse review, a family notification, or a doctor alert depending on what it sounds like. If a message asks you to reply and you do not, the system notes the silence; repeated unanswered messages at higher tiers trigger a call instead. If you cannot reply by text — vision, typing, or language difficulties — tell your care team and a family member can be the designated responder.
A few practical notes: the messages come from a system number, so save it under 'ARIA' when the first one arrives; do not reply with personal financial information — no message will ever ask for card numbers or passwords; message and data rates follow your mobile plan; and if you change your phone number, update it with your care team or the reminders will knock on a door you no longer answer.
What the SMS is not: it is not a replacement for emergency services. If you are experiencing emergency symptoms — chest pain, breathlessness, heavy bleeding, stroke signs, fainting — call emergency services first; do not type a text and wait. For everything short of that, the daily SMS is the lightest, most reliable touchpoint in your recovery — ten seconds a day that quietly connect you to people watching your progress.""",
        ["SMS reminders", "replies", "monitoring window"],
    ),
    chunk(
        "The voice follow-up call: what happens and why",
        "guideline", "process",
        """If your risk tier is MEDIUM or HIGH, ARIA's follow-up process includes a voice call, placed at the scheduled time in your monitoring calendar. People sometimes feel nervous about calls from automated systems, so here is exactly what to expect.
The call asks structured questions: how you are feeling today; whether medicines were taken as prescribed; and condition-specific checks — for heart conditions, breathing, swelling, and weight changes; for lung conditions, breathlessness and inhaler use; for diabetes, sugars and feet; after surgery, wound appearance, pain trend, and fever. You answer by voice or keypad, and your answers appear on the care team's dashboard in real time. Depending on your answers, the system can schedule next steps: a repeat call, a family notification, or a doctor review. A difficult or concerning answer can also route you to a human nurse promptly — the automation exists to widen the net, not to replace the people in it.
Tips for a good call: answer even when you feel fine; 'all good today' is exactly the data the dashboard wants. Have your medicine boxes nearby in case you are asked what you took. If you miss the call, the system logs it and your schedule continues; a consistently missed call usually triggers a family notice, so if calls arrive at a bad time, tell your care team to shift the window.
The call is a safety instrument, not a test: nobody is judged for a rough day, and reporting a new symptom honestly is the whole point — the earlier a wobble is spoken, the smaller it stays. And as with every ARIA channel: the call is not for emergencies. If you are experiencing emergency symptoms during or before a call, hang up and call emergency services directly. For everything else, ten honest minutes on the phone is one of the highest-value touches in your entire recovery plan.""",
        ["voice call", "follow-up", "care team"],
    ),
    chunk(
        "Your monitoring window and the ARIA calendar",
        "guideline", "process",
        """Your recovery is monitored for a defined window that starts at discharge — about five days at LOW risk, seven at MEDIUM, and ten at HIGH. The monitoring calendar shows this window day by day: which days carry an SMS reminder, which days include a voice call for your tier, and where family or doctor notifications are scheduled if warning signs appear. Think of it as the weather forecast for your follow-up: nothing on it should surprise you.
The window is not arbitrary. Readmission risk is not spread evenly across recovery — it concentrates in the first days, when medicines are new, wounds are youngest, and activity is changing daily. The calendar front-loads attention exactly there and tapers as your body proves the trend.
How to use it well: look at it once so you know which days expect a call; answer the SMS on every scheduled day, including boring days; and treat the final days as seriously as the first — the temptation to coast late in the window is natural, and the late window still catches real problems. When the window ends, your routine follow-up appointments take over; the calendar ending does not mean recovery is over, it means the automated net has done its concentrated work.
If things change mid-window — you feel notably worse, a new symptom appears, you are readmitted to a hospital, or your medicines change — tell your care team, because the plan can be extended or intensified. A calendar is a plan, not a cage: it bends to your actual recovery, and it exists so that neither you nor your family carries the whole job of remembering what to watch. Between the calendar, the SMS replies, the calls, and this Copilot for questions, the window is fully watched — your part is simply to show up for your ten seconds a day.""",
        ["monitoring calendar", "window", "readmission"],
    ),
    chunk(
        "How family and doctor alerts work",
        "guideline", "process",
        """ARIA includes a care-circle design: your recovery is not watched by you and a dashboard alone, but by the people you named and the clinicians responsible for you. Here is how the alerting works, so it feels like a net rather than a surveillance system.
Scheduled notifications: at certain tiers and days, family and doctor notifications are part of the plan itself — for example, family escalation windows are built into HIGH-risk schedules, and MEDIUM-risk schedules include a doctor review within the first days. These are routine parts of the monitoring calendar, not reactions to anything you did.
Triggered notifications: when your SMS replies, call answers, or risk signals describe something that needs hands-on attention — worsening symptoms, missed medicines at high tier, unanswered contact attempts — the system schedules or sends the matching notice: family members may be informed so someone can check on you in person, and your doctor or care team receives a structured summary so review is informed before it begins.
Copilot escalations: if you ever describe an emergency-sounding symptom in the Ask ARIA chat, the Copilot immediately directs you to emergency services and your care team, and it files an alert through this same pipeline so the clinical side knows an emergency pattern was described — with a record of the signal category, kept minimal and without your raw chat text.
What this means practically: keep your listed contact details current — a family phone number that has changed is a safety hole; tell family members what to expect so a 'message from ARIA' does not alarm them; and remember the alerts describe signals, not verdicts — a family alert is a request for presence and care, not a punishment or an accusation. Everything in this design points one direction: shortening the distance between 'something feels wrong' and 'someone who can help knows'. If you would like your care circle adjusted — someone added or removed — ask your care team; it is your circle, and it works best when it contains exactly the people you trust.""",
        ["family alerts", "doctor alerts", "care circle"],
    ),
    chunk(
        "What the ARIA risk score is — and what it is not",
        "guideline", "process",
        """When ARIA reads your discharge documents, it produces a risk readmission score from 1 to 100 and a tier — LOW, MEDIUM, or HIGH. Understanding what that number is, and what it is not, helps you use it well.
What it is: a structured first-pass summary of signals in your record at discharge — your diagnosis and how serious it tends to be for recovery, your age, abnormal vital signs recorded in your documents, how many medicines you take and whether any need close monitoring, prior admissions, and adherence or support concerns the documents mention. Each signal contributes points; the total maps to a tier with a matching follow-up plan: monitoring window length, whether you get calls, and how the care circle is arranged.
What it is not: it is not a diagnosis, not a prophecy, and not a grade of you as a person. It was computed once, from documents, at a moment in time; it does not know how determined you are, how good your home support is, or how you will feel next Tuesday. It can be wrong in both directions — a HIGH tier patient can sail through, a LOW tier patient can hit a complication. That is why the tier triggers watching rather than treatment, and why the daily SMS, the calls, and this chat exist: they keep collecting fresh information that documents alone cannot provide.
If your tier seems wrong, say so at your follow-up — clinicians can adjust the plan around the number, and new symptoms can re-rank attention regardless of the tier. What the score is genuinely good at is one thing: making sure nobody's recovery goes unwatched, and that the watching is proportionate to what the documents showed. Use it as you would a weather forecast — plan sensibly around it, carry the umbrella it suggests, and remember that it is describing conditions, not commanding your journey. Your daily habits remain the real driver of this story.""",
        ["risk score", "risk engine", "tiers explained"],
    ),
]
