"""Wound care and infection warning signs after common procedures (spec §10)."""

from seed import chunk

CHUNKS = [
    chunk(
        "Caring for a surgical incision at home",
        "guideline", "wound",
        """Caring for your incision is one of the most useful things you can do for a smooth recovery. Wash your hands with soap and water before and every time you touch the area, even if you are only checking it. Keep the incision clean and dry according to the instructions your hospital gave you, because different closures and dressings have different rules. If your care team told you to change the dressing, wash your hands, remove the old dressing gently by peeling it toward the incision rather than straight up, and put on a fresh clean dressing. Do not pick at scabs, pull glue edges, or remove steri-strips early, since those protect the wound while new skin forms.
Check the incision once a day in good light. A healing incision is usually a little pink, slightly puffy, and mildly tender in the first days. What you are watching for is change: spreading redness, increasing swelling, warmth that is clearly hotter than the surrounding skin, fluid that becomes cloudy yellow or green, a bad smell, or pain that gets worse after day three instead of better. A small amount of clear or light pink fluid on the dressing in the first day or two is common.
Wear loose clothing over the area so nothing rubs. Eat regular meals with enough protein, because wound healing uses extra energy. Keep follow-up appointments even when everything looks fine, since your care team is tracking progress you may not notice. If you are unsure whether what you see is normal, take a photo each day with good lighting so you can compare, and message or call your care team with questions rather than guessing. If the incision suddenly opens, bleeds heavily, or you develop fever with chills, contact your care team urgently or seek emergency care.""",
        ["incision", "surgery", "dressing", "healing", "infection signs"],
    ),
    chunk(
        "Hand hygiene and safe dressing changes",
        "guideline", "wound",
        """Clean hands are the single most effective way to keep a healing wound free of infection. Wash with soap and running water for about twenty seconds, getting between fingers and under nails, then dry with a clean towel. Use an alcohol-based hand rub when soap and water are not available, rubbing until hands are dry. Do this before touching the wound or dressing, after using the toilet, after coughing or sneezing, after handling pets, and after touching anything dirty such as laundry or bin lids.
Set up a small clean area before a dressing change: a washed table surface, a fresh dressing pack, a small bag for the old dressing, and tape or the supplies your team gave you. Close windows to avoid dust, keep pets out of the room, and put phone screens out of reach. Remove the old dressing slowly; if it sticks, dampen it with clean warm water or saline rather than pulling. Never touch the pad surface that will lie against the wound, and never re-use dressings that have dropped.
If your plan includes cleaning the wound, use the solution your team recommended, wiping from the cleanest part of the wound outward in one direction, and use each wipe or gauze piece once. Pat the skin around it dry with a fresh towel or gauze. Wash your hands again when you finish, and write down anything you noticed, such as a spot of fluid or a loosened edge, so you can report change over time.
Ask a family member to help if you cannot see the area well or cannot reach it. If you run out of supplies, contact your care team rather than improvising with household items. Any sudden increase in pain during a change, fresh bleeding that does not settle with gentle pressure, or a dressing that keeps soaking through should be reported the same day.""",
        ["hand hygiene", "dressing change", "infection prevention", "supplies"],
    ),
    chunk(
        "Signs of wound infection: when to call the care team",
        "guideline", "red_flags",
        """Knowing the difference between normal healing and infection helps you act at the right time. Normal healing includes mild tenderness, a thin pink or red edge, slight puffiness, small bruises near the incision, and a tiny amount of clear or blood-tinged fluid in the first day or two. These should steadily improve each day.
Call your care team promptly, the same day, if you notice: increasing redness that spreads outward from the incision; the skin around it becoming hot and firm; new or worsening pain rather than improving comfort; cloudy, yellow, or green discharge; a foul smell; the wound edges separating; a tender lump near the incision; or fever above 38 degrees Celsius (100.4 Fahrenheit) without another clear cause. These suggest the wound needs professional review, cleaning, or antibiotics, and earlier treatment almost always means simpler treatment.
Seek emergency care immediately for: heavy or uncontrolled bleeding from the wound; sudden opening of the incision with visible tissue; confusion or severe drowsiness with fever; spreading red streaks up the limb; breathing difficulty; or feeling suddenly and severely unwell with chills and shaking. These can indicate problems that move fast and need hands-on care, not a waiting appointment.
Two habits make this easier. First, look at the wound once daily in the same good light and compare with yesterday. Second, take a photo every day; photos are honest witnesses when memory is not. If you are simply unsure, it is always reasonable to contact your care team and describe what you see. Nobody minds a false alarm, but an infection that waits can undo a good recovery. Remember your discharge instructions list the exact numbers to call; keep them saved in your phone.""",
        ["infection", "fever", "discharge", "emergency", "wound check"],
    ),
    chunk(
        "How a surgical wound heals: timeline and what to expect",
        "guideline", "wound",
        """Healing follows a predictable rhythm, and knowing it turns worry into confidence. In the first one to four days, the body seals and cleans the wound. Expect mild swelling, pinkness, tenderness, and sometimes small bruises. Fluid may be slightly pink; this settles. Pain is usually strongest here and should respond to the pain relief your team prescribed.
From roughly day four to week two, the building phase takes over. New skin cells creep across the surface and collagen stitches the deeper layers together. The incision looks pink to dark red, feels firm like a ridge, and may itch as nerves regrow, which is a good sign. This is also the stretchiest period for the scar, so follow your team's advice about limiting lifting or straining that pulls on the edges. If you had staples or stitches due for removal around day seven to fourteen, keep that appointment.
From week two to about six weeks, strength builds quickly. Redness fades toward pink or brown, the ridge softens, and tenderness disappears. Numb patches or tingling near the scar are common while small nerves recover and can take months to settle. From six weeks onward, the scar matures, becoming paler and flatter over six to twelve months, sometimes longer.
Things that reliably slow healing include smoking and vaping, uncontrolled diabetes, poor food intake, excess strain across the wound, and repeated friction from tight clothes. Things that reliably help are protein-rich meals, steady hydration, gentle movement as advised, sleep, and keeping dressings clean and dry.
Judge progress by trend, not by one anxious look in poor lighting. Compare today with yesterday: is redness spreading or fading, is pain rising or falling, is fluid increasing or gone? A trend in the wrong direction after day three is your cue to contact your care team, even if every individual change looks small.""",
        ["healing timeline", "expectations", "scar", "recovery phases"],
    ),
    chunk(
        "Stitches, staples, steri-strips and glue: care and removal",
        "guideline", "wound",
        """Your incision may be closed with stitches, staples, steri-strips, surgical glue, or a combination. Each has simple rules. Stitches under the skin dissolve on their own and do not need removal; surface stitches usually come out around seven to fourteen days depending on where the surgery was. Staples follow a similar schedule and are removed quickly at the clinic with a special remover, which is far more comfortable than people expect.
Keep steri-strips on until they peel by themselves, usually ten to fourteen days. Trim the curled edges with clean scissors if they catch on clothing, but do not pull them off early, because they support the skin while it gains strength. Surgical glue forms a film that flakes off naturally in one to three weeks. Do not scratch, scrub, or pick at it, do not apply ointments or creams over it, and pat it dry after washing unless your team said otherwise.
Whatever the closure material, avoid stretching the area for the first few weeks: no heavy lifting, no pushing or pulling heavy objects, and no sports until your team clears you. Supporting the incision with your hand or a small pillow when you cough, sneeze, laugh, or change position dramatically reduces pull and pain, especially after chest or abdominal surgery.
Contact your care team if a stitch or staple pokes out and snags, if the wound edges gape, if glue lifts early leaving an open gap, or if any closure area becomes increasingly red, swollen, hot, or weepy. If part of the wound opens after stitches are removed and it is small and dry, cover it and call the same day; if it opens and bleeds heavily or you can see deeper tissue, press gently with clean gauze and seek urgent care. Never try to re-stick or stitch a wound yourself, and never apply household adhesives to skin.""",
        ["stitches", "staples", "steri-strips", "glue", "removal"],
    ),
    chunk(
        "Showering and bathing with a healing incision",
        "guideline", "activity",
        """Water rules differ by dressing and closure type, so the written instructions from your hospital win over general advice. As a broad pattern: simple closed incisions without a dressing, or with a waterproof dressing, can usually shower from the second or third day after surgery. Pat the area dry gently with a clean towel afterward rather than rubbing. Steri-strips and glue tolerate brief splashes but soften with soaking, so keep showers short and warm rather than hot.
Avoid baths, swimming pools, hot tubs, and soaking in the bathtub until your care team confirms the wound is fully sealed, usually two weeks or more. Soaking softens healing tissue, encourages germs, and loosens glue and strips prematurely. A sponge bath is a good substitute during the first week if your incision must stay dry.
Use plain mild soap and running water over the incision; do not scrub it, and do not aim a strong jet directly at it. Avoid products with fragrance, exfoliants, or alcohol near the wound. If your dressing accidentally becomes soaked, pat it dry and replace it with a clean one if you were given spares; if the wound underneath looks wet and you were told to keep it dry, call your care team for advice the same day.
For incisions on the head after hair surgery, use gentle baby shampoo and let water run over rather than scrubbing. After hand or foot surgery, waterproof covers or a plastic bag taped above the dressing let you shower while keeping the area dry. If in doubt about whether your dressing is waterproof, ask before your first shower rather than guessing. Comfortable washing is part of recovery; feeling clean lifts mood as well as hygiene, so aim for a short shower routine that respects the wound instead of avoiding washing altogether.""",
        ["showering", "bathing", "dressing", "water", "hygiene"],
    ),
    chunk(
        "Surgical drains at home: the basics",
        "guideline", "wound",
        """Some operations leave a small drain in place to let fluid escape so it does not collect under the incision. Drains are normal, temporary, and usually removed within days to a couple of weeks. Your team will show you how to care for it, and these points help you follow along.
Keep the drain bulb below the level of the wound at all times, clipped to your waistband or a lanyard when you walk, so fluid flows out instead of back. Empty the bulb when it is about half full or at the times your team specified, usually two to three times a day. To empty it: wash your hands, open the spout, squeeze the contents into the measuring container you were given, note the amount and its color on the chart they provided, compress the bulb fully to recreate the gentle suction, and close the cap. Wash your hands afterward.
Watch the insertion site daily the same way you watch an incision: increasing redness, heat, leaking around the tube, or new pain deserve a call. Fluid amounts should generally decrease day by day and lighten in color, from bloody to pale straw; your team will tell you the numbers that trigger a visit. A sudden increase in bright red fluid, a drain that stops producing entirely when it was producing well, or a bulb that will not hold suction are all reasons to contact your care team promptly.
Shower only if your team said it is allowed with a drain in place; otherwise sponge-bathe, keeping the site dry. Sleep with the drain secured where it cannot be pulled, and never cut or shorten the tubing. Bring your fluid chart and the drain itself to every appointment. Removal is usually quick and causes brief pulling, not pain. If a drain accidentally falls out completely, cover the site with clean gauze and call your care team immediately rather than trying to reinsert anything.""",
        ["drain", "JP drain", "suction", "output chart"],
    ),
    chunk(
        "Caring for a diabetic foot wound",
        "guideline", "wound",
        """Foot wounds in people with diabetes need extra respect because healing is slower and infection can escalate quietly. Inspect both feet every day, using a mirror or asking a family member for the underside and between toes. You are looking for breaks in skin, blisters, redness, swelling, warmth, callus with dark spots, discharge, or anything new. Reduced sensation means a wound can grow without pain warning you, so inspection replaces pain as your alarm system.
Keep the wound covered and moist in the way your team prescribed, not dry and exposed; modern healing happens best under an appropriate dressing. Do not walk barefoot, even indoors, and wear the offloading shoe or boot you were given if the wound is on the sole, because every step on the wound delays closure. Wash daily with lukewarm water and mild soap, test the water with your elbow or a thermometer since damaged nerves can misjudge heat, and dry carefully between toes.
Never treat foot wounds with home remedies: no hydrogen peroxide, no iodine soaks, no cutting callus yourself, no over-the-counter wart removers on a wound. Check your blood sugars as instructed, because high sugars feed infection and stall healing; a foot wound plus sugars running high needs same-day contact with your team.
Seek urgent care for: spreading redness or red streaks, swelling that makes shoes tight, pus or bad smell, black tissue, new fever or chills, or pain that becomes severe in a foot that previously had none. Attend every foot clinic appointment, even when it looks better, because the team is also checking circulation and pressure points. Healing a diabetic foot wound is a partnership between your daily care and professional review, and your consistency at home carries most of the weight.""",
        ["diabetic foot", "ulcer", "offloading", "inspection"],
    ),
    chunk(
        "Looking after your scar for the next year",
        "guideline", "wound",
        """Once your incision has fully closed and any glue or strips have fallen off, the long job of scar maturation begins, lasting six to eighteen months. Early care pays off for years. Protect new scars from sunlight: fresh scar tissue burns easily and darkens permanently, so cover it with clothing or use a broad-spectrum sunscreen of SPF 30 or higher once the skin has healed over, whenever it might see daylight, for at least a year.
Keep the healed skin moisturized with a plain, fragrance-free cream once or twice a day; massaging gently in small circles for a minute or two, once your team confirms it is safe, softens the tissue and reduces sensitivity. Firm, raised, itchy, or red ridges that grow beyond the original incision line can be hypertrophic or keloid scarring; mention them early, because early treatment works better and your care team has several options.
Some tightness, pulling, numbness, or odd electric sensations are normal as nerves regenerate and can continue for months. Gentle movement and stretching of the area, as advised at follow-up, prevents stiffness, especially for scars near joints. Avoid smoking, which narrows the small vessels that feed maturing tissue.
If the scar pulls your skin into a tight band that limits movement, or becomes increasingly painful rather than settling, ask about scar therapy rather than waiting a year. Patience is part of the plan: scars look their angriest around weeks four to eight and improve steadily after that, so judge at three-month intervals. Take a photo every month in similar light if you want an honest record of progress. And keep the rest of the recovery rules going, because good nutrition, steady activity, and controlled blood sugars remain the strongest medicines a scar has.""",
        ["scar care", "sunscreen", "massage", "keloid", "maturation"],
    ),
    chunk(
        "What never to put on or do to a healing wound",
        "guideline", "wound",
        """Well-meaning home treatments can quietly undo professional repair. Do not apply hydrogen peroxide, rubbing alcohol, or undiluted iodine to a healing wound; they damage the fresh cells that are trying to close it and can slow healing significantly. Clean water, saline, or the specific solution your team prescribed are enough. Do not apply butter, toothpaste, oils, herbal pastes, turmeric, or ice directly to surgical wounds or burns; none help and several cause harm.
Do not burst blisters near the incision, pick at scabs or glue, pull steri-strips early, or shave over a healing incision. Do not use cosmetic creams, anti-aging products, or exfoliants on the area, and keep adhesive bandages off fragile skin unless your team advised them. Avoid heating pads or hot water bottles directly on or near the wound, and avoid tight belts or waistbands that press across it.
Do not stop or change antibiotics or other medicines because the wound looks better; finish the course exactly as prescribed. Do not test the wound by pressing on it to see if it hurts, and do not ask family members to squeeze out fluid; discharge that needs removing belongs in a clinic.
Never delay care to see if things improve overnight in genuinely urgent situations: heavy bleeding, a wound that opens showing deeper tissue, spreading red streaks, fever with shaking chills, confusion, or breathing difficulty all need immediate attention. And do not compare your wound with internet photos; closures, locations, and healing speeds differ enormously. When in doubt, photograph the wound, note what changed, and call your care team. The safe rule is simple: anything you would not put in your eye does not belong on an unhealed incision, and everything you were not told to do is worth a quick question first.""",
        ["wound care mistakes", "peroxide", "home remedies", "safety"],
    ),
]
